// SPDX-License-Identifier: MPL-2.0

/// PanLL Interfaces Model — types for the language bridges panel.
///
/// Tracks Idris2 ABI definitions, Zig FFI implementations, binding
/// coverage per language, believe_me counts, and build status.
/// This panel makes the ABI/FFI standard visible and auditable.
///
/// Dependency: leaf module — no imports from other PanLL models.

/// An Idris2 ABI definition file and its verification status.
type abiDefinition = {
  /// File path relative to src/abi/.
  path: string,
  /// Module name (e.g. "Types", "Layout", "Foreign").
  moduleName: string,
  /// Number of exported functions/types.
  exportCount: int,
  /// Number of believe_me instances (should be 0).
  believeMeCount: int,
  /// Whether all proofs pass (%default total, no holes).
  verified: bool,
}

/// A Zig FFI implementation and its build status.
type ffiImplementation = {
  /// File path relative to ffi/zig/src/.
  path: string,
  /// Number of exported C-compatible functions.
  exportCount: int,
  /// Build status: "ok", "error", "untested".
  buildStatus: string,
  /// Error message if build failed.
  buildError: option<string>,
}

/// Binding coverage for a specific target language.
type bindingCoverage = {
  /// Target language name (e.g. "Rust", "ReScript", "Gleam").
  language: string,
  /// Number of ABI functions with bindings.
  boundCount: int,
  /// Total ABI functions that need bindings.
  totalCount: int,
  /// Coverage percentage (0.0–100.0).
  coverage: float,
  /// Whether bindings are auto-generated or hand-written.
  autoGenerated: bool,
}

/// Category tabs for the Interfaces panel.
type interfacesCategory =
  /// Overview dashboard — ABI count, FFI status, coverage matrix.
  | IfaceDashboard
  /// Idris2 ABI definitions inventory.
  | IfaceAbi
  /// Zig FFI implementations.
  | IfaceFfi
  /// Per-language binding coverage matrix.
  | IfaceBindings

/// Root state for the Interfaces panel.
type interfacesState = {
  /// Whether data has been loaded.
  loaded: bool,
  /// Whether scanning is in progress.
  loading: bool,
  /// Error from the last operation.
  error: option<string>,
  /// Idris2 ABI definitions.
  abiDefs: array<abiDefinition>,
  /// Zig FFI implementations.
  ffiImpls: array<ffiImplementation>,
  /// Per-language binding coverage.
  bindings: array<bindingCoverage>,
  /// Active category tab.
  activeCategory: interfacesCategory,
  /// Total believe_me count across all ABI files (should be 0).
  totalBelieveMe: int,
}
