// SPDX-License-Identifier: MPL-2.0

/// PanLL VAB (Verified Assembly Building) Model Types.
///
/// State types for the KSP VAB-inspired server component assembly panel.
/// Users compose verified protocol/core/connector components from the
/// proven-servers catalog (108 components) onto a virtual server rack,
/// with real-time dependency checking and capability enumeration.
///
/// This module has NO dependencies on other PanLL modules — leaf of the
/// type dependency graph, following the same pattern as PaneModel.

/// Component categories — the 11 sidebar icons in the VAB.
/// Mirrors the proven-servers project structure: 8 core primitives,
/// 94 protocols across 9 domains, and 6 connector interfaces.
type vabCategory =
  | VabCore // Core primitives (socket, frame, fsm, wire, compose, tls, config, audit)
  | VabNetwork // Network protocols (tcp, udp, quic, sctp, etc.)
  | VabDns // DNS protocols (dns-resolver, dns-authoritative, mdns, doh, dot)
  | VabWeb // Web protocols (httpd, http2, http3, websocket, grpc, graphql, rest, sse)
  | VabIot // IoT protocols (mqtt, coap, amqp, lwm2m, zigbee, zwave, matter)
  | VabEmail // Email protocols (smtp, imap, pop3, dkim, spf, dmarc)
  | VabSecurity // Security protocols (tls, dtls, noise, ssh, kerberos, oauth, saml, oidc)
  | VabData // Data protocols (ldap, nfs, ftp, rsync, s3, redis, memcached)
  | VabApplication // Application protocols (sip, xmpp, rtsp, rtp, webrtc, jsonrpc, xmlrpc)
  | VabInfrastructure // Infrastructure (syslog, snmp, ntp, bgp, ospf, dhcp, radius, diameter)
  | VabConnectors // Connector interfaces (dbconn, cacheconn, storageconn, queueconn, authconn, resolverconn)

/// A single proven-servers component that can be placed on the rack.
/// Each component declares its ports, dependency chain, capabilities,
/// and rack unit height for the visual assembly area.
type vabComponent = {
  id: string, // Unique ID, e.g. "proven-httpd"
  name: string, // Display name, e.g. "HTTP Server"
  shortName: string, // Short label for rack view, e.g. "httpd"
  category: vabCategory, // Which sidebar category this belongs to
  ports: array<int>, // TCP/UDP ports used (e.g. [80, 443])
  dependencies: array<string>, // Required component IDs (hard deps)
  softDependencies: array<string>, // Recommended component IDs (soft deps)
  capabilities: array<string>, // Capability tags this provides (e.g. ["http", "encryption"])
  description: string, // Brief description for tooltip/card
  rackUnits: int, // Visual height in rack units (1-4)
}

/// Warnings generated by the dependency checker.
/// Modelled after KSP's vehicle assembly warnings ("No engine!", "No parachute!").
type vabWarning =
  | MissingRequired(string, string) // (component needing it, missing dep ID)
  | MissingRecommended(string, string) // (component wanting it, missing soft dep ID)
  | SecurityWarning(string) // Security advisory message
  | PortConflict(int, string, string) // (port, component A, component B)

/// Capability status for the assembled server — what it CAN and CANNOT do.
/// Displayed in the bottom status bar as green/red/yellow badges.
type capabilityStatus =
  | CanDo(string) // Green: this capability is present
  | CannotDo(string) // Red: this capability is absent
  | WarningCap(string) // Yellow: capability present but with caveats

/// Sort order for the component grid.
type vabSortBy =
  | SortByName // Alphabetical by display name
  | SortByPorts // By number of ports (ascending)
  | SortByDeps // By number of dependencies (ascending)

/// An assembled server — the user's current build.
type assembledServer = {
  name: string, // User-editable server name
  components: array<string>, // Array of component IDs in rack order
}

/// The complete VAB panel state, stored as a sub-record in the main model.
type vabState = {
  visible: bool, // Whether the VAB overlay is shown
  catalog: array<vabComponent>, // Full component catalog (loaded once)
  selectedCategory: vabCategory, // Currently active sidebar category
  sortBy: vabSortBy, // Current sort order for component grid
  filterText: string, // Text filter for component search
  server: assembledServer, // The server being assembled
  warnings: array<vabWarning>, // Current dependency warnings
  capabilities: array<capabilityStatus>, // Current capability enumeration
  hoveredComponent: option<string>, // Component ID being hovered (for tooltip)
}
