// SPDX-License-Identifier: PMPL-1.0-or-later

/// Extracted sub-updater for Pane-N (Neural/Inference Tokens).
/// Handles the real-time stream of tokens generated by the LLM.
/// All paneNMsg variants: receive, clear, toggle active, monologue, agency,
/// source/category/phase filters, confidence threshold, validated/proof only.

open Model
open Msg

/// STATE TRANSITION: Pane-N (Neural/Inference Tokens)
/// Handles the real-time stream of tokens generated by the LLM.
/// All 5 paneNMsg variants: receive, clear, toggle active, monologue, agency.
let updatePaneN = (model: model, msg: paneNMsg): model => {
  let paneN = model.paneN
  let newPaneN = switch msg {
  | ReceiveToken(token) => {
      ...paneN,
      tokens: Array.concat(paneN.tokens, [token]),
      nextTokenId: paneN.nextTokenId + 1,
      activeCausalChain: [token.id],
    }
  | ClearTokens => {...paneN, tokens: [], nextTokenId: 0, activeCausalChain: []}
  | SetInferenceActive(active) => {...paneN, inferenceActive: active}
  | UpdateMonologue(text) => {...paneN, monologue: text}
  | UpdateAgency(agency) => {...paneN, agency}
  | ToggleSourceFilter(source) => {
      let current = paneN.filters.sources
      let has = current->Array.some(s => s === source)
      let newSources = if has {
        current->Array.filter(s => s !== source)
      } else {
        Array.concat(current, [source])
      }
      {...paneN, filters: {...paneN.filters, sources: newSources}}
    }
  | ToggleCategoryFilter(cat) => {
      let current = paneN.filters.categories
      let has = current->Array.some(c => c === cat)
      let newCats = if has {
        current->Array.filter(c => c !== cat)
      } else {
        Array.concat(current, [cat])
      }
      {...paneN, filters: {...paneN.filters, categories: newCats}}
    }
  | TogglePhaseFilter(phase) => {
      let current = paneN.filters.phases
      let has = current->Array.some(p => p === phase)
      let newPhases = if has {
        current->Array.filter(p => p !== phase)
      } else {
        Array.concat(current, [phase])
      }
      {...paneN, filters: {...paneN.filters, phases: newPhases}}
    }
  | SetConfidenceThreshold(threshold) => {
      ...paneN,
      filters: {...paneN.filters, confidenceThreshold: threshold},
    }
  | ToggleValidatedOnly => {
      ...paneN,
      filters: {...paneN.filters, validatedOnly: !paneN.filters.validatedOnly},
    }
  | ToggleProofOnly => {...paneN, filters: {...paneN.filters, proofOnly: !paneN.filters.proofOnly}}
  | ClearFilters => {
      ...paneN,
      filters: {
        sources: [],
        categories: [],
        phases: [],
        confidenceThreshold: 0.0,
        validatedOnly: false,
        proofOnly: false,
      },
    }
  }
  {...model, paneN: newPaneN}
}
