;; SPDX-License-Identifier: PMPL-1.0-or-later
;; NEUROSYM.scm - Neurosymbolic integration configuration for PanLL

(neurosymbolic
  (version "1.0.0")
  (last-updated "2026-02-12")

  (overview
    "PanLL is fundamentally a neurosymbolic environment, integrating symbolic constraints "
    "(Pane-L) with neural inference (Pane-N) to produce validated outputs (Pane-W). "
    "The Anti-Crash Library acts as circuit breaker, enforcing symbolic validation "
    "before neural outputs reach the shared workspace.")

  (symbolic-layer
    (location "Pane-L (Symbolic Mass)")
    (representation
      "Constraints expressed as logical expressions (strings initially, formal logic planned). "
      "Each constraint has: id, expression, active (bool), pinned (bool).")

    (constraint-types
      ((type "type-constraint")
       (example "output must be valid JSON")
       (enforcement "compile-time or runtime validation"))

      ((type "safety-constraint")
       (example "no file system writes without confirmation")
       (enforcement "runtime validation in Anti-Crash"))

      ((type "domain-constraint")
       (example "generated code must pass linter")
       (enforcement "post-generation validation"))

      ((type "logical-constraint")
       (example "if A then B (implication)")
       (enforcement "formal verification (future: Echidna)")))

    (constraint-language
      "v0.1.0: String-based expressions (human-readable, no formal semantics). "
      "v0.3.0: Planned migration to formal constraint language (potentially SMT-LIB or custom DSL). "
      "Future: Integration with Echidna for property-based testing and formal verification.")

    (constraint-editor
      "Interactive editor in Pane-L for adding, editing, removing constraints. "
      "Constraints can be pinned (sticky) across sessions. "
      "Active/inactive toggle for temporary constraint disabling."))

  (neural-layer
    (location "Pane-N (Neural Stream)")
    (representation
      "Stream of neuralToken records: {content, timestamp, confidence, validated}. "
      "Monologue field shows agent's internal reasoning (OODA loop). "
      "Agency state tracks: oodaPhase (Observe/Orient/Decide/Act), autonomyLevel, lastOperatorInput.")

    (token-generation
      "Tokens generated by AI agent (Claude, GPT, etc.) via Tauri commands. "
      "Each token timestamped and confidence-scored. "
      "Tokens flow from Pane-N → Anti-Crash → Pane-W (if validated).")

    (ooda-loop
      "OODA (Observe-Orient-Decide-Act) models agent decision-making:"
      "- Observe: Gather information from environment (Pane-L constraints, Pane-W state)"
      "- Orient: Analyse situation, update internal model"
      "- Decide: Choose action based on constraints and goals"
      "- Act: Generate token, submit to Anti-Crash for validation"
      "Operator can see current OODA phase in Pane-N.")

    (autonomy-tracking
      "autonomyLevel (0.0-1.0) indicates machine autonomy:"
      "- 0.0 = Fully instructed (operator guides every step)"
      "- 0.5 = Shared autonomy (operator sets goals, machine chooses tactics)"
      "- 1.0 = Fully autonomous (machine operates independently within constraints)"
      "lastOperatorInput timestamp tracks time since last human intervention."))

  (integration-layer
    (location "Anti-Crash Library (circuit breaker)")
    (mechanism
      "Every neural token passes through validate_inference Tauri command. "
      "Validation checks token.content against active constraints from Pane-L. "
      "If validation passes: token.validated = true, flows to Pane-W. "
      "If validation fails: RequestOperatorIntervention message, token blocked.")

    (validation-algorithm
      "v0.1.0: Simple substring matching (constraint in token.content → fail). "
      "v0.2.0: Pattern matching (regex support). "
      "v0.3.0: Formal verification (SMT solver, Echidna property-based testing). "
      "v0.4.0: Machine learning classifier (trained on operator feedback).")

    (failure-handling
      "On validation failure:"
      "1. RequestOperatorIntervention(reason) message sent to Update"
      "2. Operator shown: failed token, violated constraint, reason"
      "3. Operator choices: Reject token, Override constraint, Refine constraint"
      "4. Vexometer records correction (increases vexation index)")

    (feedback-loop
      "Operator corrections feed back to constraint refinement. "
      "Feedback-O-Tron collects (Pane-L state, Pane-N state, Pane-W state, correction). "
      "Community analyses patterns, proposes constraint improvements. "
      "Future: Active learning to improve validation accuracy."))

  (neurosymbolic-reasoning
    (approach "Hybrid: symbolic constraints guide neural generation")

    (symbolic-guides-neural
      "Constraints in Pane-L act as 'guard rails' for neural inference. "
      "Agent aware of constraints, tries to generate tokens that satisfy them. "
      "Anti-Crash validates after-the-fact, but agent aims to avoid violations.")

    (neural-refines-symbolic
      "Agent's OODA loop can suggest constraint refinements. "
      "If constraints too strict (many false positives), agent proposes relaxation. "
      "If constraints too loose (validation misses errors), agent proposes tightening. "
      "Operator reviews and approves constraint changes.")

    (emergent-behaviour
      "Binary Star co-orbit enables emergent collaboration patterns:"
      "- Agent learns operator's preferences from corrections"
      "- Operator learns to express constraints more precisely"
      "- Shared vocabulary develops over time"
      "- Orbital stability sigma measures synchronicity"))

  (performance-metrics
    (validation-latency
      "Target: <100ms for validation (v0.2.0). "
      "Current: ~10ms (simple substring matching). "
      "Future: May increase with formal verification, mitigate with caching.")

    (false-positive-rate
      "Percentage of tokens incorrectly rejected by Anti-Crash. "
      "Target: <5% (v0.3.0). "
      "Tracked via Vexometer corrections.")

    (false-negative-rate
      "Percentage of invalid tokens incorrectly passed by Anti-Crash. "
      "Target: <1% (v0.3.0). "
      "Requires operator reporting of missed errors.")

    (orbital-stability
      "Sigma value (0.0-1.0) measuring Human-Machine synchronicity. "
      "Calculated from: validation pass rate, vexation index, autonomy level. "
      "High sigma (>0.8) = stable co-orbit. "
      "Low sigma (<0.5) = drift, needs intervention."))

  (future-integrations
    ((system "Echidna")
     (purpose "Property-based testing and formal verification")
     (timeline "v0.3.0 (Q2 2026)")
     (usage "Verify Anti-Crash validation logic, constraint satisfiability"))

    ((system "BEAM/Elixir")
     (purpose "Distributed neurosymbolic reasoning")
     (timeline "v0.4.0 (Q3 2026)")
     (usage "Multi-agent coordination, parallel constraint solving"))

    ((system "SMT Solver (Z3)")
     (purpose "Formal constraint solving")
     (timeline "v0.3.0 (Q2 2026)")
     (usage "Check constraint satisfiability, generate counter-examples"))

    ((system "GPT/Claude API")
     (purpose "Neural inference backend")
     (timeline "v0.2.0 (Q1 2026)")
     (usage "Generate tokens, OODA loop reasoning, constraint suggestions"))

    ((system "Hypatia")
     (purpose "Neurosymbolic CI/CD")
     (timeline "v0.4.0 (Q3 2026)")
     (usage "Visualise build reasoning chains in PanLL UI")))

  (research-directions
    (explainable-validation
      "Generate human-readable explanations for why Anti-Crash rejected a token. "
      "Show violated constraint, relevant part of token, suggested fix.")

    (constraint-synthesis
      "Learn constraints from examples (operator provides valid/invalid tokens). "
      "Use inductive logic programming or LLM-based synthesis.")

    (multi-modal-constraints
      "Support constraints on non-textual outputs (images, audio, code ASTs). "
      "Extend Anti-Crash to validate structured data.")

    (temporal-constraints
      "Constraints over sequences of tokens (e.g., 'if token A, then token B within 5 tokens'). "
      "Requires stateful validation logic.")

    (probabilistic-constraints
      "Soft constraints with confidence scores. "
      "Allow agent to violate low-confidence constraints if overall probability high.")))
