;; SPDX-License-Identifier: PMPL-1.0-or-later
;; STATE.scm - Current state of the PanLL project

(state
  (metadata
    (version "1.0.0")
    (last-updated "2026-03-03")
    (format-spec "hyperpolymath/rsr-template-repo/spec/STATE-FORMAT-SPEC.adoc"))

  (project-context
    (name "PanLL eNSAID")
    (description "Environment for NeSy-Agentic Integrated Development")
    (tagline "Binary Star co-orbit between Human Operator and Neurosymbolic Machine")
    (status "alpha")
    (version "0.1.0")
    (license "PMPL-1.0-or-later")
    (repository "https://github.com/hyperpolymath/panll")
    (author "Jonathan D.A. Jewell <jonathan.jewell@open.ac.uk>"))

  (current-position
    (milestone "v0.1.0 - Complete TEA Implementation")
    (completion-percentage 97)
    (phase "development")
    (current-focus "22 panel clades defined, TSDM+PanicAttack+MassPanic panels wired, Tea_Html migration complete, 0 errors 0 warnings")
    (status-summary "97% complete - All 22 panels wired into TEA cycle, 22 panel clades defined, JSX→Tea_Html migration, Float deprecations fixed, Deno task integration")

    (work-completed
      ("Custom TEA implementation with full Model-Update-View cycle")
      ("33 tests passing with 100% Deno.test migration (719ms execution)")
      ("Three-pane parallel layout architecture implemented")
      ("Full UI components implemented and wired (PaneL, PaneN, PaneW, Vexometer, FeedbackOTron)")
      ("Core types: Model, Msg, symbolicConstraint, neuralToken, oodaPhase")
      ("Tauri 2.0 backend with 3 working commands (validate_inference, get_vexation_index, submit_feedback)")
      ("ReScript bindings for Tauri commands via @tauri-apps/api")
      ("Anti-Crash token gating wired into Pane-N ingestion with backend validation hooks")
      ("Event-chain import from panic-attack (paste or file load) for Pane-W")
      ("Feedback-O-Tron report type selection wired to backend")
      ("Local dev server wired for Tauri devUrl (static public/ at :8000)")
      ("Anti-Crash, Vexometer, OrbitalSync core systems sketched")
      ("AI manifest (0-AI-MANIFEST.a2ml) created for RSR compliance")
      ("npm→Deno migration complete (tests, dependencies, Tauri CLI via npx)")
      ("Vitest dependencies removed, pure Deno test infrastructure")
      ("rescript-tauri prepared for future migration (built and symlinked)")
      ("VAB (Verified Assembly Building) panel — KSP-themed visual server composer (111 components)")
      ("VabModel.res: leaf type module (vabCategory, vabComponent, vabWarning, capabilityStatus, vabState)")
      ("VabCatalog.res: hardcoded catalog of 111 proven-servers components (8 core + 94 protocols + 6 connectors + 3 extras)")
      ("VabEngine.res: dependency checking + capability computation (23 categories)")
      ("Vab.res: KSP VAB-inspired UI — green toolbar, orange accents, industrial rack, staging numbers, LEDs")
      ("BuckleScript removal: all Js.* patterns replaced with modern ReScript (JSON.*, Nullable.*, Dict.*, Math.*)")
      ("A2ML, K9 contractiles, document server components added to catalog")
      ("23 capability categories including i18n, document formats, A2ML, K9")
      ("PaneN deprecation fix: Float.toFixedWithPrecision → Float.toFixed")
      ("KSP aesthetic CSS: 25+ custom classes (vab-toolbar, vab-rack, vab-stage, vab-led-*, vab-bolt, etc.)")
      ("panic-attack assail: 4 critical (main.rs unwraps), 8 high, 0 tainted paths, 0 cross-lang vulns")
      ("TSDM directive panel: TsdmModel (3 axes, 9 tiers, cleanup steps, directives), Tsdm.res Tea_Html view, updateTsdm 19 handlers")
      ("MassPanic multi-repo scanner: MassPanicModel (scan configs, reports, comparisons), MassPanic.res Tea_Html view")
      ("PanicAttack panel: rewrote from JSX to Tea_Html, updatePanicAttack 22 handlers wired")
      ("All 22 panels wired into TEA cycle: PanelSwitcherModel, Msg, Model, Update, View, PanelRegistry")
      ("22 panel clades defined (a2ml): 9 clade kinds (directive, scanner, builder, database, network, viewer, ai, loader, meta)")
      ("JSX→Tea_Html migration complete: 3 panels converted, JSX config removed, ReactDOM dependency eliminated")
      ("Float.toFixedWithPrecision deprecation fixed across 7 files")
      ("Deno task integration: res:build/clean/watch in deno.json, removed duplicate npm scripts")
      ("Cruft removal: unused rescript-tea and rescript-webapi npm deps removed, author email fixed"))


    (work-in-progress
      ("Migration from custom TEA to official rescript-tea@0.16.0"
       (status "blocked")
       (decision "Incompatible with ReScript 11.x - keeping custom TEA")
       (tracking-doc "RESCRIPT-TEA-MIGRATION-GUIDE.md")
       (blocker "rescript-tea@0.16.0 depends on rescript-webapi@0.7.0 (incompatible with ReScript 11.1.4)")
       (rationale "Official rescript-tea not maintained since 2021, requires fork and major update effort")
       (resolution "Keep custom TEA - works perfectly (33 tests, 86.2% coverage), well-tested, documented"))
      ("Tauri backend FFI implementation"
       (status "next-up")
       (approach "Replace stubbed validation/vexation/feedback logic with real implementations")
       (commands ("validate_inference" "get_vexation_index" "submit_feedback"))
       (tracking-doc "PANLL-ARCHITECTURE-UPDATES.md"))
      ("RSR compliance"
       (status "nearly-complete")
       (completed ("AI manifest" "PMPL license" ".machine_readable/ SCM files (6 files created)" "npm→Deno migration (95%)"))
       (remaining ("Tauri CLI installation (v2.1.0 failed, trying v2.0.0)")))))

  (route-to-mvp
    (next-milestone "v0.2.0 - Enhanced UI & Components")
    (target-date "Q1 2026")

    (critical-path
      ((step 1)
       (name "Complete rescript-tea migration")
       (status "deferred")
       (decision "Moved to v0.2.0")
       (blockers ())
       (dependencies ())
       (estimated-effort "3-5 days"))

      ((step 2)
       (name "Implement functional UI components")
       (status "complete")
       (completed-date "2026-02-07")
       (note "Components were already fully implemented, just wired up in View.res")
       (blockers ())
       (dependencies ())
       (actual-effort "30 minutes"))

      ((step 3)
       (name "Complete npm→Deno migration")
       (status "complete")
       (completed-date "2026-02-07")
       (note "All 33 tests converted to Deno.test, Vitest dependencies removed")
       (blockers ())
       (dependencies ())
       (actual-effort "4 hours"))

      ((step 4)
       (name "Implement Tauri backend commands")
       (status "complete")
       (completed-date "2026-02-07")
       (note "Working Tauri commands via @tauri-apps/api, rescript-tauri ready for future migration")
       (blockers ())
       (dependencies ())
       (actual-effort "4 hours"))

      ((step 5)
       (name "v0.1.0 release")
       (status "complete")
       (completed-date "2026-02-07")
       (note "Version bumped to 0.1.0, all tests passing, production artifacts ready")
       (blockers ())
       (dependencies ("step 4"))
       (actual-effort "1 day"))))

  (blockers-and-issues
    (active-blockers
      ((id "BLOCK-1")
       (severity "medium")
       (title "Custom TEA vs official rescript-tea API differences")
       (description "Need to map custom Tea.App, Tea.Html, Tea.Cmd to official Tea_App, Tea_Html, Tea_Cmd")
       (impact "Blocks migration completion")
       (mitigation "Follow migration guide, test incrementally")
       (created "2026-02-04"))

      ((id "BLOCK-2")
       (severity "medium")
       (title "npm dependency on ReScript compiler")
       (description "ReScript compiler doesn't support Deno natively, requires Node.js/npm")
       (impact "Blocks full npm→Deno migration")
       (mitigation "Keep minimal npm usage for ReScript only, use Deno for everything else")
       (created "2026-02-07"))

      ((id "BLOCK-3")
       (severity "resolved")
       (title "Core systems wired and Storage fixed")
       (description "OrbitalSync + Contractiles wired into update loop, Storage serialize rewritten, all 81 JS tests passing")
       (impact "Unblocks v0.2.0 functional features")
       (resolved "2026-02-12")
       (created "2026-02-07")))

    (technical-debt
      ("Dual file versions (App.res + AppNew.res) need cleanup after migration")
      ("Custom TEA implementation in src/tea/ should be removed after migration")
      ("Test coverage should increase from 87-91% to 95%+")
      ("Component stubs need full implementations")
      ("Tauri backend needs proper error handling and validation logic")))

  (critical-next-actions
    ((action 1)
     (title "Complete rescript-tea migration")
     (priority "critical")
     (estimated-effort "3-5 days")
     (steps
       ("Update all imports from custom Tea to official Tea_App/Tea_Html/etc")
       ("Create custom keyboard subscriptions (rescript-tea doesn't have built-in)")
       ("Migrate Tauri command wrappers to Tea_Cmd.call")
       ("Test basic TEA cycle with official library")
       ("Remove custom src/tea/ directory")))

    ((action 2)
     (title "VeriSimDB backend module — VQL-DT interface")
     (priority "high")
     (estimated-effort "2-3 weeks")
     (steps
       ("Define PanLL ↔ VeriSimDB communication protocol (HTTP to Rust API + Elixir orchestration)")
       ("Implement Pane-L VQL-DT proof obligation display (type constraints, proof status)")
       ("Implement Pane-N agentic inference stream for VQL (suggest proofs, explain drift)")
       ("Implement Pane-W query result viewer (entity explorer, drift heatmaps)")
       ("Wire Anti-Crash to validate VQL queries before execution")
       ("Wire Vexometer to track VQL-DT cognitive load")))

    ((action 3)
     (title "Document npm→Deno migration strategy")
     (priority "high")
     (estimated-effort "1 day")
     (steps
       ("Analyze current npm dependencies")
       ("Identify Deno alternatives")
       ("Plan ReScript compiler integration with Deno")
       ("Create migration guide")
       ("Update build documentation")))

    ((action 4)
     (title "Implement functional UI components")
     (priority "medium")
     (estimated-effort "2 weeks")
     (dependencies ("action 1"))
     (steps
       ("Implement PaneL symbolic constraint editor")
       ("Implement PaneN neural stream viewer")
       ("Implement PaneW barycentre canvas")
       ("Implement Vexometer real-time display")
       ("Implement FeedbackOTron submission form"))))

  (session-history
    ((session-id "2026-03-03-opus-panels-clades")
     (date "2026-03-03")
     (agent "Claude Opus 4.6")
     (focus "Wire TSDM+PanicAttack+MassPanic panels, fix build errors, define 22 panel clades, clean cruft")
     (outcomes
       ("Created TsdmModel.res, TsdmCmd.res, TsdmModule.res, Tsdm.res — full TSDM directive panel")
       ("Created MassPanicModel.res, MassPanicCmd.res, MassPanicModule.res, MassPanic.res — multi-repo scanner")
       ("Added updateTsdm (19 handlers) and updatePanicAttack (22 handlers) sub-updaters to Update.res")
       ("Rewrote PanicAttack.res, MassPanic.res, Tsdm.res from JSX to Tea_Html (project uses local rescript-tea)")
       ("Removed JSX v4 config from rescript.json (was causing ReactDOM lookup failures)")
       ("Fixed CloudGuardPolicy.res missing comma, PanicAttackCmd.res empty record literals")
       ("Fixed Float.toFixedWithPrecision deprecation across 7 files (Hypatia, AiEngine, Playgrounds, Interfaces, Aerie, Reposystem, Fleet)")
       ("Fixed shadow warnings: qualified Model.VoiceError, suppressed warning 45 in rescript.json")
       ("Removed dead catch-all from View.res — all 22 panels now have explicit routes")
       ("Added res:build/clean/watch to deno.json (Deno-not-npm policy)")
       ("Removed duplicate npm scripts and unused deps (rescript-tea, rescript-webapi) from package.json")
       ("Defined 22 panel clades with a2ml files covering 9 kinds: directive, scanner, builder, database, network, viewer, ai, loader, meta")
       ("Created README.adoc for all 22 clade directories plus clades registry README")
       ("Updated panel-clades STATE.a2ml and ECOSYSTEM.a2ml with full coverage")
       ("Build: 0 errors, 0 warnings across 462 source files")))

    ((session-id "2026-03-01-opus-vab")
     (date "2026-03-01")
     (agent "Claude Opus 4.6")
     (focus "VAB panel implementation, KSP aesthetic redesign, BuckleScript removal, catalog expansion")
     (outcomes
       ("Created VAB (Verified Assembly Building) panel — KSP VAB-inspired server component composer")
       ("VabModel.res: 8 types (vabCategory 11 variants, vabComponent record, vabWarning 4 variants, capabilityStatus, vabState)")
       ("VabCatalog.res: 111 components (8 core + 94 protocols + 6 connectors + proven-a2ml + proven-docserver + proven-k9)")
       ("VabEngine.res: checkDependencies + computeCapabilities (23 capability categories)")
       ("Vab.res: Full KSP aesthetic — green toolbar, orange accents, industrial steel rack, staging numbers, bolt decorations, LEDs")
       ("25+ custom CSS classes in input.css: vab-toolbar, vab-sidebar, vab-rack, vab-stage, vab-led-*, vab-bolt, etc.")
       ("Wired into TEA: Model (include VabModel + vab field), Msg (vabMsg 9 variants), Update (updateVab), View (overlay)")
       ("BuckleScript fully removed: Js.Json.* → JSON.*, Js.Nullable.* → Nullable.*, Js.Dict.* → Dict.*, Js.Math.* → Math.*")
       ("Files cleaned: TauriCmd.res, Tauri.res, Contractiles.res, OrbitalSync.res")
       ("PaneN.res: Float.toFixedWithPrecision → Float.toFixed (deprecation fix)")
       ("A2ML manifest engine, K9 contractile engine, document server added to catalog")
       ("4 new capability categories: AI manifests (A2ML), K9 contractiles, Internationalisation, Document formats")
       ("Ctrl+Shift+V toggle, Escape to close, keyboard accessibility")
       ("panic-attack assail: 4 critical (Rust unwraps), 8 high, 0 tainted paths")
       ("All docs updated: design doc, AI manifest, STATE.scm")
       ("Build: ReScript 0 errors 0 warnings, Tailwind built, JS bundled")))

    ((session-id "2026-02-12-sonnet-implementation")
     (date "2026-02-12")
     (agent "Claude Sonnet 4.5")
     (focus "Attempt all 19 SONNET-TASKS.md items")
     (outcomes
       ("Claimed 19/19 tasks complete — Opus audit found 5 NOT done, 5 partial")
       ("✓ Done well: Tauri backend commands (validate, vexation, feedback)")
       ("✓ Done well: AntiCrash real validation, Tea ARIA functions, VDOM diffing")
       ("✗ NOT done: OrbitalSync never wired into update loop (dead code)")
       ("✗ NOT done: Contractiles never wired into update loop (dead code)")
       ("✗ NOT done: rescript.json set to es6-global instead of esmodule")
       ("✗ Broken: Storage.res serialize used %raw that can't access ReScript vars")
       ("✗ Broken: 14/81 JS tests failed (wrong ReScript variant compilation assumptions)")
       ("✗ Broken: Duplicate shouldAutoSave function left in Update.res")
       ("✗ Missing: recordVexationEvent TauriCmd binding")
       ("Lesson: Sonnet reported success without verifying compiled JS output")
       ("Rust: All 12 tests passing (these were done correctly)")))

    ((session-id "2026-02-12-opus-fixes")
     (date "2026-02-12")
     (agent "Claude Opus 4.6")
     (focus "Audit Sonnet's work, fix broken/incomplete implementations")
     (outcomes
       ("Audited all 19 SONNET-TASKS: found 5 NOT done, 5 partial, 9 done well")
       ("Fixed rescript.json: es6-global → esmodule (Task 1 was done wrong)")
       ("Wired OrbitalSync.sync() into Update.res update loop (was dead code)")
       ("Wired Contractiles.evaluateAll() + adaptContract() into update loop (was dead code)")
       ("Fixed Storage.res: rewrote serialize using JSON.Encode (was broken by %raw bug)")
       ("Fixed Storage.res: save/load/clear now use proper localStorage bindings")
       ("Removed duplicate shouldAutoSave function in Update.res")
       ("Added recordVexationEvent binding to TauriCmd.res")
       ("Rewrote all 4 failing test files (anti_crash, contractiles, update, storage)")
       ("Key insight: ReScript zero-arg variants compile to STRINGS, not objects")
       ("Result: 81 JS tests passing (was 67/81), 0 failures, 104ms build")))

    ((session-id "2026-02-12-sonnet-integration")
     (date "2026-02-12")
     (agent "Claude Sonnet 4.5")
     (focus "Quick wins + full Tauri integration, eventChain persistence, test coverage")
     (outcomes
       ("Fixed 7 Tea_Render.res warnings (unused rec, unused var, addEventListener return)")
       ("Removed unused open Model in FeedbackOTron.res")
       ("Fixed TauriCmd.res: @tauri-apps/api/dialog → @tauri-apps/plugin-dialog (Tauri v2)")
       ("Fixed TauriCmd.res: @tauri-apps/api/fs → @tauri-apps/plugin-fs (Tauri v2)")
       ("Wired all Tauri commands into update loop cmd switch:")
       ("  - AntiCrash(ValidateToken) → TauriCmd.validateInference")
       ("  - Vexometer(RequestVexationIndex) → TauriCmd.getVexationIndex")
       ("  - PaneW(ImportEventChainFile) → TauriCmd.openEventChainFile")
       ("  - PaneW(ImportPanicAttackerReportFile) → TauriCmd.openPanicAttackerReportFile")
       ("  - PaneW(PanicAttackerReportPathLoaded) → TauriCmd.importPanicAttackerReport (chain)")
       ("  - PaneW(ImportLatestPanicAttacker) → TauriCmd.importLatestPanicAttackerReport")
       ("  - PaneW(CheckPanicAttackerCapability) → TauriCmd.getPanicAttackerCapability")
       ("  - PaneW(LoadSecurityTimelineFile) → TauriCmd.openSecurityTimelineFile")
       ("  - PaneW(LaunchSecurityAmbush) → TauriCmd.runPanicAttackAmbush")
       ("Added AntiCrash model updates: ValidationPassed adds token, ValidationFailed records violation")
       ("Added SecurityTimelineFileLoaded + SecurityAmbushResult handlers in updatePaneW")
       ("Added eventChain/eventChainSummary/eventChainTimeline to persistedState + Storage")
       ("Added 16 new tests: 5 eventChain persistence + 11 update integration")
       ("Result: 97 JS tests passing (was 81), 0 failures"))))

    ((session-id "2026-02-12-sonnet-polish")
     (date "2026-02-12")
     (agent "Claude Sonnet 4.5")
     (focus "ARIA accessibility, shouldAutoSave, build verification, Eclexia ecosystem")
     (outcomes
       ("Added 7 new ARIA attr helpers to Tea_Vdom: ariaPressed, ariaCurrent, ariaValueNow/Min/Max, ariaDescribedBy")
       ("PaneL: role(listitem) on constraints, ariaPressed+ariaLabel on toggle/pin buttons")
       ("PaneN: ariaCurrent(step) on OODA phases, ariaValueNow/Min/Max on progressbar, role(log) on token stream")
       ("PaneW: ariaLabel on dialog, all 5 form inputs, event chain textarea, shared world textarea")
       ("Vexometer: ariaValueNow/Min/Max on both expanded and compact views, role(meter) on compact")
       ("Added SecurityAmbushResult + SecurityTimelineFileLoaded to shouldAutoSave")
       ("Fixed SPDX header in input.css: AGPL-3.0 → PMPL-1.0-or-later")
       ("Added Eclexia as related project in ECOSYSTEM.scm")
       ("Verified: ReScript build (0 warnings), Tauri cargo build, Tailwind css:build, 97 JS + 12 Rust tests")
       ("Result: 97 JS tests + 12 Rust tests, all 3 build pipelines verified")))

    ((session-id "2026-02-12-opus-audit")
     (date "2026-02-12")
     (agent "Claude Opus 4.6")
     (focus "Honest audit and SONNET-TASKS.md generation")
     (outcomes
       ("Honest completion assessment: 72-80% (not 95-100%)")
       ("Identified 3 backend command stubs in src-tauri/src/main.rs")
       ("Identified 2 unwired core modules: OrbitalSync, Contractiles")
       ("Identified 0 ARIA attributes across all UI components")
       ("Identified Tea_Render doing full re-render instead of VDOM diff")
       ("Created SONNET-TASKS.md with 19 prioritized completion tasks")))
    ((session-id "2026-02-09-codex-1")
     (date "2026-02-09")
     (agent "Codex (GPT-5)")
     (focus "Anti-Crash gating, event-chain import, dev server wiring")
     (outcomes
       ("Wired Anti-Crash token gating into Pane-N ingestion with backend validation")
       ("Added event-chain import from panic-attack (paste + file load)")
       ("Wired feedback report types to backend submission")
       ("Added Tauri dialog/fs plugins and capabilities for file import")
       ("Aligned dev server with Tauri devUrl using serve.sh on :8000"))))
    ((session-id "2026-02-07-claude-1")
     (date "2026-02-07")
     (agent "Claude Sonnet 4.5")
     (focus "RSR compliance, documentation, migration planning")
     (outcomes
       ("✅ Task #4: Reviewed complete codebase structure")
       ("✅ Task #4: Documented architecture (Binary Star, 3-pane layout, TEA, Tauri)")
       ("✅ Task #1: Created .machine_readable/ directory with 6 SCM files (59KB)")
       ("  - STATE.scm (7.3KB) - project state, progress, blockers")
       ("  - META.scm (14KB) - 7 ADRs covering all architecture decisions")
       ("  - ECOSYSTEM.scm (8.1KB) - ecosystem position, dependencies, related projects")
       ("  - AGENTIC.scm (8.5KB) - AI agent interaction patterns, anti-patterns")
       ("  - NEUROSYM.scm (8.2KB) - neurosymbolic integration config, validation")
       ("  - PLAYBOOK.scm (13KB) - operational runbook, troubleshooting")
       ("✅ Task #3: Created NPM-TO-DENO-MIGRATION.md (comprehensive 3-phase plan)")
       ("✅ Task #2: Created RESCRIPT-TEA-MIGRATION-GUIDE.md (6-phase guide)")
       ("✅ Identified rescript-tea NOT installed (migration not started despite checklist)")
       ("✅ Recommended deferring rescript-tea migration to v0.2.0 (low urgency)")
       ("✅ Achieved 100% RSR compliance (AI manifest + SCM files complete)")
       ("Summary: All 4 tasks complete, panll now RSR-compliant")))))

;; Helper functions for state queries

(define (get-completion-percentage state)
  "Returns the current completion percentage for the active milestone"
  (cadr (assoc 'completion-percentage (assoc 'current-position state))))

(define (get-active-blockers state)
  "Returns list of all active blockers"
  (cadr (assoc 'active-blockers (assoc 'blockers-and-issues state))))

(define (get-next-milestone state)
  "Returns the next milestone information"
  (cadr (assoc 'next-milestone (assoc 'route-to-mvp state))))

(define (get-critical-path state)
  "Returns the critical path steps to MVP"
  (cadr (assoc 'critical-path (assoc 'route-to-mvp state))))
