// SPDX-License-Identifier: PMPL-1.0-or-later

/// PanLL CloudGuard Pages Setup — Cloudflare Pages integration panel.
///
/// Provides a workflow for connecting GitHub repositories to Cloudflare Pages
/// projects with automatic SSG framework detection, CNAME record creation,
/// custom domain binding, and security headers setup via `_headers` file.
///
/// Layout:
///   +-----------------------------------------------+
///   | Existing Pages Projects                        |
///   | +-------------------------------------------+  |
///   | | project-name.pages.dev                    |  |
///   | | custom-domain.com (CNAME active)          |  |
///   | | Framework: Jekyll | Branch: main          |  |
///   | +-------------------------------------------+  |
///   |                                               |
///   | [+ New Pages Project]                         |
///   |                                               |
///   | Security Headers Template                     |
///   | [Generate _headers file] [Preview]            |
///   +-----------------------------------------------+

open Msg
open Model
open Tea.Html

// ============================================================================
// Pages project card
// ============================================================================

/// Render a single Pages project card showing project metadata and status.
let renderProjectCard = (project: cfPagesProject): Tea_Vdom.t<msg> => {
  div(
    list{
      Attrs.class_(
        "border border-gray-700 rounded-lg p-3 mb-2 hover:border-gray-600 transition-colors",
      ),
    },
    list{
      // Project header
      div(
        list{Attrs.class_("flex items-center justify-between mb-2")},
        list{
          div(
            list{Attrs.class_("flex items-center gap-2")},
            list{
              span(
                list{Attrs.class_("text-sm font-medium text-gray-200")},
                list{text(project.name)},
              ),
              span(
                list{Attrs.class_("text-xs text-indigo-400 font-mono")},
                list{text(`${project.subdomain}.pages.dev`)},
              ),
            },
          ),
          // Framework badge
          switch project.framework {
          | Some(fw) =>
            span(
              list{
                Attrs.class_(
                  "text-xs text-purple-400 font-medium px-1.5 py-0.5 bg-purple-900/30 rounded",
                ),
              },
              list{text(fw)},
            )
          | None => noNode
          },
        },
      ),
      // Custom domains
      if Array.length(project.customDomains) > 0 {
        div(
          list{Attrs.class_("mb-1.5")},
          list{
            div(list{Attrs.class_("text-xs text-gray-500 mb-0.5")}, list{text("Custom domains:")}),
            div(
              list{Attrs.class_("flex flex-wrap gap-1")},
              project.customDomains
              ->Array.map(domain =>
                span(
                  list{
                    Attrs.class_(
                      "text-xs text-green-400 font-mono px-1.5 py-0.5 bg-green-900/20 rounded",
                    ),
                  },
                  list{text(domain)},
                )
              )
              ->List.fromArray,
            ),
          },
        )
      } else {
        noNode
      },
      // Branch info
      div(
        list{Attrs.class_("text-xs text-gray-500")},
        list{text(`Production branch: ${project.productionBranch}`)},
      ),
    },
  )
}

// ============================================================================
// Security headers template preview
// ============================================================================

/// Generate a `_headers` file content for security hardening.
/// This is a free alternative to Workers for setting security headers on
/// Cloudflare Pages deployments.
let securityHeadersTemplate = (domain: string): string => {
  `/*
  X-Frame-Options: DENY
  X-Content-Type-Options: nosniff
  X-XSS-Protection: 1; mode=block
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()
  Content-Security-Policy: default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self'; connect-src 'self'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'
  Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
  Cross-Origin-Embedder-Policy: require-corp
  Cross-Origin-Opener-Policy: same-origin
  Cross-Origin-Resource-Policy: same-origin

# ${domain} — Generated by CloudGuard
`
}

/// Render the security headers template section.
let renderHeadersTemplate = (currentDomain: option<string>): Tea_Vdom.t<msg> => {
  let domain = switch currentDomain {
  | Some(d) => d
  | None => "example.com"
  }

  div(
    list{Attrs.class_("border border-gray-700 rounded-lg p-3")},
    list{
      div(
        list{Attrs.class_("text-sm text-gray-300 font-medium mb-2")},
        list{text("Security Headers Template (_headers)")},
      ),
      div(
        list{Attrs.class_("text-xs text-gray-500 mb-2")},
        list{
          text(
            "Add this _headers file to your Pages project root for free security headers (no Workers needed).",
          ),
        },
      ),
      // Template preview
      pre(
        list{
          Attrs.class_(
            "text-xs text-gray-400 bg-gray-900 rounded p-2 overflow-x-auto max-h-40 font-mono whitespace-pre",
          ),
        },
        list{text(securityHeadersTemplate(domain))},
      ),
    },
  )
}

// ============================================================================
// Main Pages setup view
// ============================================================================

/// Render the Pages setup panel. Shows existing projects and the security
/// headers template generator.
let view = (
  pagesProjects: array<cfPagesProject>,
  currentDomain: option<string>,
  _loading: bool,
): Tea_Vdom.t<msg> => {
  div(
    list{
      Attrs.class_("flex-1 flex flex-col gap-4"),
      Attrs.role("region"),
      Attrs.ariaLabel("Cloudflare Pages Setup"),
    },
    list{
      // Existing projects section
      div(
        list{},
        list{
          div(
            list{Attrs.class_("text-sm text-gray-400 font-medium mb-2")},
            list{text("Pages Projects")},
          ),
          if Array.length(pagesProjects) > 0 {
            div(
              list{Attrs.class_("space-y-2")},
              pagesProjects
              ->Array.map(renderProjectCard)
              ->List.fromArray,
            )
          } else {
            div(
              list{Attrs.class_("text-xs text-gray-600 italic py-2")},
              list{text("No Pages projects found for this account.")},
            )
          },
        },
      ),
      // Security headers template
      renderHeadersTemplate(currentDomain),
    },
  )
}
