# SPDX-License-Identifier: MPL-2.0
# Panel contract for Fleet — gitbot fleet orchestration and dispatch

panel_id = "Fleet"
module_name = "Fleet"
model_slice = "fleet"
msg_namespace = "fleetMsg"
view_route = "PanelFleet"
short_name = "Fleet"
clade_id = "fleet"
has_backend = true
