# SPDX-License-Identifier: MPL-2.0
# Panel contract for Mass Panic — organisation-scale batch scanning

panel_id = "Mass Panic"
module_name = "MassPanic"
model_slice = "massPanic"
msg_namespace = "massPanicMsg"
view_route = "PanelMassPanic"
short_name = "MP"
clade_id = "mass-panic"
has_backend = true
