// SPDX-License-Identifier: PMPL-1.0-or-later

/// PanLL ENSAID_CONFIG Engine — generates well-annotated .machine_readable/ENSAID_CONFIG.a2ml
/// files from the combined state of Minter, Provisioner, Workspace, and Automation Router.
///
/// The generated file is human-readable and heavily annotated so users can tweak
/// it manually without needing to re-open PanLL. Every section includes comments
/// explaining what each field does, what values are valid, and what the defaults are.
///
/// This is a pure module — no side effects. It builds a string; the Cmd module writes it.

open ProvisionerModel
open WorkspaceModel
open AutomationRouterModel

// ============================================================================
// Helpers
// ============================================================================

/// Render an isolation tier to its ENSAID_CONFIG string value.
let isolationToString = (iso: panelIsolation): string => {
  switch iso {
  | Native => "native"
  | StandardPod => "container"
  | HardenedPod => "vm"
  }
}

/// Render a workspace mode to its ENSAID_CONFIG string value.
let workspaceModeToString = (mode: workspaceMode): string => {
  switch mode {
  | RhodiumMode => "rhodium"
  | EverythingMode => "everything"
  | CodeMode => "code"
  | BespokeMode => "bespoke"
  }
}

/// Render session protection to its ENSAID_CONFIG string value.
let protectionToString = (prot: sessionProtection): string => {
  switch prot {
  | Open => "open"
  | ReadOnly => "readonly"
  | Sandboxed => "sandboxed"
  | LanguageLocked(_) => "language-locked"
  | TranspilationGuarded => "transpilation-guarded"
  | ProductionGated => "production-gated"
  }
}

/// Render execution mode to its ENSAID_CONFIG string value.
let executionModeToString = (mode: executionMode): string => {
  switch mode {
  | Live => "live"
  | DryRun => "dry-run"
  | Simulation => "simulation"
  | Emulation => "emulation"
  }
}

/// Render an approval mode to its ENSAID_CONFIG string value.
let approvalToString = (mode: approvalMode): string => {
  switch mode {
  | AutoFire => "auto-fire"
  | RequireApproval => "require-approval"
  | ApproveOnce => "approve-once"
  | DryRunFirst => "dry-run-first"
  }
}

/// Render a trigger event to a TOML inline table.
let triggerToToml = (trigger: triggerEvent): string => {
  switch trigger {
  | FileChanged(pattern) => `{ event = "file-changed", pattern = "${pattern}" }`
  | PanelMessage(panel, msg) =>
    `{ event = "panel-message", panel = "${panel}", message = "${msg}" }`
  | Timer(seconds) => `{ event = "timer", seconds = ${Int.toString(seconds)} }`
  | Manual => `{ event = "manual" }`
  | PanelStateChange(panel, field) =>
    `{ event = "panel-state-change", panel = "${panel}", field = "${field}" }`
  }
}

/// Extract language-lock extensions if applicable.
let languageLockExtensions = (prot: sessionProtection): option<array<string>> => {
  switch prot {
  | LanguageLocked(exts) => Some(exts)
  | _ => None
  }
}

// ============================================================================
// Section Generators
// ============================================================================

/// Generate the file header with SPDX and explanatory comments.
let generateHeader = (repoName: string): string => {
  `# SPDX-License-Identifier: PMPL-1.0-or-later
#
# ENSAID_CONFIG.a2ml — eNSAID Environment Configuration for ${repoName}
#
# This file configures PanLL (and any eNSAID-compatible tool) for this repository.
# It was generated by PanLL but is designed to be human-editable. Every section
# includes comments explaining what each field does and what values are valid.
#
# Canonical location: .machine_readable/ENSAID_CONFIG.a2ml
# Spec: https://github.com/hyperpolymath/standards/tree/main/ensaid-config
#
# To regenerate this file from PanLL, use any of:
#   - Provisioner panel → Export Config
#   - Workspace panel → Export Config
#   - Automation Router panel → Settings → Save to Repo
#   - Minter panel → after minting a panel, choose "Update ENSAID_CONFIG"
`
}

/// Generate the [ensaid] section.
let generateEnsaidSection = (): string => {
  `
# ─────────────────────────────────────────────────────────────────
# [ensaid] — Core eNSAID identity
#
# version: Spec version this file conforms to (semver).
# tool:    Which eNSAID tool generated this file. Informational only —
#          other tools MUST NOT reject configs with a different tool value.
# ─────────────────────────────────────────────────────────────────
[ensaid]
version = "1.0.0"
tool = "panll"
`
}

/// Generate the [workspace] section from Workspace state.
let generateWorkspaceSection = (ws: workspaceState): string => {
  let modeStr = workspaceModeToString(ws.mode)
  let protStr = protectionToString(ws.protection)
  let execStr = executionModeToString(ws.executionMode)

  let langLock = switch languageLockExtensions(ws.protection) {
  | Some(exts) => {
      let extList = exts->Array.map(e => `"${e}"`)->Array.join(", ")
      `
# Only editable when protection = "language-locked".
# Files with these extensions are immutable; everything else is open.
[workspace.language-lock]
extensions = [${extList}]
`
    }
  | None => ""
  }

  `
# ─────────────────────────────────────────────────────────────────
# [workspace] — Workspace mode, protection, and execution policy
#
# mode: Controls which panels and metadata are visible.
#   "rhodium"    — Full RSR standard compliance view (all governance visible)
#   "everything" — Every panel and tool enabled
#   "code"       — Pure development experience (hides governance panels)
#   "bespoke"    — Per-repo custom panel set (uses [panels] section below)
#
# protection: What operations are permitted in this workspace.
#   "open"                  — No restrictions, full read-write
#   "readonly"              — Browse everything, edit nothing
#   "sandboxed"             — Changes reset when the session ends
#   "language-locked"       — Only files matching language-lock extensions editable
#   "transpilation-guarded" — Saves require equivalence proof
#   "production-gated"      — Changes staged, require explicit sign-off
#
# execution: How commands and builds run.
#   "live"       — Real execution against real data
#   "dry-run"    — Preview changes without applying
#   "simulation" — Run against simulated environment with mock data
#   "emulation"  — Full emulation of target environment locally
# ─────────────────────────────────────────────────────────────────
[workspace]
mode = "${modeStr}"
protection = "${protStr}"
execution = "${execStr}"
` ++
  langLock
}

/// Generate the [preferences] section.
let generatePreferencesSection = (humidity: string, arrangementId: option<string>): string => {
  let arrStr = switch arrangementId {
  | Some(id) => id
  | None => "default-3-panel"
  }

  `
# ─────────────────────────────────────────────────────────────────
# [preferences] — Display and behaviour preferences
#
# humidity: Intensity of the Orbital Drift Aura (ambient background).
#   "high"   — Strong colour wash (immersive)
#   "medium" — Subtle tint (balanced)
#   "low"    — Barely visible (minimal distraction)
#
# default-arrangement: Which panel layout loads by default.
#   Built-in options: "default-3-panel", "ai-focus", "debug-layout", "teaching-mode"
#   Or any custom arrangement ID you've saved.
#
# auto-connect: Whether panels auto-connect to their backends on load.
#   true  — Panels connect immediately (faster startup)
#   false — Panels wait for manual connection (more control)
# ─────────────────────────────────────────────────────────────────
[preferences]
humidity = "${humidity}"
default-arrangement = "${arrStr}"
auto-connect = true
`
}

/// Generate the [panels] section from Provisioner panel configs.
let generatePanelsSection = (configs: array<panelConfig>): string => {
  let enabledPanels = configs->Array.filter(c => c.enabled)
  let disabledPanels = configs->Array.filter(c => !c.enabled)

  let enabledEntries =
    enabledPanels
    ->Array.map(c => {
      let isoStr = isolationToString(c.isolation)
      let endpointLine = if c.endpoint !== "" {
        `\nendpoint = "${c.endpoint}"`
      } else {
        ""
      }
      let autoLine = if !c.autoConnect {
        "\nauto-connect = false"
      } else {
        "\nauto-connect = true"
      }
      let envLines = if c.envVars->Array.length > 0 {
        let pairs = c.envVars->Array.map(((k, v)) => `${k} = "${v}"`)->Array.join(", ")
        `\nenv = { ${pairs} }`
      } else {
        ""
      }
      `
[[panels.enabled]]
id = "${c.panelName}"
isolation = "${isoStr}"${autoLine}${endpointLine}${envLines}
`
    })
    ->Array.join("")

  let disabledSection = if disabledPanels->Array.length > 0 {
    let ids = disabledPanels->Array.map(c => `"${c.panelName}"`)->Array.join(", ")
    `
# Panels hidden for this repo context. Users can still enable them
# manually through the PanLL UI if the tool supports it.
[panels.disabled]
ids = [${ids}]
`
  } else {
    `
# No panels explicitly disabled. Uncomment to hide panels:
# [panels.disabled]
# ids = ["cloudguard", "aerie"]
`
  }

  `
# ─────────────────────────────────────────────────────────────────
# [panels] — Panel visibility, enablement, and configuration
#
# Each [[panels.enabled]] entry declares a panel that should be active.
# If this section is empty or absent, ALL panels are available (tool default).
#
# Fields per panel:
#   id:           Panel identifier (matches PanLL's panel registry)
#   isolation:    "native" (in-process), "container" (Podman), "vm" (Stapeln hardened)
#   auto-connect: Whether this panel connects to its backend on load
#   endpoint:     Backend URL (only for panels with external services)
#   env:          Environment variables scoped to this panel's processes
# ─────────────────────────────────────────────────────────────────
[panels]
version = "1.0.0"
` ++
  enabledEntries ++
  disabledSection
}

/// Generate the [workflows] section from Automation Router rules.
let generateWorkflowsSection = (rules: array<automationRule>): string => {
  let ruleEntries = if rules->Array.length > 0 {
    rules
    ->Array.map(rule => {
      let triggerStr = triggerToToml(rule.trigger)
      let approvalStr = approvalToString(rule.approval)
      let enabledStr = if !rule.enabled {
        "\nenabled = false"
      } else {
        ""
      }
      let condLines =
        rule.conditions
        ->Array.map(cond => {
          `condition = { panel = "${cond.panelId}", field = "${cond.field}", operator = "${cond.operator}", value = "${cond.value}" }`
        })
        ->Array.join("\n")
      let condSection = if condLines !== "" {
        "\n" ++ condLines
      } else {
        ""
      }
      let actionLines =
        rule.actions
        ->Array.map(act => {
          let argsStr = if act.args->Array.length > 0 {
            let pairs = act.args->Array.map(((k, v)) => `${k} = "${v}"`)->Array.join(", ")
            `, args = { ${pairs} }`
          } else {
            ""
          }
          `action = { panel = "${act.panelId}", message = "${act.message}"${argsStr} }`
        })
        ->Array.join("\n")

      `
# ${rule.description}
[[workflows.rule]]
name = "${rule.name}"
trigger = ${triggerStr}${condSection}
${actionLines}
approval = "${approvalStr}"${enabledStr}
`
    })
    ->Array.join("")
  } else {
    `
# No automation rules defined yet. Here's an example to get started:
#
# [[workflows.rule]]
# name = "build-on-save"
# trigger = { event = "file-changed", pattern = "src/**/*.res" }
# condition = { panel = "build-dashboard", field = "watchMode", equals = true }
# action = { panel = "build-dashboard", message = "TriggerBuild", args = { target = "game" } }
# approval = "auto-fire"
`
  }

  `
# ─────────────────────────────────────────────────────────────────
# [workflows] — Automation Router event-driven cross-panel rules
#
# Rules fire when a trigger event occurs. Each rule has:
#   name:      Human-readable identifier (must be unique)
#   trigger:   What event activates this rule
#   condition: (optional) Additional check before the action fires
#   action:    What to do — sends a message to a panel
#   approval:  How the action is gated:
#     "auto-fire"        — Runs immediately, no confirmation
#     "require-approval" — Queues in Pending tab, waits for user approval
#     "approve-once"     — Asks once, then auto-fires for identical triggers
#     "dry-run-first"    — Shows what would happen, then asks to confirm
#   enabled:   (optional) Set to false to disable without deleting
#
# Trigger types:
#   file-changed:       A file matching 'pattern' (glob) was saved
#   panel-message:      A panel emitted a specific message
#   timer:              Fires every N seconds
#   manual:             Only fires when explicitly triggered by user
#   panel-state-change: A panel's state field changed value
# ─────────────────────────────────────────────────────────────────
[workflows]
version = "1.0.0"
` ++
  ruleEntries
}

/// Generate the [clades] section (placeholder — clade overrides are per-repo).
let generateCladesSection = (): string => {
  `
# ─────────────────────────────────────────────────────────────────
# [clades] — Panel clade trait and capability overrides
#
# Clades are the taxonomic categories of panels (ai, bridge, builder,
# database, directive, loader, meta, network, scanner, terminal, viewer).
# Override traits and capabilities here for this repo context only —
# the global clade registry is not modified.
#
# Fields per override:
#   id:                  Clade identifier to customise
#   traits:              Key-value pairs to set or override (booleans/strings)
#   capabilities-add:    Capabilities to add for this repo
#   capabilities-remove: Capabilities to remove for this repo
# ─────────────────────────────────────────────────────────────────
[clades]
version = "1.0.0"

# Example: give the build dashboard a work-items trait for this repo
# [[clades.override]]
# id = "build-dashboard"
# traits = { has-work-items = true }
# capabilities-add = ["CustomCheck"]
`
}

/// Generate the [portfolios] section from Provisioner portfolios.
let generatePortfoliosSection = (portfolios: array<portfolio>): string => {
  let customPortfolios = portfolios->Array.filter(p => !p.builtIn)

  let portfolioEntries = if customPortfolios->Array.length > 0 {
    customPortfolios
    ->Array.map(p => {
      let panelList = p.panels->Array.map(id => `"${id}"`)->Array.join(", ")
      let isoStr = isolationToString(p.defaultIsolation)
      `
# ${p.description}
[[portfolios.custom]]
id = "${p.id}"
name = "${p.name}"
description = "${p.description}"
panels = [${panelList}]
default-isolation = "${isoStr}"
`
    })
    ->Array.join("")
  } else {
    `
# No custom portfolios defined yet. Here's an example:
#
# [[portfolios.custom]]
# id = "my-project-dev"
# name = "My Project Development"
# description = "Panels tailored to this project's workflow"
# panels = ["valence-shell", "editor-bridge", "build-dashboard"]
# default-isolation = "native"
`
  }

  `
# ─────────────────────────────────────────────────────────────────
# [portfolios] — Custom panel bundles for this repo's workflow
#
# A portfolio is a named collection of panels that form a workspace
# configuration. Define portfolios here to give collaborators a
# one-click setup for common workflows.
#
# Fields:
#   id:                Unique identifier (kebab-case)
#   name:              Human-readable name
#   description:       What this portfolio is for
#   panels:            Ordered list of panel IDs to include
#   default-isolation: Default isolation tier for panels in this bundle
#                      ("native", "container", "vm")
#                      Panels with explicit isolation in [panels] override this.
# ─────────────────────────────────────────────────────────────────
[portfolios]
version = "1.0.0"
` ++
  portfolioEntries
}

// ============================================================================
// Main Generator
// ============================================================================

/// Generate a complete, well-annotated ENSAID_CONFIG.a2ml from PanLL state.
///
/// This is the primary entry point. Each panel calls this with whatever state
/// it has access to. Missing state uses sensible defaults.
let generate = (
  ~repoName: string,
  ~workspace: option<workspaceState>=?,
  ~humidity: string="medium",
  ~panelConfigs: array<panelConfig>=[],
  ~portfolios: array<portfolio>=[],
  ~automationRules: array<automationRule>=[],
  (),
): string => {
  let ws = switch workspace {
  | Some(w) => w
  | None => {
      mode: RhodiumMode,
      protection: Open,
      executionMode: Live,
      groups: [],
      arrangements: [],
      activeArrangementId: None,
      sessions: [],
      activeSessionId: None,
      polyTools: [],
      configuratorOpen: false,
      configuratorTab: TabArrangements,
      viewingMetadata: None,
      metadataContent: None,
    }
  }

  let arrangementId = ws.activeArrangementId

  generateHeader(repoName) ++
  generateEnsaidSection() ++
  generateWorkspaceSection(ws) ++
  generatePreferencesSection(humidity, arrangementId) ++
  generatePanelsSection(panelConfigs) ++
  generateWorkflowsSection(automationRules) ++
  generateCladesSection() ++
  generatePortfoliosSection(portfolios)
}
