// SPDX-License-Identifier: PMPL-1.0-or-later

/// PanLL ProvenanceEngine — Pure computation for the Code Provenance Map.
///
/// Derives trust levels from git blame data, computes summaries, manages
/// the accessibility palette colour mappings, and determines when hostile
/// UX should activate. All functions are pure — no side effects.
///
/// DESIGN NOTE: The trust colour mapping below covers 4 palettes × 5 trust
/// levels = 20 colour combinations, all expressed as a pure function from
/// `(trustLevel, accessibilityPalette) => (bgClass, textClass, borderClass)`.
/// In a dynamically typed language, this would be a nested dictionary lookup
/// with runtime KeyError risk. Here, the compiler proves exhaustiveness: every
/// palette/level combination has a defined mapping, and adding a new trust level
/// forces you to define its colours for ALL four palettes before the code
/// compiles. This matters because accessibility palette bugs are invisible to
/// most developers — they only surface for users who need them most.

open ProvenanceModel

/// Derive the trust level for a blame region based on author and co-author data.
///
/// Rules (in priority order):
///   1. If the commit has proof metadata (verified flag), trust = Verified
///   2. If no co-author and author is human, trust = HumanReviewed
///   3. If co-authored (human + AI) with subsequent human commit, trust = HumanReviewed
///   4. If co-authored (human + AI) without subsequent review, trust = AiAssisted
///   5. If author matches known AI patterns and no human in chain, trust = UnreviewedAi
///   6. Otherwise, trust = Unknown
let deriveTrustLevel = (
  author: string,
  coAuthored: bool,
  coAuthor: option<string>,
  hasSubsequentHumanCommit: bool,
): trustLevel => {
  // Known AI co-author patterns (Claude, Copilot, etc.)
  let isAiCoAuthor = switch coAuthor {
  | Some(name) =>
    String.includes(name, "Claude") ||
    String.includes(name, "Copilot") ||
    String.includes(name, "noreply@anthropic.com") ||
    String.includes(name, "noreply@github.com") ||
    String.includes(name, "GPT") ||
    String.includes(name, "Gemini")
  | None => false
  }

  // Known AI-only author patterns (bot accounts).
  let isAiAuthor =
    String.includes(author, "bot") ||
    String.includes(author, "Bot") ||
    String.includes(author, "copilot") ||
    String.includes(author, "dependabot") ||
    author === "test@example.com" ||
    author === "you@example.com"

  if coAuthored && isAiCoAuthor {
    if hasSubsequentHumanCommit {
      HumanReviewed
    } else {
      AiAssisted
    }
  } else if isAiAuthor {
    UnreviewedAi
  } else if author !== "" {
    HumanReviewed
  } else {
    Unknown
  }
}

/// Compute summary statistics from an array of provenance regions.
let computeSummary = (regions: array<provenanceRegion>): provenanceSummary => {
  let totalLines = regions->Array.reduce(0, (acc, r) => acc + (r.endLine - r.startLine + 1))
  let countLines = (level: trustLevel) =>
    regions
    ->Array.filter(r => r.trustLevel === level)
    ->Array.reduce(0, (acc, r) => acc + (r.endLine - r.startLine + 1))

  let authors =
    regions
    ->Array.map(r => r.author)
    ->Array.reduce([], (acc, a) =>
      if acc->Array.some(x => x === a) {
        acc
      } else {
        Array.concat(acc, [a])
      }
    )

  let coAuthors =
    regions
    ->Array.filterMap(r => r.coAuthor)
    ->Array.reduce([], (acc, a) =>
      if acc->Array.some(x => x === a) {
        acc
      } else {
        Array.concat(acc, [a])
      }
    )

  {
    totalLines,
    verifiedLines: countLines(Verified),
    humanReviewedLines: countLines(HumanReviewed),
    aiAssistedLines: countLines(AiAssisted),
    unreviewedAiLines: countLines(UnreviewedAi),
    unknownLines: countLines(Unknown),
    authorCount: Array.length(authors),
    coAuthorCount: Array.length(coAuthors),
    hasViolations: regions->Array.some(r => r.trustLevel === UnreviewedAi),
    unsoundMarkers: 0, // Populated by separate believe_me scan
  }
}

/// Trust level display label — used in UI and screen readers.
/// These are the CANONICAL names, not configurable.
let trustLabel = (level: trustLevel): string => {
  switch level {
  | Verified => "Formally Verified"
  | HumanReviewed => "Human Reviewed"
  | AiAssisted => "AI Assisted"
  | UnreviewedAi => "Unreviewed AI"
  | Unknown => "Unknown Provenance"
  }
}

/// Short label for compact displays.
let trustShortLabel = (level: trustLevel): string => {
  switch level {
  | Verified => "Verified"
  | HumanReviewed => "Human"
  | AiAssisted => "AI+Human"
  | UnreviewedAi => "AI Only"
  | Unknown => "Unknown"
  }
}

/// ARIA label for screen reader announcement.
let trustAriaLabel = (level: trustLevel): string => {
  switch level {
  | Verified => "Code formally verified with proof checker"
  | HumanReviewed => "Code written or reviewed by a human"
  | AiAssisted => "Code co-authored with AI, not yet reviewed"
  | UnreviewedAi => "WARNING: Code generated by AI with no human review"
  | Unknown => "Code provenance unknown"
  }
}

/// Shape indicator for each trust level — redundant channel beyond colour.
/// Used as CSS class suffixes for icon rendering.
let trustShape = (level: trustLevel): string => {
  switch level {
  | Verified => "shield-check"   // Shield with checkmark
  | HumanReviewed => "user-check" // Person with checkmark
  | AiAssisted => "cpu"           // Circuit/chip icon
  | UnreviewedAi => "alert-triangle" // Warning triangle
  | Unknown => "help-circle"      // Question mark circle
  }
}

/// Get the CSS colour classes for a trust level under the given palette.
///
/// Returns (bgClass, textClass, borderClass) triple. The semantic POSITION
/// is fixed; only the specific hues change per palette.
let trustColours = (
  level: trustLevel,
  palette: accessibilityPalette,
): (string, string, string) => {
  switch (level, palette) {
  // Standard palette
  | (Verified, StandardPalette) => ("bg-green-900/30", "text-green-400", "border-green-600")
  | (HumanReviewed, StandardPalette) => ("bg-blue-900/30", "text-blue-400", "border-blue-600")
  | (AiAssisted, StandardPalette) => ("bg-amber-900/30", "text-amber-400", "border-amber-600")
  | (UnreviewedAi, StandardPalette) => ("bg-red-900/30", "text-red-400", "border-red-600")
  | (Unknown, StandardPalette) => ("bg-gray-900/30", "text-gray-400", "border-gray-600")

  // Deuteranopia-safe palette (green → teal, red → magenta)
  | (Verified, DeuteranopiaPalette) => ("bg-teal-900/30", "text-teal-400", "border-teal-600")
  | (HumanReviewed, DeuteranopiaPalette) => ("bg-blue-900/30", "text-blue-400", "border-blue-600")
  | (AiAssisted, DeuteranopiaPalette) => ("bg-yellow-900/30", "text-yellow-400", "border-yellow-600")
  | (UnreviewedAi, DeuteranopiaPalette) => ("bg-fuchsia-900/30", "text-fuchsia-400", "border-fuchsia-600")
  | (Unknown, DeuteranopiaPalette) => ("bg-gray-900/30", "text-gray-400", "border-gray-600")

  // Protanopia-safe palette (green → cyan, red → magenta)
  | (Verified, ProtanopiaPalette) => ("bg-cyan-900/30", "text-cyan-400", "border-cyan-600")
  | (HumanReviewed, ProtanopiaPalette) => ("bg-blue-900/30", "text-blue-400", "border-blue-600")
  | (AiAssisted, ProtanopiaPalette) => ("bg-orange-900/30", "text-orange-400", "border-orange-600")
  | (UnreviewedAi, ProtanopiaPalette) => ("bg-fuchsia-900/30", "text-fuchsia-400", "border-fuchsia-600")
  | (Unknown, ProtanopiaPalette) => ("bg-gray-900/30", "text-gray-400", "border-gray-600")

  // High-contrast palette
  | (Verified, HighContrastPalette) => ("bg-green-800", "text-white", "border-green-400")
  | (HumanReviewed, HighContrastPalette) => ("bg-blue-800", "text-white", "border-blue-400")
  | (AiAssisted, HighContrastPalette) => ("bg-yellow-600", "text-black", "border-yellow-400")
  | (UnreviewedAi, HighContrastPalette) => ("bg-red-800", "text-white", "border-red-400")
  | (Unknown, HighContrastPalette) => ("bg-gray-700", "text-gray-200", "border-gray-400")
  }
}

/// Whether a trust level should trigger hostile UX (pulsing, alarming visuals).
let isHostile = (level: trustLevel): bool => {
  level === UnreviewedAi
}

/// CSS classes for hostile UX animation on unreviewed AI regions.
/// Returns empty string for non-hostile trust levels.
let hostileClasses = (level: trustLevel, suppressed: bool): string => {
  if isHostile(level) && !suppressed {
    "animate-pulse border-2 border-red-500 ring-2 ring-red-500/50"
  } else {
    ""
  }
}

/// Compute the trust percentage (verified + human-reviewed) for a file.
/// This is the "trust score" shown in the provenance summary bar.
let trustPercentage = (summary: provenanceSummary): float => {
  if summary.totalLines === 0 {
    0.0
  } else {
    let trusted = Float.fromInt(summary.verifiedLines + summary.humanReviewedLines)
    trusted /. Float.fromInt(summary.totalLines) *. 100.0
  }
}

/// Default provenance state — enabled with standard palette.
let defaultState: provenanceState = {
  enabled: true,
  activeFile: None,
  cache: [],
  palette: StandardPalette,
  hostileUxActive: false,
  hostileUxSuppressed: false,
  loading: false,
  error: None,
}

/// Build a simple provenance DAG from a set of file provenances.
/// Each file becomes a SourceNode, and files that import from each other
/// get edges. This is the naive version — the real one would parse imports.
let buildDag = (files: array<fileProvenance>): provenanceDag => {
  let nodes = files->Array.map(fp => {
    let trust = if fp.summary.verifiedLines > fp.summary.totalLines / 2 {
      Verified
    } else if fp.summary.humanReviewedLines > fp.summary.totalLines / 2 {
      HumanReviewed
    } else if fp.summary.aiAssistedLines > fp.summary.totalLines / 2 {
      AiAssisted
    } else if fp.summary.unreviewedAiLines > 0 {
      UnreviewedAi
    } else {
      Unknown
    }
    {
      id: fp.filePath,
      label: fp.filePath,
      kind: SourceNode,
      trustLevel: trust,
      contentHash: "",
      createdAt: fp.analysedAt,
      verified: fp.summary.unsoundMarkers === 0 && trust === Verified,
    }
  })
  {
    nodes,
    edges: [],
    roots: nodes->Array.map(n => n.id),
    leaves: nodes->Array.map(n => n.id),
    computedAt: Date.now(),
  }
}

/// Find all transitive dependencies (ancestors) of a node in the DAG.
let ancestors = (dag: provenanceDag, nodeId: string): array<string> => {
  let rec walk = (current: string, visited: array<string>): array<string> => {
    if visited->Array.some(v => v === current) {
      visited
    } else {
      let visited = Array.concat(visited, [current])
      dag.edges
      ->Array.filter(e => e.toId === current)
      ->Array.reduce(visited, (acc, e) => walk(e.fromId, acc))
    }
  }
  walk(nodeId, [])->Array.filter(id => id !== nodeId)
}

/// Find all transitive dependents (descendants) of a node in the DAG.
let descendants = (dag: provenanceDag, nodeId: string): array<string> => {
  let rec walk = (current: string, visited: array<string>): array<string> => {
    if visited->Array.some(v => v === current) {
      visited
    } else {
      let visited = Array.concat(visited, [current])
      dag.edges
      ->Array.filter(e => e.fromId === current)
      ->Array.reduce(visited, (acc, e) => walk(e.toId, acc))
    }
  }
  walk(nodeId, [])->Array.filter(id => id !== nodeId)
}

/// Compute the "blast radius" — if a node's trust is compromised, how many
/// downstream nodes are affected? Returns (directCount, transitiveCount).
let blastRadius = (dag: provenanceDag, nodeId: string): (int, int) => {
  let direct = dag.edges->Array.filter(e => e.fromId === nodeId)->Array.length
  let transitive = descendants(dag, nodeId)->Array.length
  (direct, transitive)
}

/// Label for a DAG node kind.
let dagNodeKindLabel = (kind: dagNodeKind): string => {
  switch kind {
  | SourceNode => "Source"
  | BuildNode => "Build"
  | DependencyNode => "Dependency"
  | ProofNode => "Proof"
  | AttestationNode => "Attestation"
  }
}

/// CSS colour class for a DAG node kind.
let dagNodeKindColour = (kind: dagNodeKind): string => {
  switch kind {
  | SourceNode => "text-blue-400"
  | BuildNode => "text-amber-400"
  | DependencyNode => "text-purple-400"
  | ProofNode => "text-green-400"
  | AttestationNode => "text-cyan-400"
  }
}

// ===========================================================================
// Code MRI Layer 1 — Blake3 Provenance Chain
//
// Tamper-evident hash chain for code regions. Each entry's hash is computed
// from (content, author, timestamp, parentHash), forming a linked chain
// where modifying any field invalidates everything downstream.
//
// IMPLEMENTATION NOTE: ReScript cannot call Blake3 directly, so we use a
// deterministic hex-encoded hash built from character code accumulation with
// prime mixing. This gives collision resistance suitable for integrity
// checking (not cryptographic security). A future FFI binding to a real
// Blake3 library can replace `computeRegionHash` without changing the chain
// structure.
// ===========================================================================

/// Compute a deterministic hex-encoded hash from a code region's fields.
///
/// Concatenates (content, author, timestamp, parentHash) with a separator,
/// then applies a prime-mixing accumulator over each character code to
/// produce a 16-character hex digest. This is NOT cryptographically secure —
/// it is a structural integrity check. Replace with Blake3 FFI when available.
///
/// @param content    The source code text of the region
/// @param author     The commit author (name or email)
/// @param timestamp  ISO 8601 timestamp string
/// @param parentHash Hash of the previous chain entry ("0" for genesis)
/// @returns 16-character hex string
let computeRegionHash = (
  content: string,
  author: string,
  timestamp: string,
  parentHash: string,
): string => {
  // Concatenate all fields with a pipe separator to avoid ambiguity
  let input = content ++ "|" ++ author ++ "|" ++ timestamp ++ "|" ++ parentHash
  // Prime-mixing accumulator: fold over character codes with two accumulators
  // Use raw JS for bitwise hash — ReScript lacks bitwise operators.
  let hash: string = %raw(`
    (function(input) {
      var len = input.length;
      var hashA = 0x811c9dc5;
      var hashB = 0x01000193;
      for (var i = 0; i < len; i++) {
        var c = input.charCodeAt(i);
        hashA = (hashA * 16777619 ^ c) >>> 0;
        hashB = (hashB * 16777259 ^ (c + i)) >>> 0;
      }
      var hex = "";
      var vals = [hashA, hashB];
      for (var j = 0; j < 2; j++) {
        var n = vals[j];
        for (var k = 7; k >= 0; k--) {
          hex += "0123456789abcdef"[(n >> (k * 4)) & 15];
        }
      }
      return hex;
    })(input)
  `)
  hash
}

/// Create a new provenance chain entry with a computed hash.
///
/// The hash is derived from the content, author, timestamp, and parent hash,
/// ensuring the chain is tamper-evident. The attribution field defaults to
/// "human" — callers should set it explicitly for AI-generated code.
///
/// @param content    The source code region
/// @param author     Who committed this region
/// @param timestamp  When it was committed (ISO 8601)
/// @param parentHash Hash of the previous entry ("0" for the first entry)
/// @returns A fully populated chain entry with computed hash
let createChainEntry = (
  content: string,
  author: string,
  timestamp: string,
  parentHash: string,
): provenanceChainEntry => {
  let hash = computeRegionHash(content, author, timestamp, parentHash)
  {
    hash,
    parentHash,
    content,
    author,
    timestamp,
    attribution: "human",
  }
}

/// Verify that a provenance chain is internally consistent.
///
/// Walks the chain from index 1 onward, checking that each entry's
/// `parentHash` matches the previous entry's `hash`. Also verifies that
/// each entry's `hash` field matches the recomputed hash from its fields.
///
/// An empty chain or single-entry chain is considered valid.
///
/// @param entries The provenance chain to verify (ordered oldest-first)
/// @returns true if the entire chain is consistent, false if any link is broken
let verifyChain = (entries: array<provenanceChainEntry>): bool => {
  let len = Array.length(entries)
  if len <= 1 {
    true
  } else {
    let valid = ref(true)
    for i in 0 to len - 1 {
      let entry = entries->Array.getUnsafe(i)
      // Verify the hash field matches recomputation
      let recomputed = computeRegionHash(
        entry.content,
        entry.author,
        entry.timestamp,
        entry.parentHash,
      )
      if recomputed !== entry.hash {
        valid := false
      }
      // Verify parent linkage (skip index 0 — genesis entry)
      if i > 0 {
        let prev = entries->Array.getUnsafe(i - 1)
        if entry.parentHash !== prev.hash {
          valid := false
        }
      }
    }
    valid.contents
  }
}

/// Serialize a provenance chain to JSON for .mri.json sidecar files.
///
/// Produces a JSON array where each element is an object with fields:
/// hash, parentHash, content, author, timestamp, attribution.
/// The output is deterministic (same chain always produces same JSON).
///
/// @param entries The provenance chain to serialize
/// @returns A JSON string representation of the chain
let chainToJson = (entries: array<provenanceChainEntry>): string => {
  // Escape double quotes and backslashes in a string for JSON embedding.
  let escapeJson = (s: string): string => {
    let result = ref("")
    let len = String.length(s)
    for i in 0 to len - 1 {
      let ch = String.charAt(s, i)
      if ch === "\"" {
        result := result.contents ++ "\\\""
      } else if ch === "\\" {
        result := result.contents ++ "\\\\"
      } else if ch === "\n" {
        result := result.contents ++ "\\n"
      } else if ch === "\r" {
        result := result.contents ++ "\\r"
      } else if ch === "\t" {
        result := result.contents ++ "\\t"
      } else {
        result := result.contents ++ ch
      }
    }
    result.contents
  }
  let items = entries->Array.map(entry => {
    "{" ++
    "\"hash\":\"" ++ escapeJson(entry.hash) ++ "\"," ++
    "\"parentHash\":\"" ++ escapeJson(entry.parentHash) ++ "\"," ++
    "\"content\":\"" ++ escapeJson(entry.content) ++ "\"," ++
    "\"author\":\"" ++ escapeJson(entry.author) ++ "\"," ++
    "\"timestamp\":\"" ++ escapeJson(entry.timestamp) ++ "\"," ++
    "\"attribution\":\"" ++ escapeJson(entry.attribution) ++ "\"" ++
    "}"
  })
  "[" ++ Array.join(items, ",") ++ "]"
}

/// Detect tampered entries in a provenance chain.
///
/// Returns the indices of entries whose hash does not match recomputation
/// from their fields, OR whose parentHash does not match the previous
/// entry's hash. Index 0 is only flagged if its own hash is inconsistent
/// (it has no parent to check against).
///
/// @param entries The provenance chain to audit
/// @returns Array of 0-based indices where tampering was detected
let detectTampering = (entries: array<provenanceChainEntry>): array<int> => {
  let len = Array.length(entries)
  let tampered = ref([])
  for i in 0 to len - 1 {
    let entry = entries->Array.getUnsafe(i)
    let recomputed = computeRegionHash(
      entry.content,
      entry.author,
      entry.timestamp,
      entry.parentHash,
    )
    let hashMismatch = recomputed !== entry.hash
    let parentMismatch = if i > 0 {
      let prev = entries->Array.getUnsafe(i - 1)
      entry.parentHash !== prev.hash
    } else {
      false
    }
    if hashMismatch || parentMismatch {
      tampered := Array.concat(tampered.contents, [i])
    }
  }
  tampered.contents
}
