// SPDX-License-Identifier: PMPL-1.0-or-later

/// PanLL ProvenanceEngine — Pure computation for the Code Provenance Map.
///
/// Derives trust levels from git blame data, computes summaries, manages
/// the accessibility palette colour mappings, and determines when hostile
/// UX should activate. All functions are pure — no side effects.
///
/// DESIGN NOTE: The trust colour mapping below covers 4 palettes × 5 trust
/// levels = 20 colour combinations, all expressed as a pure function from
/// `(trustLevel, accessibilityPalette) => (bgClass, textClass, borderClass)`.
/// In a dynamically typed language, this would be a nested dictionary lookup
/// with runtime KeyError risk. Here, the compiler proves exhaustiveness: every
/// palette/level combination has a defined mapping, and adding a new trust level
/// forces you to define its colours for ALL four palettes before the code
/// compiles. This matters because accessibility palette bugs are invisible to
/// most developers — they only surface for users who need them most.

open ProvenanceModel

/// Derive the trust level for a blame region based on author and co-author data.
///
/// Rules (in priority order):
///   1. If the commit has proof metadata (verified flag), trust = Verified
///   2. If no co-author and author is human, trust = HumanReviewed
///   3. If co-authored (human + AI) with subsequent human commit, trust = HumanReviewed
///   4. If co-authored (human + AI) without subsequent review, trust = AiAssisted
///   5. If author matches known AI patterns and no human in chain, trust = UnreviewedAi
///   6. Otherwise, trust = Unknown
let deriveTrustLevel = (
  author: string,
  coAuthored: bool,
  coAuthor: option<string>,
  hasSubsequentHumanCommit: bool,
): trustLevel => {
  // Known AI co-author patterns (Claude, Copilot, etc.)
  let isAiCoAuthor = switch coAuthor {
  | Some(name) =>
    String.includes(name, "Claude") ||
    String.includes(name, "Copilot") ||
    String.includes(name, "noreply@anthropic.com") ||
    String.includes(name, "noreply@github.com") ||
    String.includes(name, "GPT") ||
    String.includes(name, "Gemini")
  | None => false
  }

  // Known AI-only author patterns (bot accounts).
  let isAiAuthor =
    String.includes(author, "bot") ||
    String.includes(author, "Bot") ||
    String.includes(author, "copilot") ||
    String.includes(author, "dependabot") ||
    author === "test@example.com" ||
    author === "you@example.com"

  if coAuthored && isAiCoAuthor {
    if hasSubsequentHumanCommit {
      HumanReviewed
    } else {
      AiAssisted
    }
  } else if isAiAuthor {
    UnreviewedAi
  } else if author !== "" {
    HumanReviewed
  } else {
    Unknown
  }
}

/// Compute summary statistics from an array of provenance regions.
let computeSummary = (regions: array<provenanceRegion>): provenanceSummary => {
  let totalLines = regions->Array.reduce(0, (acc, r) => acc + (r.endLine - r.startLine + 1))
  let countLines = (level: trustLevel) =>
    regions
    ->Array.filter(r => r.trustLevel === level)
    ->Array.reduce(0, (acc, r) => acc + (r.endLine - r.startLine + 1))

  let authors =
    regions
    ->Array.map(r => r.author)
    ->Array.reduce([], (acc, a) =>
      if acc->Array.some(x => x === a) {
        acc
      } else {
        Array.concat(acc, [a])
      }
    )

  let coAuthors =
    regions
    ->Array.filterMap(r => r.coAuthor)
    ->Array.reduce([], (acc, a) =>
      if acc->Array.some(x => x === a) {
        acc
      } else {
        Array.concat(acc, [a])
      }
    )

  {
    totalLines,
    verifiedLines: countLines(Verified),
    humanReviewedLines: countLines(HumanReviewed),
    aiAssistedLines: countLines(AiAssisted),
    unreviewedAiLines: countLines(UnreviewedAi),
    unknownLines: countLines(Unknown),
    authorCount: Array.length(authors),
    coAuthorCount: Array.length(coAuthors),
    hasViolations: regions->Array.some(r => r.trustLevel === UnreviewedAi),
    unsoundMarkers: 0, // Populated by separate believe_me scan
  }
}

/// Trust level display label — used in UI and screen readers.
/// These are the CANONICAL names, not configurable.
let trustLabel = (level: trustLevel): string => {
  switch level {
  | Verified => "Formally Verified"
  | HumanReviewed => "Human Reviewed"
  | AiAssisted => "AI Assisted"
  | UnreviewedAi => "Unreviewed AI"
  | Unknown => "Unknown Provenance"
  }
}

/// Short label for compact displays.
let trustShortLabel = (level: trustLevel): string => {
  switch level {
  | Verified => "Verified"
  | HumanReviewed => "Human"
  | AiAssisted => "AI+Human"
  | UnreviewedAi => "AI Only"
  | Unknown => "Unknown"
  }
}

/// ARIA label for screen reader announcement.
let trustAriaLabel = (level: trustLevel): string => {
  switch level {
  | Verified => "Code formally verified with proof checker"
  | HumanReviewed => "Code written or reviewed by a human"
  | AiAssisted => "Code co-authored with AI, not yet reviewed"
  | UnreviewedAi => "WARNING: Code generated by AI with no human review"
  | Unknown => "Code provenance unknown"
  }
}

/// Shape indicator for each trust level — redundant channel beyond colour.
/// Used as CSS class suffixes for icon rendering.
let trustShape = (level: trustLevel): string => {
  switch level {
  | Verified => "shield-check"   // Shield with checkmark
  | HumanReviewed => "user-check" // Person with checkmark
  | AiAssisted => "cpu"           // Circuit/chip icon
  | UnreviewedAi => "alert-triangle" // Warning triangle
  | Unknown => "help-circle"      // Question mark circle
  }
}

/// Get the CSS colour classes for a trust level under the given palette.
///
/// Returns (bgClass, textClass, borderClass) triple. The semantic POSITION
/// is fixed; only the specific hues change per palette.
let trustColours = (
  level: trustLevel,
  palette: accessibilityPalette,
): (string, string, string) => {
  switch (level, palette) {
  // Standard palette
  | (Verified, StandardPalette) => ("bg-green-900/30", "text-green-400", "border-green-600")
  | (HumanReviewed, StandardPalette) => ("bg-blue-900/30", "text-blue-400", "border-blue-600")
  | (AiAssisted, StandardPalette) => ("bg-amber-900/30", "text-amber-400", "border-amber-600")
  | (UnreviewedAi, StandardPalette) => ("bg-red-900/30", "text-red-400", "border-red-600")
  | (Unknown, StandardPalette) => ("bg-gray-900/30", "text-gray-400", "border-gray-600")

  // Deuteranopia-safe palette (green → teal, red → magenta)
  | (Verified, DeuteranopiaPalette) => ("bg-teal-900/30", "text-teal-400", "border-teal-600")
  | (HumanReviewed, DeuteranopiaPalette) => ("bg-blue-900/30", "text-blue-400", "border-blue-600")
  | (AiAssisted, DeuteranopiaPalette) => ("bg-yellow-900/30", "text-yellow-400", "border-yellow-600")
  | (UnreviewedAi, DeuteranopiaPalette) => ("bg-fuchsia-900/30", "text-fuchsia-400", "border-fuchsia-600")
  | (Unknown, DeuteranopiaPalette) => ("bg-gray-900/30", "text-gray-400", "border-gray-600")

  // Protanopia-safe palette (green → cyan, red → magenta)
  | (Verified, ProtanopiaPalette) => ("bg-cyan-900/30", "text-cyan-400", "border-cyan-600")
  | (HumanReviewed, ProtanopiaPalette) => ("bg-blue-900/30", "text-blue-400", "border-blue-600")
  | (AiAssisted, ProtanopiaPalette) => ("bg-orange-900/30", "text-orange-400", "border-orange-600")
  | (UnreviewedAi, ProtanopiaPalette) => ("bg-fuchsia-900/30", "text-fuchsia-400", "border-fuchsia-600")
  | (Unknown, ProtanopiaPalette) => ("bg-gray-900/30", "text-gray-400", "border-gray-600")

  // High-contrast palette
  | (Verified, HighContrastPalette) => ("bg-green-800", "text-white", "border-green-400")
  | (HumanReviewed, HighContrastPalette) => ("bg-blue-800", "text-white", "border-blue-400")
  | (AiAssisted, HighContrastPalette) => ("bg-yellow-600", "text-black", "border-yellow-400")
  | (UnreviewedAi, HighContrastPalette) => ("bg-red-800", "text-white", "border-red-400")
  | (Unknown, HighContrastPalette) => ("bg-gray-700", "text-gray-200", "border-gray-400")
  }
}

/// Whether a trust level should trigger hostile UX (pulsing, alarming visuals).
let isHostile = (level: trustLevel): bool => {
  level === UnreviewedAi
}

/// CSS classes for hostile UX animation on unreviewed AI regions.
/// Returns empty string for non-hostile trust levels.
let hostileClasses = (level: trustLevel, suppressed: bool): string => {
  if isHostile(level) && !suppressed {
    "animate-pulse border-2 border-red-500 ring-2 ring-red-500/50"
  } else {
    ""
  }
}

/// Compute the trust percentage (verified + human-reviewed) for a file.
/// This is the "trust score" shown in the provenance summary bar.
let trustPercentage = (summary: provenanceSummary): float => {
  if summary.totalLines === 0 {
    0.0
  } else {
    let trusted = Float.fromInt(summary.verifiedLines + summary.humanReviewedLines)
    trusted /. Float.fromInt(summary.totalLines) *. 100.0
  }
}

/// Default provenance state — enabled with standard palette.
let defaultState: provenanceState = {
  enabled: true,
  activeFile: None,
  cache: [],
  palette: StandardPalette,
  hostileUxActive: false,
  hostileUxSuppressed: false,
  loading: false,
  error: None,
}

/// Build a simple provenance DAG from a set of file provenances.
/// Each file becomes a SourceNode, and files that import from each other
/// get edges. This is the naive version — the real one would parse imports.
let buildDag = (files: array<fileProvenance>): provenanceDag => {
  let nodes = files->Array.map(fp => {
    let trust = if fp.summary.verifiedLines > fp.summary.totalLines / 2 {
      Verified
    } else if fp.summary.humanReviewedLines > fp.summary.totalLines / 2 {
      HumanReviewed
    } else if fp.summary.aiAssistedLines > fp.summary.totalLines / 2 {
      AiAssisted
    } else if fp.summary.unreviewedAiLines > 0 {
      UnreviewedAi
    } else {
      Unknown
    }
    {
      id: fp.filePath,
      label: fp.filePath,
      kind: SourceNode,
      trustLevel: trust,
      contentHash: "",
      createdAt: fp.analysedAt,
      verified: fp.summary.unsoundMarkers === 0 && trust === Verified,
    }
  })
  {
    nodes,
    edges: [],
    roots: nodes->Array.map(n => n.id),
    leaves: nodes->Array.map(n => n.id),
    computedAt: Date.now(),
  }
}

/// Find all transitive dependencies (ancestors) of a node in the DAG.
let ancestors = (dag: provenanceDag, nodeId: string): array<string> => {
  let rec walk = (current: string, visited: array<string>): array<string> => {
    if visited->Array.some(v => v === current) {
      visited
    } else {
      let visited = Array.concat(visited, [current])
      dag.edges
      ->Array.filter(e => e.toId === current)
      ->Array.reduce(visited, (acc, e) => walk(e.fromId, acc))
    }
  }
  walk(nodeId, [])->Array.filter(id => id !== nodeId)
}

/// Find all transitive dependents (descendants) of a node in the DAG.
let descendants = (dag: provenanceDag, nodeId: string): array<string> => {
  let rec walk = (current: string, visited: array<string>): array<string> => {
    if visited->Array.some(v => v === current) {
      visited
    } else {
      let visited = Array.concat(visited, [current])
      dag.edges
      ->Array.filter(e => e.fromId === current)
      ->Array.reduce(visited, (acc, e) => walk(e.toId, acc))
    }
  }
  walk(nodeId, [])->Array.filter(id => id !== nodeId)
}

/// Compute the "blast radius" — if a node's trust is compromised, how many
/// downstream nodes are affected? Returns (directCount, transitiveCount).
let blastRadius = (dag: provenanceDag, nodeId: string): (int, int) => {
  let direct = dag.edges->Array.filter(e => e.fromId === nodeId)->Array.length
  let transitive = descendants(dag, nodeId)->Array.length
  (direct, transitive)
}

/// Label for a DAG node kind.
let dagNodeKindLabel = (kind: dagNodeKind): string => {
  switch kind {
  | SourceNode => "Source"
  | BuildNode => "Build"
  | DependencyNode => "Dependency"
  | ProofNode => "Proof"
  | AttestationNode => "Attestation"
  }
}

/// CSS colour class for a DAG node kind.
let dagNodeKindColour = (kind: dagNodeKind): string => {
  switch kind {
  | SourceNode => "text-blue-400"
  | BuildNode => "text-amber-400"
  | DependencyNode => "text-purple-400"
  | ProofNode => "text-green-400"
  | AttestationNode => "text-cyan-400"
  }
}
