// SPDX-License-Identifier: PMPL-1.0-or-later

/// PanLL VAB Catalog — The complete proven-servers component library.
///
/// Hardcoded catalog of all 108 verified server components from the
/// proven-servers project. Each entry declares ports, dependencies,
/// capabilities, and description for the VAB assembly panel.
///
/// Component breakdown:
///   - 8 core primitives (socket, frame, fsm, wire, compose, tls, config, audit)
///   - 94 protocol implementations across 9 domains
///   - 6 connector interfaces (dbconn, cacheconn, storageconn, queueconn, authconn, resolverconn)
///
/// All components are formally verified Idris2 with %default total and
/// zero believe_me instances.

/// Uses VabModel types directly (not Model) to avoid dependency cycles.
/// Model includes VabModel, but also references VabCatalog — so we go
/// straight to the leaf module.
open VabModel

// ===========================================================================
// Core Primitives (8)
// ===========================================================================

/// Core primitives — the fundamental building blocks that protocols depend on.
/// These are the proven-servers equivalent of KSP's command pods and fuel tanks.
let coreComponents: array<vabComponent> = [
  {
    id: "proven-socket",
    name: "Socket Primitive",
    shortName: "socket",
    category: VabCore,
    ports: [],
    dependencies: [],
    softDependencies: [],
    capabilities: ["tcp", "udp", "networking"],
    description: "Verified TCP/UDP socket abstraction. Foundation of all network protocols.",
    rackUnits: 1,
  },
  {
    id: "proven-frame",
    name: "Frame Codec",
    shortName: "frame",
    category: VabCore,
    ports: [],
    dependencies: ["proven-socket"],
    softDependencies: [],
    capabilities: ["framing", "codec"],
    description: "Length-delimited frame encoding/decoding with verified boundary checks.",
    rackUnits: 1,
  },
  {
    id: "proven-fsm",
    name: "Finite State Machine",
    shortName: "fsm",
    category: VabCore,
    ports: [],
    dependencies: [],
    softDependencies: [],
    capabilities: ["state-machine", "protocol-logic"],
    description: "Verified FSM engine for protocol state transitions. Proves no invalid states reachable.",
    rackUnits: 1,
  },
  {
    id: "proven-wire",
    name: "Wire Format",
    shortName: "wire",
    category: VabCore,
    ports: [],
    dependencies: [],
    softDependencies: [],
    capabilities: ["serialisation", "wire-format"],
    description: "Binary wire format serialisation with proven round-trip correctness.",
    rackUnits: 1,
  },
  {
    id: "proven-compose",
    name: "Protocol Composer",
    shortName: "compose",
    category: VabCore,
    ports: [],
    dependencies: ["proven-fsm"],
    softDependencies: [],
    capabilities: ["composition", "protocol-stack"],
    description: "Composes protocol layers into verified stacks. Proves layer compatibility.",
    rackUnits: 1,
  },
  {
    id: "proven-tls",
    name: "TLS Engine",
    shortName: "tls",
    category: VabCore,
    ports: [443],
    dependencies: ["proven-socket"],
    softDependencies: ["proven-config"],
    capabilities: ["encryption", "tls", "certificates"],
    description: "Verified TLS 1.3 implementation. All handshake states formally proven.",
    rackUnits: 2,
  },
  {
    id: "proven-config",
    name: "Configuration",
    shortName: "config",
    category: VabCore,
    ports: [],
    dependencies: [],
    softDependencies: [],
    capabilities: ["configuration", "settings"],
    description: "Type-safe configuration loading with schema validation proofs.",
    rackUnits: 1,
  },
  {
    id: "proven-audit",
    name: "Audit Logger",
    shortName: "audit",
    category: VabCore,
    ports: [],
    dependencies: [],
    softDependencies: ["proven-config"],
    capabilities: ["audit-logging", "compliance"],
    description: "Tamper-evident audit trail with cryptographic chain of custody proofs.",
    rackUnits: 1,
  },
]

// ===========================================================================
// Network Protocols (12)
// ===========================================================================

/// Network-layer protocols — transport, tunnelling, and low-level networking.
let networkComponents: array<vabComponent> = [
  {
    id: "proven-proxy",
    name: "Reverse Proxy",
    shortName: "proxy",
    category: VabNetwork,
    ports: [8080],
    dependencies: ["proven-socket"],
    softDependencies: ["proven-tls", "proven-audit"],
    capabilities: ["proxying", "load-distribution"],
    description: "Verified reverse proxy with connection pooling and header rewriting.",
    rackUnits: 2,
  },
  {
    id: "proven-loadbalancer",
    name: "Load Balancer",
    shortName: "lb",
    category: VabNetwork,
    ports: [80, 443],
    dependencies: ["proven-socket"],
    softDependencies: ["proven-tls", "proven-config"],
    capabilities: ["load-balancing", "health-checks"],
    description: "Verified L4/L7 load balancer with provably fair distribution algorithms.",
    rackUnits: 2,
  },
  {
    id: "proven-vpn",
    name: "VPN Gateway",
    shortName: "vpn",
    category: VabNetwork,
    ports: [1194],
    dependencies: ["proven-socket", "proven-tls"],
    softDependencies: ["proven-audit"],
    capabilities: ["vpn", "tunnelling", "encryption"],
    description: "Verified VPN tunnel with proven key exchange and forward secrecy.",
    rackUnits: 2,
  },
  {
    id: "proven-firewall",
    name: "Packet Filter",
    shortName: "fw",
    category: VabNetwork,
    ports: [],
    dependencies: ["proven-socket"],
    softDependencies: ["proven-audit", "proven-config"],
    capabilities: ["firewall", "packet-filtering"],
    description: "Verified stateful packet filter with provably complete rule evaluation.",
    rackUnits: 2,
  },
  {
    id: "proven-socks",
    name: "SOCKS Proxy",
    shortName: "socks",
    category: VabNetwork,
    ports: [1080],
    dependencies: ["proven-socket"],
    softDependencies: ["proven-audit"],
    capabilities: ["socks-proxy", "tunnelling"],
    description: "SOCKS5 proxy with verified authentication and UDP relay support.",
    rackUnits: 1,
  },
  {
    id: "proven-stun",
    name: "STUN/TURN",
    shortName: "stun",
    category: VabNetwork,
    ports: [3478],
    dependencies: ["proven-socket"],
    softDependencies: [],
    capabilities: ["nat-traversal", "stun", "turn"],
    description: "Verified STUN/TURN server for NAT traversal with proven relay correctness.",
    rackUnits: 1,
  },
  {
    id: "proven-sdn",
    name: "SDN Controller",
    shortName: "sdn",
    category: VabNetwork,
    ports: [6633],
    dependencies: ["proven-socket", "proven-fsm"],
    softDependencies: ["proven-config", "proven-audit"],
    capabilities: ["sdn", "network-control"],
    description: "Software-defined networking controller with verified flow table management.",
    rackUnits: 2,
  },
  {
    id: "proven-telnet",
    name: "Telnet Server",
    shortName: "telnet",
    category: VabNetwork,
    ports: [23],
    dependencies: ["proven-socket"],
    softDependencies: ["proven-audit"],
    capabilities: ["telnet", "remote-access"],
    description: "Verified Telnet with option negotiation. Use SSH for production; this is for legacy/honeypot.",
    rackUnits: 1,
  },
  {
    id: "proven-diode",
    name: "Data Diode",
    shortName: "diode",
    category: VabNetwork,
    ports: [],
    dependencies: ["proven-socket"],
    softDependencies: ["proven-audit"],
    capabilities: ["data-diode", "one-way"],
    description: "Verified unidirectional data flow enforcer. Proves no reverse channel exists.",
    rackUnits: 1,
  },
  {
    id: "proven-airgap",
    name: "Air Gap Bridge",
    shortName: "airgap",
    category: VabNetwork,
    ports: [],
    dependencies: ["proven-diode"],
    softDependencies: ["proven-audit"],
    capabilities: ["airgap", "isolation"],
    description: "Verified air-gap bridge with proven data sanitisation between networks.",
    rackUnits: 2,
  },
  {
    id: "proven-bfd",
    name: "BFD Daemon",
    shortName: "bfd",
    category: VabNetwork,
    ports: [3784],
    dependencies: ["proven-socket"],
    softDependencies: [],
    capabilities: ["bfd", "failure-detection"],
    description: "Bidirectional Forwarding Detection with verified sub-second failure detection.",
    rackUnits: 1,
  },
  {
    id: "proven-ptp",
    name: "PTP Clock",
    shortName: "ptp",
    category: VabNetwork,
    ports: [319, 320],
    dependencies: ["proven-socket"],
    softDependencies: ["proven-config"],
    capabilities: ["precision-time", "clock-sync"],
    description: "IEEE 1588 Precision Time Protocol with verified clock discipline algorithms.",
    rackUnits: 1,
  },
]

// ===========================================================================
// DNS Protocols (5)
// ===========================================================================

/// DNS protocol family — resolution, authority, multicast, encrypted DNS.
let dnsComponents: array<vabComponent> = [
  {
    id: "proven-dns",
    name: "DNS Resolver",
    shortName: "dns",
    category: VabDns,
    ports: [53],
    dependencies: ["proven-socket"],
    softDependencies: ["proven-cache"],
    capabilities: ["dns-resolution", "name-lookup"],
    description: "Verified recursive DNS resolver with DNSSEC validation proofs.",
    rackUnits: 1,
  },
  {
    id: "proven-mdns",
    name: "mDNS Responder",
    shortName: "mdns",
    category: VabDns,
    ports: [5353],
    dependencies: ["proven-socket"],
    softDependencies: [],
    capabilities: ["mdns", "service-discovery"],
    description: "Multicast DNS for local service discovery with verified conflict resolution.",
    rackUnits: 1,
  },
  {
    id: "proven-doh",
    name: "DNS over HTTPS",
    shortName: "doh",
    category: VabDns,
    ports: [443],
    dependencies: ["proven-socket", "proven-tls", "proven-httpd"],
    softDependencies: ["proven-cache"],
    capabilities: ["dns-resolution", "encrypted-dns"],
    description: "RFC 8484 DNS-over-HTTPS with verified query encryption and response integrity.",
    rackUnits: 1,
  },
  {
    id: "proven-dot",
    name: "DNS over TLS",
    shortName: "dot",
    category: VabDns,
    ports: [853],
    dependencies: ["proven-socket", "proven-tls"],
    softDependencies: ["proven-cache"],
    capabilities: ["dns-resolution", "encrypted-dns"],
    description: "RFC 7858 DNS-over-TLS with verified handshake and query privacy.",
    rackUnits: 1,
  },
  {
    id: "proven-doq",
    name: "DNS over QUIC",
    shortName: "doq",
    category: VabDns,
    ports: [853],
    dependencies: ["proven-socket", "proven-tls"],
    softDependencies: ["proven-cache"],
    capabilities: ["dns-resolution", "encrypted-dns"],
    description: "RFC 9250 DNS-over-QUIC with verified 0-RTT query resumption.",
    rackUnits: 1,
  },
]

// ===========================================================================
// Web Protocols (10)
// ===========================================================================

/// Web protocols — HTTP, WebSocket, gRPC, GraphQL, REST, SSE, and more.
let webComponents: array<vabComponent> = [
  {
    id: "proven-httpd",
    name: "HTTP Server",
    shortName: "httpd",
    category: VabWeb,
    ports: [80, 443],
    dependencies: ["proven-socket"],
    softDependencies: ["proven-tls", "proven-audit"],
    capabilities: ["http", "web-serving", "document-json", "document-xml", "i18n"],
    description: "Verified HTTP/1.1 server with provably correct request parsing, response framing, content negotiation, and Accept-Language routing.",
    rackUnits: 2,
  },
  {
    id: "proven-ws",
    name: "WebSocket Server",
    shortName: "ws",
    category: VabWeb,
    ports: [8080],
    dependencies: ["proven-socket", "proven-httpd"],
    softDependencies: ["proven-tls"],
    capabilities: ["websocket", "real-time"],
    description: "Verified WebSocket with proven upgrade handshake and frame masking.",
    rackUnits: 1,
  },
  {
    id: "proven-grpc",
    name: "gRPC Server",
    shortName: "grpc",
    category: VabWeb,
    ports: [50051],
    dependencies: ["proven-socket", "proven-frame"],
    softDependencies: ["proven-tls"],
    capabilities: ["grpc", "rpc", "protobuf"],
    description: "Verified gRPC with proven HTTP/2 framing and protobuf serialisation.",
    rackUnits: 2,
  },
  {
    id: "proven-graphql",
    name: "GraphQL Server",
    shortName: "graphql",
    category: VabWeb,
    ports: [4000],
    dependencies: ["proven-httpd"],
    softDependencies: ["proven-tls", "proven-audit"],
    capabilities: ["graphql", "api", "document-json", "i18n"],
    description: "Verified GraphQL executor with proven query validation, depth limiting, and i18n-aware error messages.",
    rackUnits: 2,
  },
  {
    id: "proven-apiserver",
    name: "API Server",
    shortName: "api",
    category: VabWeb,
    ports: [8443],
    dependencies: ["proven-httpd"],
    softDependencies: ["proven-tls", "proven-audit", "proven-config"],
    capabilities: ["rest-api", "json-api", "document-json", "i18n"],
    description: "REST API server with verified route matching, content negotiation, and i18n-aware response localisation.",
    rackUnits: 2,
  },
  {
    id: "proven-appserver",
    name: "Application Server",
    shortName: "app",
    category: VabWeb,
    ports: [3000],
    dependencies: ["proven-httpd"],
    softDependencies: ["proven-tls", "proven-config", "proven-audit"],
    capabilities: ["application", "web-app"],
    description: "General-purpose application server with verified middleware pipeline.",
    rackUnits: 2,
  },
  {
    id: "proven-webdav",
    name: "WebDAV Server",
    shortName: "webdav",
    category: VabWeb,
    ports: [80, 443],
    dependencies: ["proven-httpd"],
    softDependencies: ["proven-tls", "proven-audit"],
    capabilities: ["webdav", "file-sharing"],
    description: "Verified WebDAV with proven lock management and property store consistency.",
    rackUnits: 1,
  },
  {
    id: "proven-ldp",
    name: "Linked Data Platform",
    shortName: "ldp",
    category: VabWeb,
    ports: [8080],
    dependencies: ["proven-httpd"],
    softDependencies: ["proven-tls"],
    capabilities: ["linked-data", "rdf"],
    description: "W3C Linked Data Platform with verified container/resource semantics.",
    rackUnits: 1,
  },
  {
    id: "proven-semweb",
    name: "Semantic Web",
    shortName: "semweb",
    category: VabWeb,
    ports: [8080],
    dependencies: ["proven-httpd"],
    softDependencies: ["proven-tls"],
    capabilities: ["semantic-web", "rdf", "ontology"],
    description: "Semantic web endpoint with verified RDF graph operations and SHACL validation.",
    rackUnits: 1,
  },
  {
    id: "proven-wasm",
    name: "WASM Runtime",
    shortName: "wasm",
    category: VabWeb,
    ports: [],
    dependencies: [],
    softDependencies: ["proven-sandbox"],
    capabilities: ["wasm", "sandboxed-execution"],
    description: "Verified WebAssembly runtime with proven memory safety and sandboxing.",
    rackUnits: 2,
  },
]

// ===========================================================================
// IoT Protocols (7)
// ===========================================================================

/// IoT protocols — MQTT, CoAP, AMQP, LwM2M, industrial, and smart home.
let iotComponents: array<vabComponent> = [
  {
    id: "proven-mqtt",
    name: "MQTT Broker",
    shortName: "mqtt",
    category: VabIot,
    ports: [1883, 8883],
    dependencies: ["proven-socket"],
    softDependencies: ["proven-tls", "proven-audit"],
    capabilities: ["mqtt", "pub-sub", "iot-messaging"],
    description: "Verified MQTT v5.0 broker with proven QoS delivery guarantees.",
    rackUnits: 2,
  },
  {
    id: "proven-coap",
    name: "CoAP Server",
    shortName: "coap",
    category: VabIot,
    ports: [5683, 5684],
    dependencies: ["proven-socket"],
    softDependencies: ["proven-tls"],
    capabilities: ["coap", "iot-rest"],
    description: "Verified CoAP with proven observe mechanism and block-wise transfer.",
    rackUnits: 1,
  },
  {
    id: "proven-amqp",
    name: "AMQP Broker",
    shortName: "amqp",
    category: VabIot,
    ports: [5672, 5671],
    dependencies: ["proven-socket", "proven-frame"],
    softDependencies: ["proven-tls", "proven-audit"],
    capabilities: ["amqp", "message-queue"],
    description: "Verified AMQP 0-9-1 broker with proven message ordering and acknowledgement.",
    rackUnits: 2,
  },
  {
    id: "proven-modbus",
    name: "Modbus Server",
    shortName: "modbus",
    category: VabIot,
    ports: [502],
    dependencies: ["proven-socket"],
    softDependencies: ["proven-audit"],
    capabilities: ["modbus", "industrial-control"],
    description: "Verified Modbus TCP with proven register access control and bounds checking.",
    rackUnits: 1,
  },
  {
    id: "proven-opcua",
    name: "OPC UA Server",
    shortName: "opcua",
    category: VabIot,
    ports: [4840],
    dependencies: ["proven-socket", "proven-tls"],
    softDependencies: ["proven-audit", "proven-config"],
    capabilities: ["opcua", "industrial-automation"],
    description: "Verified OPC UA with proven information model consistency and security modes.",
    rackUnits: 2,
  },
  {
    id: "proven-netconf",
    name: "NETCONF Server",
    shortName: "netconf",
    category: VabIot,
    ports: [830],
    dependencies: ["proven-socket"],
    softDependencies: ["proven-tls", "proven-config"],
    capabilities: ["netconf", "network-config"],
    description: "Verified NETCONF with proven YANG model validation and transactional edits.",
    rackUnits: 1,
  },
  {
    id: "proven-mcp",
    name: "Model Context Protocol",
    shortName: "mcp",
    category: VabIot,
    ports: [8080],
    dependencies: ["proven-socket", "proven-frame"],
    softDependencies: ["proven-tls", "proven-audit"],
    capabilities: ["mcp", "ai-tooling"],
    description: "Verified MCP server for AI tool integration with proven capability negotiation.",
    rackUnits: 1,
  },
]

// ===========================================================================
// Email Protocols (5)
// ===========================================================================

/// Email protocols — SMTP, IMAP, POP3, and email authentication.
let emailComponents: array<vabComponent> = [
  {
    id: "proven-smtp",
    name: "SMTP Server",
    shortName: "smtp",
    category: VabEmail,
    ports: [25, 587],
    dependencies: ["proven-socket"],
    softDependencies: ["proven-tls", "proven-audit"],
    capabilities: ["email-send", "smtp"],
    description: "Verified SMTP with proven envelope validation and relay control.",
    rackUnits: 2,
  },
  {
    id: "proven-imap",
    name: "IMAP Server",
    shortName: "imap",
    category: VabEmail,
    ports: [143, 993],
    dependencies: ["proven-socket"],
    softDependencies: ["proven-tls", "proven-audit"],
    capabilities: ["email-receive", "imap", "mailbox"],
    description: "Verified IMAP4rev2 with proven mailbox state consistency and IDLE notification.",
    rackUnits: 2,
  },
  {
    id: "proven-pop3",
    name: "POP3 Server",
    shortName: "pop3",
    category: VabEmail,
    ports: [110, 995],
    dependencies: ["proven-socket"],
    softDependencies: ["proven-tls"],
    capabilities: ["email-receive", "pop3"],
    description: "Verified POP3 with proven download-and-delete semantics.",
    rackUnits: 1,
  },
  {
    id: "proven-lpd",
    name: "Line Printer Daemon",
    shortName: "lpd",
    category: VabEmail,
    ports: [515],
    dependencies: ["proven-socket"],
    softDependencies: [],
    capabilities: ["printing", "lpd"],
    description: "Verified LPD with proven job queue management and access control.",
    rackUnits: 1,
  },
  {
    id: "proven-odns",
    name: "Oblivious DNS",
    shortName: "odns",
    category: VabEmail,
    ports: [443],
    dependencies: ["proven-socket", "proven-tls"],
    softDependencies: [],
    capabilities: ["dns-privacy", "oblivious-dns"],
    description: "Oblivious DNS-over-HTTPS relay with proven query unlinkability.",
    rackUnits: 1,
  },
]

// ===========================================================================
// Security Protocols (14)
// ===========================================================================

/// Security protocols — authentication, key management, intrusion detection,
/// certificate transparency, post-quantum crypto, and zero-trust architecture.
let securityComponents: array<vabComponent> = [
  {
    id: "proven-ssh-bastion",
    name: "SSH Bastion",
    shortName: "ssh",
    category: VabSecurity,
    ports: [22],
    dependencies: ["proven-socket"],
    softDependencies: ["proven-audit"],
    capabilities: ["ssh", "remote-access", "bastion"],
    description: "Verified SSH bastion host with proven key exchange and session recording.",
    rackUnits: 2,
  },
  {
    id: "proven-kerberos",
    name: "Kerberos KDC",
    shortName: "krb5",
    category: VabSecurity,
    ports: [88],
    dependencies: ["proven-socket"],
    softDependencies: ["proven-audit", "proven-config"],
    capabilities: ["kerberos", "authentication", "sso"],
    description: "Verified Kerberos 5 KDC with proven ticket granting and cross-realm trust.",
    rackUnits: 2,
  },
  {
    id: "proven-radius",
    name: "RADIUS Server",
    shortName: "radius",
    category: VabSecurity,
    ports: [1812, 1813],
    dependencies: ["proven-socket"],
    softDependencies: ["proven-audit"],
    capabilities: ["radius", "aaa"],
    description: "Verified RADIUS with proven authenticator and attribute validation.",
    rackUnits: 1,
  },
  {
    id: "proven-tacacs",
    name: "TACACS+ Server",
    shortName: "tacacs",
    category: VabSecurity,
    ports: [49],
    dependencies: ["proven-socket"],
    softDependencies: ["proven-audit"],
    capabilities: ["tacacs", "aaa", "network-auth"],
    description: "Verified TACACS+ with proven authentication/authorisation/accounting separation.",
    rackUnits: 1,
  },
  {
    id: "proven-ldap",
    name: "LDAP Directory",
    shortName: "ldap",
    category: VabSecurity,
    ports: [389, 636],
    dependencies: ["proven-socket"],
    softDependencies: ["proven-tls", "proven-audit"],
    capabilities: ["ldap", "directory", "authentication"],
    description: "Verified LDAP directory with proven search filter evaluation and ACL enforcement.",
    rackUnits: 2,
  },
  {
    id: "proven-authserver",
    name: "Auth Server",
    shortName: "auth",
    category: VabSecurity,
    ports: [8443],
    dependencies: ["proven-httpd", "proven-tls"],
    softDependencies: ["proven-audit", "proven-config"],
    capabilities: ["oauth", "oidc", "authentication"],
    description: "Verified OAuth 2.0/OIDC server with proven token lifecycle and consent flows.",
    rackUnits: 2,
  },
  {
    id: "proven-ca",
    name: "Certificate Authority",
    shortName: "ca",
    category: VabSecurity,
    ports: [8443],
    dependencies: ["proven-tls"],
    softDependencies: ["proven-audit", "proven-config"],
    capabilities: ["certificates", "pki", "ca"],
    description: "Verified X.509 CA with proven certificate chain validation and CRL management.",
    rackUnits: 2,
  },
  {
    id: "proven-ocsp",
    name: "OCSP Responder",
    shortName: "ocsp",
    category: VabSecurity,
    ports: [80],
    dependencies: ["proven-httpd"],
    softDependencies: ["proven-ca"],
    capabilities: ["ocsp", "certificate-status"],
    description: "Verified OCSP responder with proven certificate revocation status lookups.",
    rackUnits: 1,
  },
  {
    id: "proven-ctlog",
    name: "CT Log",
    shortName: "ctlog",
    category: VabSecurity,
    ports: [443],
    dependencies: ["proven-httpd", "proven-tls"],
    softDependencies: ["proven-audit"],
    capabilities: ["certificate-transparency", "ct-log"],
    description: "Certificate Transparency log with verified Merkle tree append-only semantics.",
    rackUnits: 2,
  },
  {
    id: "proven-kms",
    name: "Key Management",
    shortName: "kms",
    category: VabSecurity,
    ports: [5696],
    dependencies: ["proven-tls"],
    softDependencies: ["proven-audit", "proven-config"],
    capabilities: ["key-management", "encryption-keys"],
    description: "KMIP-compliant key management with verified key lifecycle and access control.",
    rackUnits: 2,
  },
  {
    id: "proven-ids",
    name: "Intrusion Detection",
    shortName: "ids",
    category: VabSecurity,
    ports: [],
    dependencies: ["proven-socket"],
    softDependencies: ["proven-audit", "proven-config"],
    capabilities: ["ids", "intrusion-detection"],
    description: "Verified IDS with proven pattern matching and anomaly detection classification.",
    rackUnits: 2,
  },
  {
    id: "proven-pqc",
    name: "Post-Quantum Crypto",
    shortName: "pqc",
    category: VabSecurity,
    ports: [],
    dependencies: ["proven-tls"],
    softDependencies: [],
    capabilities: ["post-quantum", "pqc", "encryption"],
    description: "Post-quantum cryptographic primitives (ML-KEM, ML-DSA) with verified correctness.",
    rackUnits: 1,
  },
  {
    id: "proven-zerotrust",
    name: "Zero Trust Engine",
    shortName: "ztrust",
    category: VabSecurity,
    ports: [443],
    dependencies: ["proven-httpd", "proven-tls"],
    softDependencies: ["proven-audit", "proven-authserver"],
    capabilities: ["zero-trust", "policy-engine"],
    description: "Verified zero-trust policy engine with proven continuous authentication.",
    rackUnits: 2,
  },
  {
    id: "proven-honeypot",
    name: "Honeypot",
    shortName: "honeypot",
    category: VabSecurity,
    ports: [23, 80, 22],
    dependencies: ["proven-socket"],
    softDependencies: ["proven-audit", "proven-telnet"],
    capabilities: ["deception", "honeypot"],
    description: "Verified honeypot with proven attacker session isolation and behaviour logging.",
    rackUnits: 1,
  },
]

// ===========================================================================
// Data Protocols (14)
// ===========================================================================

/// Data protocols — databases, caches, file transfer, object storage,
/// graph databases, triple stores, and semantic query engines.
let dataComponents: array<vabComponent> = [
  {
    id: "proven-dbserver",
    name: "Database Server",
    shortName: "db",
    category: VabData,
    ports: [5432],
    dependencies: ["proven-socket"],
    softDependencies: ["proven-tls", "proven-audit", "proven-config"],
    capabilities: ["database", "sql", "persistence"],
    description: "Verified relational database server with proven transaction isolation.",
    rackUnits: 2,
  },
  {
    id: "proven-graphdb",
    name: "Graph Database",
    shortName: "graphdb",
    category: VabData,
    ports: [7687],
    dependencies: ["proven-socket"],
    softDependencies: ["proven-tls", "proven-audit"],
    capabilities: ["graph-database", "graph-queries"],
    description: "Verified property graph database with proven traversal correctness.",
    rackUnits: 2,
  },
  {
    id: "proven-triplestore",
    name: "Triple Store",
    shortName: "triples",
    category: VabData,
    ports: [3030],
    dependencies: ["proven-socket"],
    softDependencies: ["proven-tls"],
    capabilities: ["rdf-store", "sparql"],
    description: "Verified RDF triple store with proven SPARQL query evaluation semantics.",
    rackUnits: 2,
  },
  {
    id: "proven-sparql",
    name: "SPARQL Endpoint",
    shortName: "sparql",
    category: VabData,
    ports: [3030],
    dependencies: ["proven-httpd", "proven-triplestore"],
    softDependencies: ["proven-tls"],
    capabilities: ["sparql", "semantic-query"],
    description: "Verified SPARQL 1.1 endpoint with proven query algebra evaluation.",
    rackUnits: 1,
  },
  {
    id: "proven-cache",
    name: "Cache Server",
    shortName: "cache",
    category: VabData,
    ports: [6379, 11211],
    dependencies: ["proven-socket"],
    softDependencies: ["proven-config"],
    capabilities: ["caching", "in-memory"],
    description: "Verified in-memory cache with proven eviction policy correctness (LRU, LFU).",
    rackUnits: 1,
  },
  {
    id: "proven-objectstore",
    name: "Object Store",
    shortName: "objstore",
    category: VabData,
    ports: [9000],
    dependencies: ["proven-httpd"],
    softDependencies: ["proven-tls", "proven-audit"],
    capabilities: ["object-storage", "s3-compatible"],
    description: "S3-compatible verified object store with proven consistency and versioning.",
    rackUnits: 2,
  },
  {
    id: "proven-ftp",
    name: "FTP Server",
    shortName: "ftp",
    category: VabData,
    ports: [21],
    dependencies: ["proven-socket"],
    softDependencies: ["proven-tls", "proven-audit"],
    capabilities: ["ftp", "file-transfer"],
    description: "Verified FTP with proven directory traversal prevention and passive mode.",
    rackUnits: 1,
  },
  {
    id: "proven-tftp",
    name: "TFTP Server",
    shortName: "tftp",
    category: VabData,
    ports: [69],
    dependencies: ["proven-socket"],
    softDependencies: [],
    capabilities: ["tftp", "boot-transfer"],
    description: "Verified TFTP with proven block acknowledgement and timeout handling.",
    rackUnits: 1,
  },
  {
    id: "proven-nfs",
    name: "NFS Server",
    shortName: "nfs",
    category: VabData,
    ports: [2049],
    dependencies: ["proven-socket"],
    softDependencies: ["proven-tls", "proven-audit"],
    capabilities: ["nfs", "network-filesystem"],
    description: "Verified NFSv4 with proven delegation and lock management.",
    rackUnits: 2,
  },
  {
    id: "proven-smb",
    name: "SMB Server",
    shortName: "smb",
    category: VabData,
    ports: [445],
    dependencies: ["proven-socket"],
    softDependencies: ["proven-tls", "proven-audit"],
    capabilities: ["smb", "file-sharing"],
    description: "Verified SMB3 with proven oplock/lease management and signing.",
    rackUnits: 2,
  },
  {
    id: "proven-fileserver",
    name: "File Server",
    shortName: "files",
    category: VabData,
    ports: [80, 443],
    dependencies: ["proven-httpd"],
    softDependencies: ["proven-tls", "proven-audit"],
    capabilities: ["file-serving", "static-content"],
    description: "Verified static file server with proven path traversal prevention.",
    rackUnits: 1,
  },
  {
    id: "proven-backup",
    name: "Backup Server",
    shortName: "backup",
    category: VabData,
    ports: [8200],
    dependencies: ["proven-socket"],
    softDependencies: ["proven-tls", "proven-audit", "proven-config"],
    capabilities: ["backup", "disaster-recovery"],
    description: "Verified backup server with proven deduplication and integrity verification.",
    rackUnits: 2,
  },
  {
    id: "proven-git",
    name: "Git Server",
    shortName: "git",
    category: VabData,
    ports: [9418],
    dependencies: ["proven-socket"],
    softDependencies: ["proven-ssh-bastion", "proven-httpd", "proven-audit"],
    capabilities: ["git", "version-control"],
    description: "Verified Git smart protocol server with proven pack negotiation.",
    rackUnits: 1,
  },
  {
    id: "proven-configmgmt",
    name: "Config Management",
    shortName: "cfgmgmt",
    category: VabData,
    ports: [8140],
    dependencies: ["proven-httpd"],
    softDependencies: ["proven-tls", "proven-config", "proven-audit"],
    capabilities: ["config-management", "infrastructure-as-code"],
    description: "Verified configuration management server with proven convergence proofs.",
    rackUnits: 2,
  },
]

// ===========================================================================
// Application Protocols (14)
// ===========================================================================

/// Application protocols — VoIP, chat, media, gaming, CLI, agentic AI,
/// container orchestration, and neurosymbolic integration.
let applicationComponents: array<vabComponent> = [
  {
    id: "proven-voip",
    name: "VoIP Server",
    shortName: "voip",
    category: VabApplication,
    ports: [5060, 5061],
    dependencies: ["proven-socket"],
    softDependencies: ["proven-tls", "proven-audit"],
    capabilities: ["voip", "sip"],
    description: "Verified SIP/RTP VoIP server with proven call state machine and codec negotiation.",
    rackUnits: 2,
  },
  {
    id: "proven-xmpp",
    name: "XMPP Server",
    shortName: "xmpp",
    category: VabApplication,
    ports: [5222, 5269],
    dependencies: ["proven-socket"],
    softDependencies: ["proven-tls", "proven-audit"],
    capabilities: ["xmpp", "instant-messaging"],
    description: "Verified XMPP with proven roster management and message archiving.",
    rackUnits: 2,
  },
  {
    id: "proven-irc",
    name: "IRC Server",
    shortName: "irc",
    category: VabApplication,
    ports: [6667, 6697],
    dependencies: ["proven-socket"],
    softDependencies: ["proven-tls"],
    capabilities: ["irc", "chat"],
    description: "Verified IRCv3 with proven channel state and nick collision handling.",
    rackUnits: 1,
  },
  {
    id: "proven-chat",
    name: "Chat Server",
    shortName: "chat",
    category: VabApplication,
    ports: [8080],
    dependencies: ["proven-httpd", "proven-ws"],
    softDependencies: ["proven-tls", "proven-audit"],
    capabilities: ["chat", "real-time-messaging"],
    description: "Modern chat server with verified message ordering and delivery guarantees.",
    rackUnits: 2,
  },
  {
    id: "proven-rtsp",
    name: "RTSP Server",
    shortName: "rtsp",
    category: VabApplication,
    ports: [554],
    dependencies: ["proven-socket"],
    softDependencies: ["proven-tls"],
    capabilities: ["rtsp", "media-streaming"],
    description: "Verified RTSP with proven session state and RTP interleaving.",
    rackUnits: 1,
  },
  {
    id: "proven-media",
    name: "Media Server",
    shortName: "media",
    category: VabApplication,
    ports: [1935, 8080],
    dependencies: ["proven-socket", "proven-httpd"],
    softDependencies: ["proven-tls"],
    capabilities: ["media-streaming", "hls", "dash"],
    description: "Verified media server with proven adaptive bitrate and segment consistency.",
    rackUnits: 2,
  },
  {
    id: "proven-gameserver",
    name: "Game Server",
    shortName: "game",
    category: VabApplication,
    ports: [27015],
    dependencies: ["proven-socket"],
    softDependencies: ["proven-config", "proven-audit"],
    capabilities: ["game-server", "real-time"],
    description: "Verified game server framework with proven state synchronisation and tick rate.",
    rackUnits: 2,
  },
  {
    id: "proven-cli",
    name: "CLI Server",
    shortName: "cli",
    category: VabApplication,
    ports: [],
    dependencies: ["proven-config"],
    softDependencies: [],
    capabilities: ["cli", "command-line"],
    description: "Verified CLI command dispatcher with proven argument parsing and help generation.",
    rackUnits: 1,
  },
  {
    id: "proven-agentic",
    name: "Agentic Runtime",
    shortName: "agent",
    category: VabApplication,
    ports: [8080],
    dependencies: ["proven-httpd", "proven-fsm"],
    softDependencies: ["proven-tls", "proven-audit", "proven-config"],
    capabilities: ["ai-agents", "tool-use", "reasoning"],
    description: "Verified AI agent runtime with proven tool-call safety and reasoning bounds.",
    rackUnits: 2,
  },
  {
    id: "proven-neurosym",
    name: "Neurosymbolic Bridge",
    shortName: "nsym",
    category: VabApplication,
    ports: [9090],
    dependencies: ["proven-socket", "proven-fsm"],
    softDependencies: ["proven-tls", "proven-audit"],
    capabilities: ["neurosymbolic", "hybrid-ai"],
    description: "Bridge between neural inference and symbolic verification with proven soundness.",
    rackUnits: 2,
  },
  {
    id: "proven-federation",
    name: "Federation Server",
    shortName: "fed",
    category: VabApplication,
    ports: [443],
    dependencies: ["proven-httpd", "proven-tls"],
    softDependencies: ["proven-audit"],
    capabilities: ["federation", "activitypub"],
    description: "Verified ActivityPub federation with proven object delivery and signature verification.",
    rackUnits: 2,
  },
  {
    id: "proven-deception",
    name: "Deception Engine",
    shortName: "decoy",
    category: VabApplication,
    ports: [],
    dependencies: ["proven-socket"],
    softDependencies: ["proven-audit", "proven-honeypot"],
    capabilities: ["deception", "threat-intelligence"],
    description: "Verified deception technology with proven attacker engagement and breadcrumb placement.",
    rackUnits: 1,
  },
  {
    id: "proven-sandbox",
    name: "Sandbox Engine",
    shortName: "sandbox",
    category: VabApplication,
    ports: [],
    dependencies: [],
    softDependencies: ["proven-audit"],
    capabilities: ["sandboxing", "isolation"],
    description: "Verified execution sandbox with proven resource isolation and capability-based security.",
    rackUnits: 2,
  },
  {
    id: "proven-hardened",
    name: "Hardened Runtime",
    shortName: "hardened",
    category: VabApplication,
    ports: [],
    dependencies: [],
    softDependencies: ["proven-audit", "proven-config"],
    capabilities: ["hardening", "security-baseline"],
    description: "Verified security hardening primitives (ASLR, stack canaries, seccomp) with proofs.",
    rackUnits: 1,
  },
  {
    id: "proven-a2ml",
    name: "A2ML Manifest Engine",
    shortName: "a2ml",
    category: VabApplication,
    ports: [8080],
    dependencies: ["proven-httpd"],
    softDependencies: ["proven-config", "proven-audit"],
    capabilities: ["a2ml", "ai-manifest", "document-a2ml", "i18n"],
    description: "Verified A2ML manifest parser/server. Handles AI agent entry points, lifecycle hooks, and cross-agent knowledge transfer with i18n-aware field extraction.",
    rackUnits: 2,
  },
  {
    id: "proven-docserver",
    name: "Document Server",
    shortName: "docs",
    category: VabApplication,
    ports: [8080],
    dependencies: ["proven-httpd"],
    softDependencies: ["proven-tls", "proven-config"],
    capabilities: [
      "document-json",
      "document-yaml",
      "document-toml",
      "document-xml",
      "document-adoc",
      "document-djot",
      "document-markdown",
      "document-pdf",
      "i18n",
    ],
    description: "Multi-format document server with verified parsing for JSON, YAML, TOML, XML, AsciiDoc, Djot, Markdown, and PDF. I18n-aware content negotiation via Accept-Language.",
    rackUnits: 2,
  },
]

// ===========================================================================
// Infrastructure Protocols (13)
// ===========================================================================

/// Infrastructure protocols — syslog, SNMP, NTP, BGP, OSPF, DHCP,
/// monitoring, metrics collection, and container orchestration.
let infrastructureComponents: array<vabComponent> = [
  {
    id: "proven-syslog",
    name: "Syslog Server",
    shortName: "syslog",
    category: VabInfrastructure,
    ports: [514],
    dependencies: ["proven-socket"],
    softDependencies: ["proven-tls", "proven-audit"],
    capabilities: ["syslog", "log-collection"],
    description: "Verified syslog with proven message parsing (RFC 5424) and reliable delivery.",
    rackUnits: 1,
  },
  {
    id: "proven-snmp",
    name: "SNMP Agent",
    shortName: "snmp",
    category: VabInfrastructure,
    ports: [161, 162],
    dependencies: ["proven-socket"],
    softDependencies: ["proven-config"],
    capabilities: ["snmp", "network-monitoring"],
    description: "Verified SNMPv3 with proven MIB walk and authentication.",
    rackUnits: 1,
  },
  {
    id: "proven-ntp",
    name: "NTP Server",
    shortName: "ntp",
    category: VabInfrastructure,
    ports: [123],
    dependencies: ["proven-socket"],
    softDependencies: [],
    capabilities: ["ntp", "time-sync"],
    description: "Verified NTPv4 with proven clock discipline and Marzullo's algorithm.",
    rackUnits: 1,
  },
  {
    id: "proven-nts",
    name: "NTS Server",
    shortName: "nts",
    category: VabInfrastructure,
    ports: [123, 4460],
    dependencies: ["proven-socket", "proven-tls"],
    softDependencies: [],
    capabilities: ["nts", "secure-time-sync"],
    description: "Network Time Security with verified key exchange and authenticated timestamps.",
    rackUnits: 1,
  },
  {
    id: "proven-bgp",
    name: "BGP Speaker",
    shortName: "bgp",
    category: VabInfrastructure,
    ports: [179],
    dependencies: ["proven-socket", "proven-fsm"],
    softDependencies: ["proven-audit", "proven-config"],
    capabilities: ["bgp", "routing"],
    description: "Verified BGP-4 with proven path selection, loop detection, and RPKI validation.",
    rackUnits: 2,
  },
  {
    id: "proven-ospf",
    name: "OSPF Router",
    shortName: "ospf",
    category: VabInfrastructure,
    ports: [],
    dependencies: ["proven-socket", "proven-fsm"],
    softDependencies: ["proven-audit"],
    capabilities: ["ospf", "routing"],
    description: "Verified OSPFv3 with proven Dijkstra convergence and LSA flooding correctness.",
    rackUnits: 2,
  },
  {
    id: "proven-dhcp",
    name: "DHCP Server",
    shortName: "dhcp",
    category: VabInfrastructure,
    ports: [67, 68],
    dependencies: ["proven-socket"],
    softDependencies: ["proven-config"],
    capabilities: ["dhcp", "address-assignment"],
    description: "Verified DHCPv4/v6 with proven lease management and address pool exhaustion handling.",
    rackUnits: 1,
  },
  {
    id: "proven-monitor",
    name: "Monitor Server",
    shortName: "monitor",
    category: VabInfrastructure,
    ports: [8080],
    dependencies: ["proven-httpd"],
    softDependencies: ["proven-config", "proven-audit"],
    capabilities: ["monitoring", "health-checks"],
    description: "Verified monitoring server with proven check scheduling and alert deduplication.",
    rackUnits: 2,
  },
  {
    id: "proven-metrics",
    name: "Metrics Collector",
    shortName: "metrics",
    category: VabInfrastructure,
    ports: [9090],
    dependencies: ["proven-httpd"],
    softDependencies: ["proven-config"],
    capabilities: ["metrics", "prometheus-compatible"],
    description: "Verified metrics collector with proven cardinality control and aggregation.",
    rackUnits: 1,
  },
  {
    id: "proven-logcollector",
    name: "Log Collector",
    shortName: "logcol",
    category: VabInfrastructure,
    ports: [5140],
    dependencies: ["proven-socket"],
    softDependencies: ["proven-tls", "proven-audit"],
    capabilities: ["log-collection", "log-aggregation"],
    description: "Verified log collector with proven delivery guarantees and back-pressure handling.",
    rackUnits: 1,
  },
  {
    id: "proven-siem",
    name: "SIEM Engine",
    shortName: "siem",
    category: VabInfrastructure,
    ports: [8443],
    dependencies: ["proven-httpd", "proven-logcollector"],
    softDependencies: ["proven-tls", "proven-audit", "proven-config"],
    capabilities: ["siem", "security-analytics"],
    description: "Verified SIEM with proven correlation rule evaluation and alert prioritisation.",
    rackUnits: 2,
  },
  {
    id: "proven-container",
    name: "Container Runtime",
    shortName: "ctr",
    category: VabInfrastructure,
    ports: [],
    dependencies: ["proven-sandbox"],
    softDependencies: ["proven-config", "proven-audit"],
    capabilities: ["containers", "orchestration"],
    description: "Verified OCI container runtime with proven namespace isolation and cgroup enforcement.",
    rackUnits: 2,
  },
  {
    id: "proven-virt",
    name: "Virtualisation",
    shortName: "virt",
    category: VabInfrastructure,
    ports: [],
    dependencies: [],
    softDependencies: ["proven-config", "proven-audit"],
    capabilities: ["virtualisation", "vm-management"],
    description: "Verified virtualisation manager with proven VM isolation and live migration.",
    rackUnits: 2,
  },
  {
    id: "proven-k9",
    name: "K9 Contractile Engine",
    shortName: "k9",
    category: VabInfrastructure,
    ports: [],
    dependencies: ["proven-config"],
    softDependencies: ["proven-audit"],
    capabilities: ["k9-contractiles", "config-management", "deployment-config"],
    description: "Verified K9 (.k9.ncl) contractile configuration engine. Evaluates Nickel-based deployment contracts, kennel/yard/hunt templates, with proven constraint satisfaction.",
    rackUnits: 1,
  },
]

// ===========================================================================
// Connector Interfaces (6)
// ===========================================================================

/// Connector interfaces — abstract adapters that bridge protocols to backends.
/// These are the "last mile" that connects protocol servers to actual infrastructure.
let connectorComponents: array<vabComponent> = [
  {
    id: "proven-dbconn",
    name: "Database Connector",
    shortName: "dbconn",
    category: VabConnectors,
    ports: [5432],
    dependencies: ["proven-socket"],
    softDependencies: ["proven-tls"],
    capabilities: ["database-connectivity", "connection-pooling"],
    description: "Verified database connector with proven connection pool management and query pipelining.",
    rackUnits: 1,
  },
  {
    id: "proven-cacheconn",
    name: "Cache Connector",
    shortName: "cachec",
    category: VabConnectors,
    ports: [6379],
    dependencies: ["proven-socket"],
    softDependencies: [],
    capabilities: ["cache-connectivity"],
    description: "Verified cache connector with proven serialisation and TTL enforcement.",
    rackUnits: 1,
  },
  {
    id: "proven-storageconn",
    name: "Storage Connector",
    shortName: "storc",
    category: VabConnectors,
    ports: [],
    dependencies: [],
    softDependencies: [],
    capabilities: ["storage-connectivity"],
    description: "Verified storage connector with proven read/write consistency and retry logic.",
    rackUnits: 1,
  },
  {
    id: "proven-queueconn",
    name: "Queue Connector",
    shortName: "queuec",
    category: VabConnectors,
    ports: [5672],
    dependencies: ["proven-socket"],
    softDependencies: [],
    capabilities: ["queue-connectivity", "message-queue"],
    description: "Verified message queue connector with proven delivery semantics (at-least-once, exactly-once).",
    rackUnits: 1,
  },
  {
    id: "proven-authconn",
    name: "Auth Connector",
    shortName: "authc",
    category: VabConnectors,
    ports: [],
    dependencies: [],
    softDependencies: ["proven-tls"],
    capabilities: ["auth-connectivity"],
    description: "Verified auth connector with proven token validation and session management.",
    rackUnits: 1,
  },
  {
    id: "proven-resolverconn",
    name: "Resolver Connector",
    shortName: "rslvc",
    category: VabConnectors,
    ports: [53],
    dependencies: ["proven-socket"],
    softDependencies: [],
    capabilities: ["dns-connectivity"],
    description: "Verified DNS resolver connector with proven caching and negative cache TTLs.",
    rackUnits: 1,
  },
]

// ===========================================================================
// Combined Catalog
// ===========================================================================

/// The full catalog of all 108 proven-servers components, merged from all categories.
/// This is loaded once into vabState.catalog at init time.
let allComponents: array<vabComponent> = Array.flat([
  coreComponents,
  networkComponents,
  dnsComponents,
  webComponents,
  iotComponents,
  emailComponents,
  securityComponents,
  dataComponents,
  applicationComponents,
  infrastructureComponents,
  connectorComponents,
])

/// Get all components for a specific category.
let getByCategory = (catalog: array<vabComponent>, cat: vabCategory): array<vabComponent> =>
  Array.filter(catalog, c => c.category === cat)

/// Find a component by its ID.
let findById = (catalog: array<vabComponent>, id: string): option<vabComponent> =>
  Array.find(catalog, c => c.id === id)

/// Get category display name for the sidebar.
let categoryName = (cat: vabCategory): string =>
  switch cat {
  | VabCore => "Core"
  | VabNetwork => "Network"
  | VabDns => "DNS"
  | VabWeb => "Web"
  | VabIot => "IoT"
  | VabEmail => "Email"
  | VabSecurity => "Security"
  | VabData => "Data"
  | VabApplication => "App"
  | VabInfrastructure => "Infra"
  | VabConnectors => "Conn"
  }

/// Get category icon character for the sidebar (single-char abbreviations).
let categoryIcon = (cat: vabCategory): string =>
  switch cat {
  | VabCore => "C"
  | VabNetwork => "N"
  | VabDns => "D"
  | VabWeb => "W"
  | VabIot => "I"
  | VabEmail => "E"
  | VabSecurity => "S"
  | VabData => "Dt"
  | VabApplication => "A"
  | VabInfrastructure => "If"
  | VabConnectors => "Cn"
  }
