// SPDX-License-Identifier: MPL-2.0

//! Level Architect Tauri commands — level load/save, asset browsing,
//! validation, and LevelConfig export for the IDApTIK level designer.
//!
//! Commands:
//!   - `load_level`: Load a level from a JSON file at the given path.
//!   - `save_level`: Save level JSON data to a file at the given path.
//!   - `export_level_config`: Export level data as a LevelConfig.res source string.
//!   - `browse_level_assets`: List available game assets for placement.
//!   - `validate_level`: Validate level design and return issues.

use std::fs;
use std::path::Path;

use serde_json::json;

/// Load a level from a JSON file at the given path.
///
/// Reads the file, validates it as JSON, and returns the content.
/// Returns an error if the file does not exist or contains invalid JSON.

pub async fn load_level(path: String) -> Result<String, String> {
    let file_path = Path::new(&path);
    if !file_path.exists() {
        return Err(format!("Level file not found: {path}"));
    }

    let content = fs::read_to_string(file_path)
        .map_err(|e| format!("Cannot read level file: {e}"))?;

    // Validate that the content is valid JSON.
    let _parsed: serde_json::Value = serde_json::from_str(&content)
        .map_err(|e| format!("Invalid JSON in level file: {e}"))?;

    Ok(content)
}

/// Save level JSON data to a file at the given path.
///
/// Validates the data as JSON, pretty-prints it, and writes to disk.
/// Creates parent directories if they do not exist.

pub async fn save_level(path: String, data: String) -> Result<String, String> {
    let file_path = Path::new(&path);

    // Validate JSON before writing.
    let parsed: serde_json::Value = serde_json::from_str(&data)
        .map_err(|e| format!("Invalid JSON data: {e}"))?;

    // Ensure parent directory exists.
    if let Some(parent) = file_path.parent() {
        fs::create_dir_all(parent)
            .map_err(|e| format!("Cannot create directory: {e}"))?;
    }

    let pretty = serde_json::to_string_pretty(&parsed)
        .map_err(|e| format!("Serialisation error: {e}"))?;

    fs::write(file_path, &pretty)
        .map_err(|e| format!("Cannot write level file: {e}"))?;

    let result = json!({
        "saved": true,
        "path": path,
        "bytes": pretty.len(),
    });
    serde_json::to_string(&result)
        .map_err(|e| format!("Serialisation error: {e}"))
}

/// Export level data as a LevelConfig.res source file string.
///
/// Takes the level JSON and generates a ReScript module definition
/// that can be pasted into the IDApTIK game source. Currently produces
/// a stub template; future versions will fully translate entities,
/// patrols, and defence flags into typed ReScript records.

pub async fn export_level_config(data: String) -> Result<String, String> {
    let parsed: serde_json::Value = serde_json::from_str(&data)
        .map_err(|e| format!("Invalid JSON data: {e}"))?;

    let level_name = parsed.get("levelName")
        .and_then(|v| v.as_str())
        .unwrap_or("Untitled");

    let grid_width = parsed.get("gridWidth")
        .and_then(|v| v.as_i64())
        .unwrap_or(20);

    let grid_height = parsed.get("gridHeight")
        .and_then(|v| v.as_i64())
        .unwrap_or(15);

    let entity_count = parsed.get("entities")
        .and_then(|v| v.as_array())
        .map(|a| a.len())
        .unwrap_or(0);

    let patrol_count = parsed.get("patrols")
        .and_then(|v| v.as_array())
        .map(|a| a.len())
        .unwrap_or(0);

    let config_source = format!(
        r#"// SPDX-License-Identifier: MPL-2.0
// Auto-generated by PanLL Level Architect

/// Level configuration for "{level_name}"
let config = {{
  levelName: "{level_name}",
  gridWidth: {grid_width},
  gridHeight: {grid_height},
  entityCount: {entity_count},
  patrolCount: {patrol_count},
}}
"#
    );

    let result = json!({
        "source": config_source,
        "levelName": level_name,
        "entityCount": entity_count,
        "patrolCount": patrol_count,
    });
    serde_json::to_string(&result)
        .map_err(|e| format!("Serialisation error: {e}"))
}

/// Browse available game assets for level placement.
///
/// Returns a JSON array of assets grouped by category (devices, guards,
/// collectables, decorations, triggers). Currently returns stub data
/// representing sample IDApTIK game assets.

pub async fn browse_level_assets() -> Result<String, String> {
    let result = json!({
        "assets": [
            {
                "id": "asset-router",
                "name": "Network Router",
                "category": "devices",
                "thumbnail": "assets/devices/router.png",
                "entityKind": "EntityDevice"
            },
            {
                "id": "asset-server",
                "name": "Server Rack",
                "category": "devices",
                "thumbnail": "assets/devices/server.png",
                "entityKind": "EntityDevice"
            },
            {
                "id": "asset-guard-basic",
                "name": "Security Guard",
                "category": "guards",
                "thumbnail": "assets/guards/basic.png",
                "entityKind": "EntityGuard"
            },
            {
                "id": "asset-guard-admin",
                "name": "Admin Sentry",
                "category": "guards",
                "thumbnail": "assets/guards/admin.png",
                "entityKind": "EntityGuard"
            },
            {
                "id": "asset-spawn",
                "name": "Player Spawn",
                "category": "triggers",
                "thumbnail": "assets/triggers/spawn.png",
                "entityKind": "EntitySpawnPoint"
            },
            {
                "id": "asset-key-card",
                "name": "Key Card",
                "category": "collectables",
                "thumbnail": "assets/collectables/keycard.png",
                "entityKind": "EntityCollectable"
            },
            {
                "id": "asset-companion-bot",
                "name": "Companion Bot",
                "category": "companions",
                "thumbnail": "assets/companions/bot.png",
                "entityKind": "EntityCompanion"
            },
            {
                "id": "asset-plant",
                "name": "Office Plant",
                "category": "decorations",
                "thumbnail": "assets/decorations/plant.png",
                "entityKind": "EntityDecoration"
            },
            {
                "id": "asset-alarm",
                "name": "Alarm Trigger",
                "category": "triggers",
                "thumbnail": "assets/triggers/alarm.png",
                "entityKind": "EntityTrigger"
            }
        ]
    });
    serde_json::to_string(&result)
        .map_err(|e| format!("Serialisation error: {e}"))
}

/// Validate the current level design and return any issues.
///
/// Checks for common problems: missing spawn points, unreachable areas,
/// overlapping entities, missing patrol waypoints, and empty defence flags.
/// Takes the level JSON data as input and returns a JSON object with a
/// `valid` boolean and an `issues` array.

pub async fn validate_level(data: String) -> Result<String, String> {
    let parsed: serde_json::Value = serde_json::from_str(&data)
        .map_err(|e| format!("Invalid JSON data: {e}"))?;

    let mut issues: Vec<serde_json::Value> = Vec::new();

    // Check for entities array.
    let entities = parsed.get("entities")
        .and_then(|v| v.as_array());

    match entities {
        None => {
            issues.push(json!({
                "severity": "error",
                "message": "Level has no entities array",
                "entityId": null,
                "gridX": null,
                "gridY": null,
            }));
        }
        Some(ents) => {
            if ents.is_empty() {
                issues.push(json!({
                    "severity": "warning",
                    "message": "Level has no entities placed",
                    "entityId": null,
                    "gridX": null,
                    "gridY": null,
                }));
            }

            // Check for at least one spawn point.
            let has_spawn = ents.iter().any(|e| {
                e.get("kind").and_then(|k| k.as_str()) == Some("EntitySpawnPoint")
            });
            if !has_spawn {
                issues.push(json!({
                    "severity": "error",
                    "message": "No player spawn point found — level requires at least one",
                    "entityId": null,
                    "gridX": null,
                    "gridY": null,
                }));
            }

            // Check for overlapping entities (same grid position).
            let mut positions: std::collections::HashMap<(i64, i64), Vec<String>> =
                std::collections::HashMap::new();
            for entity in ents {
                let x = entity.get("gridX").and_then(|v| v.as_i64()).unwrap_or(-1);
                let y = entity.get("gridY").and_then(|v| v.as_i64()).unwrap_or(-1);
                let id = entity.get("id").and_then(|v| v.as_str()).unwrap_or("?").to_string();
                positions.entry((x, y)).or_default().push(id);
            }
            for ((x, y), ids) in &positions {
                if ids.len() > 1 {
                    issues.push(json!({
                        "severity": "warning",
                        "message": format!("Overlapping entities at ({}, {}): {}", x, y, ids.join(", ")),
                        "entityId": null,
                        "gridX": x,
                        "gridY": y,
                    }));
                }
            }
        }
    }

    // Check for patrols referencing non-existent guards.
    if let Some(patrols) = parsed.get("patrols").and_then(|v| v.as_array()) {
        let entity_ids: std::collections::HashSet<String> = entities
            .unwrap_or(&Vec::new())
            .iter()
            .filter_map(|e| e.get("id").and_then(|v| v.as_str()).map(String::from))
            .collect();

        for patrol in patrols {
            if let Some(guard_id) = patrol.get("guardId").and_then(|v| v.as_str()) {
                if !entity_ids.contains(guard_id) {
                    issues.push(json!({
                        "severity": "error",
                        "message": format!("Patrol references non-existent guard: {}", guard_id),
                        "entityId": guard_id,
                        "gridX": null,
                        "gridY": null,
                    }));
                }
            }

            // Check for empty waypoints.
            if let Some(waypoints) = patrol.get("waypoints").and_then(|v| v.as_array()) {
                if waypoints.len() < 2 {
                    let gid = patrol.get("guardId").and_then(|v| v.as_str()).unwrap_or("?");
                    issues.push(json!({
                        "severity": "warning",
                        "message": format!("Patrol for {} has fewer than 2 waypoints", gid),
                        "entityId": gid,
                        "gridX": null,
                        "gridY": null,
                    }));
                }
            }
        }
    }

    let valid = !issues.iter().any(|i| {
        i.get("severity").and_then(|s| s.as_str()) == Some("error")
    });

    let result = json!({
        "valid": valid,
        "issueCount": issues.len(),
        "issues": issues,
    });
    serde_json::to_string(&result)
        .map_err(|e| format!("Serialisation error: {e}"))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Helper: create a tokio runtime for async command tests.
    fn rt() -> tokio::runtime::Runtime {
        tokio::runtime::Builder::new_current_thread()
            .enable_all()
            .build()
            .expect("Failed to create tokio runtime for tests")
    }

    #[test]
    fn test_load_level_not_found() {
        rt().block_on(async {
            let result = load_level("/tmp/panll/nonexistent-level.json".to_string()).await;
            assert!(result.is_err());
            assert!(result.unwrap_err().contains("not found"));
        });
    }

    #[test]
    fn test_save_and_load_level() {
        rt().block_on(async {
            let level_data = json!({
                "levelName": "Test Level",
                "gridWidth": 20,
                "gridHeight": 15,
                "entities": [],
                "patrols": []
            });
            let data_str = serde_json::to_string(&level_data).unwrap();
            let path = "/tmp/panll/test-levels/save-load-test.json".to_string();

            // Save.
            let save_result = save_level(path.clone(), data_str).await;
            assert!(save_result.is_ok());
            let save_json: serde_json::Value =
                serde_json::from_str(&save_result.unwrap()).unwrap();
            assert_eq!(save_json["saved"], true);

            // Load.
            let load_result = load_level(path.clone()).await;
            assert!(load_result.is_ok());
            let loaded: serde_json::Value =
                serde_json::from_str(&load_result.unwrap()).unwrap();
            assert_eq!(loaded["levelName"], "Test Level");
            assert_eq!(loaded["gridWidth"], 20);

            // Cleanup.
            let _ = std::fs::remove_file(&path);
        });
    }

    #[test]
    fn test_save_level_invalid_json() {
        rt().block_on(async {
            let result = save_level(
                "/tmp/panll/bad.json".to_string(),
                "not valid json {{{".to_string(),
            ).await;
            assert!(result.is_err());
            assert!(result.unwrap_err().contains("Invalid JSON"));
        });
    }

    #[test]
    fn test_export_level_config() {
        rt().block_on(async {
            let level_data = json!({
                "levelName": "Firewall Breach",
                "gridWidth": 30,
                "gridHeight": 20,
                "entities": [
                    {"id": "e1", "kind": "EntityDevice"},
                    {"id": "e2", "kind": "EntityGuard"}
                ],
                "patrols": [
                    {"guardId": "e2", "waypoints": []}
                ]
            });

            let result = export_level_config(serde_json::to_string(&level_data).unwrap()).await;
            assert!(result.is_ok());
            let json: serde_json::Value = serde_json::from_str(&result.unwrap()).unwrap();
            assert_eq!(json["levelName"], "Firewall Breach");
            assert_eq!(json["entityCount"], 2);
            assert_eq!(json["patrolCount"], 1);
            let source = json["source"].as_str().unwrap();
            assert!(source.contains("Firewall Breach"));
            assert!(source.contains("gridWidth: 30"));
        });
    }

    #[test]
    fn test_browse_level_assets() {
        rt().block_on(async {
            let result = browse_level_assets().await;
            assert!(result.is_ok());
            let json: serde_json::Value = serde_json::from_str(&result.unwrap()).unwrap();
            let assets = json["assets"].as_array().unwrap();
            assert!(assets.len() >= 8, "Should have at least 8 stub assets");
            // Verify asset fields.
            let first = &assets[0];
            assert!(first["id"].as_str().is_some());
            assert!(first["name"].as_str().is_some());
            assert!(first["category"].as_str().is_some());
            assert!(first["entityKind"].as_str().is_some());
        });
    }

    #[test]
    fn test_validate_level_valid() {
        rt().block_on(async {
            let level_data = json!({
                "entities": [
                    {"id": "spawn-1", "kind": "EntitySpawnPoint", "gridX": 0, "gridY": 0},
                    {"id": "guard-1", "kind": "EntityGuard", "gridX": 5, "gridY": 5}
                ],
                "patrols": [
                    {"guardId": "guard-1", "waypoints": [
                        {"x": 5, "y": 5, "pauseDuration": 1.0},
                        {"x": 10, "y": 5, "pauseDuration": 1.0}
                    ]}
                ]
            });

            let result = validate_level(serde_json::to_string(&level_data).unwrap()).await;
            assert!(result.is_ok());
            let json: serde_json::Value = serde_json::from_str(&result.unwrap()).unwrap();
            assert_eq!(json["valid"], true);
            assert_eq!(json["issueCount"], 0);
        });
    }

    #[test]
    fn test_validate_level_missing_spawn() {
        rt().block_on(async {
            let level_data = json!({
                "entities": [
                    {"id": "guard-1", "kind": "EntityGuard", "gridX": 5, "gridY": 5}
                ],
                "patrols": []
            });

            let result = validate_level(serde_json::to_string(&level_data).unwrap()).await;
            assert!(result.is_ok());
            let json: serde_json::Value = serde_json::from_str(&result.unwrap()).unwrap();
            assert_eq!(json["valid"], false);
            let issues = json["issues"].as_array().unwrap();
            assert!(issues.iter().any(|i| {
                i["message"].as_str().unwrap().contains("spawn point")
            }));
        });
    }

    #[test]
    fn test_validate_level_overlapping_entities() {
        rt().block_on(async {
            let level_data = json!({
                "entities": [
                    {"id": "spawn-1", "kind": "EntitySpawnPoint", "gridX": 3, "gridY": 3},
                    {"id": "device-1", "kind": "EntityDevice", "gridX": 3, "gridY": 3}
                ],
                "patrols": []
            });

            let result = validate_level(serde_json::to_string(&level_data).unwrap()).await;
            assert!(result.is_ok());
            let json: serde_json::Value = serde_json::from_str(&result.unwrap()).unwrap();
            let issues = json["issues"].as_array().unwrap();
            assert!(issues.iter().any(|i| {
                i["message"].as_str().unwrap().contains("Overlapping")
            }));
        });
    }

    #[test]
    fn test_validate_level_invalid_json() {
        rt().block_on(async {
            let result = validate_level("not json".to_string()).await;
            assert!(result.is_err());
            assert!(result.unwrap_err().contains("Invalid JSON"));
        });
    }

    #[test]
    fn test_validate_level_orphan_patrol() {
        rt().block_on(async {
            let level_data = json!({
                "entities": [
                    {"id": "spawn-1", "kind": "EntitySpawnPoint", "gridX": 0, "gridY": 0}
                ],
                "patrols": [
                    {"guardId": "ghost-guard", "waypoints": [
                        {"x": 1, "y": 1, "pauseDuration": 1.0},
                        {"x": 2, "y": 2, "pauseDuration": 1.0}
                    ]}
                ]
            });

            let result = validate_level(serde_json::to_string(&level_data).unwrap()).await;
            assert!(result.is_ok());
            let json: serde_json::Value = serde_json::from_str(&result.unwrap()).unwrap();
            assert_eq!(json["valid"], false);
            let issues = json["issues"].as_array().unwrap();
            assert!(issues.iter().any(|i| {
                i["message"].as_str().unwrap().contains("non-existent guard")
            }));
        });
    }
}
