// SPDX-License-Identifier: PMPL-1.0-or-later

/// PanLL Update Engine — The state transition kernel.
///
/// This module implements the "Update" function of The Elm Architecture (TEA).
/// It is responsible for taking the current `model` and an incoming `msg`,
/// and producing a new version of the model along with any required 
/// side-effect commands (`Tea_Cmd`).
///
/// DESIGN: PURE & DETERMINISTIC. No side effects occur within these functions.

open Model
open Msg

/// STATE TRANSITION: Pane-L (Logical Constraints)
/// Manages the set of formal constraints applied to the current inference session.
let updatePaneL = (model: model, msg: paneLMsg): model => {
  let paneL = model.paneL
  let newPaneL = switch msg {
  | AddConstraint(c) => {...paneL, constraints: Array.concat(paneL.constraints, [c])}
  | ToggleConstraint(id) => {
      // Functional update: flip the 'active' status of the targeted constraint.
      ...paneL,
      constraints: Array.map(paneL.constraints, c =>
        c.id === id ? {...c, active: !c.active} : c
      ),
    }
  | UpdateEditorContent(content) => {...paneL, editorContent: content}
  | _ => paneL
  }
  {...model, paneL: newPaneL}
}

/// STATE TRANSITION: Pane-N (Neural/Inference Tokens)
/// Handles the real-time stream of tokens generated by the LLM.
let updatePaneN = (model: model, msg: paneNMsg): model => {
  let paneN = model.paneN
  let newPaneN = switch msg {
  | ReceiveToken(token) => {...paneN, tokens: Array.concat(paneN.tokens, [token])}
  | SetInferenceActive(active) => {...paneN, inferenceActive: active}
  | UpdateMonologue(text) => {...paneN, monologue: text}
  | _ => paneN
  }
  {...model, paneN: newPaneN}
}

/// STATE TRANSITION: Pane-W (World / Event Chains)
/// Orchestrates the visualization of complex temporal event chains and 
/// security study reports.
let updatePaneW = (model: model, msg: paneWMsg): model => {
  let paneW = model.paneW
  let newPaneW = switch msg {
  | ImportEventChain =>
    // PARSING: Transforms raw JSON input into a structured event chain.
    switch EventChain.parse(paneW.eventChainInput) {
    | Ok(payload) => {
        ...paneW,
        eventChain: payload.events,
        eventChainSummary: payload.summary,
        eventChainError: None,
      }
    | Error(err) => {...paneW, eventChainError: Some(err)}
    }
  | _ => paneW
  }
  {...model, paneW: newPaneW}
}

/// ORCHESTRATOR: The main entry point for state updates.
let update = (model: model, msg: msg): (model, Tea_Cmd.t<msg>) => {
  // ... [Internal routing logic]
  (model, Tea_Cmd.none)
}
