// SPDX-License-Identifier: PMPL-1.0-or-later

/// PanLL Update Engine — The state transition kernel.
///
/// This module implements the "Update" function of The Elm Architecture (TEA).
/// It is responsible for taking the current `model` and an incoming `msg`,
/// and producing a new version of the model along with any required
/// side-effect commands (`Tea_Cmd`).
///
/// Architecture:
///   1. Domain sub-updaters handle each message category (PaneL, PaneN, PaneW, etc.)
///   2. The main `update()` orchestrator routes messages to sub-updaters
///   3. Contractiles post-processing evaluates cognitive governance contracts
///      after every state-modifying update
///
/// DESIGN: Sub-updaters are pure — commands represent deferred side effects.
/// The only imperative call is `Storage.save()` in the SaveState handler.

open Model
open Msg

// ===========================================================================
// Pane Sub-Updaters
// ===========================================================================

/// STATE TRANSITION: Pane-L (Logical Constraints)
/// Manages the set of formal constraints applied to the current inference session.
/// Handles all 6 paneLMsg variants: add, remove, toggle, pin, edit, set active.
let updatePaneL = (model: model, msg: paneLMsg): model => {
  let paneL = model.paneL
  let newPaneL = switch msg {
  | AddConstraint(c) => {...paneL, constraints: Array.concat(paneL.constraints, [c])}
  | RemoveConstraint(id) => {
      ...paneL,
      constraints: Array.filter(paneL.constraints, c => c.id !== id),
    }
  | ToggleConstraint(id) => {
      // Functional update: flip the 'active' status of the targeted constraint.
      ...paneL,
      constraints: Array.map(paneL.constraints, c =>
        c.id === id ? {...c, active: !c.active} : c
      ),
    }
  | PinConstraint(id) => {
      // Toggle the 'pinned' flag — pinned constraints survive session resets.
      ...paneL,
      constraints: Array.map(paneL.constraints, c =>
        c.id === id ? {...c, pinned: !c.pinned} : c
      ),
    }
  | UpdateEditorContent(content) => {...paneL, editorContent: content}
  | SetActiveConstraint(id) => {...paneL, activeConstraintId: id}
  }
  {...model, paneL: newPaneL}
}

/// STATE TRANSITION: Pane-N (Neural/Inference Tokens)
/// Handles the real-time stream of tokens generated by the LLM.
/// All 5 paneNMsg variants: receive, clear, toggle active, monologue, agency.
let updatePaneN = (model: model, msg: paneNMsg): model => {
  let paneN = model.paneN
  let newPaneN = switch msg {
  | ReceiveToken(token) => {...paneN, tokens: Array.concat(paneN.tokens, [token])}
  | ClearTokens => {...paneN, tokens: []}
  | SetInferenceActive(active) => {...paneN, inferenceActive: active}
  | UpdateMonologue(text) => {...paneN, monologue: text}
  | UpdateAgency(agency) => {...paneN, agency}
  }
  {...model, paneN: newPaneN}
}

// ===========================================================================
// Pane-W Helpers
// ===========================================================================

/// Parse panic-attacker capability JSON response.
/// Extracts mode, binary path, and status detail from the backend probe result.
/// Expected JSON shape: { "mode": "full"|"fallback"|"unavailable",
///   "binary_path": "/path/to/binary", "status_detail": "..." }
let parsePanicAttackerCapability = (json: string): (string, option<string>, option<string>) => {
  try {
    let parsed = JSON.parseExn(json)
    switch JSON.Classify.classify(parsed) {
    | Object(obj) => {
        let getStr = (key: string): option<string> =>
          switch Dict.get(obj, key) {
          | Some(v) =>
            switch JSON.Classify.classify(v) {
            | String(s) => Some(s)
            | _ => None
            }
          | None => None
          }
        let mode = switch getStr("mode") {
        | Some(m) => m
        | None => "unknown"
        }
        (mode, getStr("binary_path"), getStr("status_detail"))
      }
    | _ => ("unknown", None, None)
    }
  } catch {
  | _ => ("unknown", None, None)
  }
}

// ===========================================================================
// Pane-W Sub-Updater
// ===========================================================================

/// STATE TRANSITION: Pane-W (World / Event Chains)
/// Orchestrates the visualization of complex temporal event chains,
/// security study reports, and panic-attacker integration.
///
/// Returns `(model, Tea_Cmd.t<msg>)` because several handlers issue Tauri
/// commands (file dialogs, backend imports, security ambush runs).
let updatePaneW = (model: model, msg: paneWMsg): (model, Tea_Cmd.t<msg>) => {
  let paneW = model.paneW
  switch msg {
  // --- Content & view toggles (pure state) ---
  | UpdateContent(text) =>
    ({...model, paneW: {...paneW, content: text}}, Tea_Cmd.none)
  | ToggleTopologyView =>
    ({...model, paneW: {...paneW, topologyView: !paneW.topologyView}}, Tea_Cmd.none)
  | SetValidatedOutput(text) =>
    ({...model, paneW: {...paneW, lastValidatedOutput: text}}, Tea_Cmd.none)
  | UpdateEventChainInput(text) =>
    ({...model, paneW: {...paneW, eventChainInput: text}}, Tea_Cmd.none)
  | ClearEventChain => (
      {...model, paneW: {
        ...paneW,
        eventChain: [],
        eventChainSummary: None,
        eventChainTimeline: None,
        eventChainInput: "",
        eventChainError: None,
      }},
      Tea_Cmd.none,
    )

  // --- Inline event chain parsing from text input ---
  | ImportEventChain =>
    // PARSING: Transforms raw JSON input into a structured event chain.
    switch EventChain.parse(paneW.eventChainInput) {
    | Ok(payload) => (
        {...model, paneW: {
          ...paneW,
          eventChain: payload.events,
          eventChainSummary: payload.summary,
          eventChainTimeline: payload.timeline,
          eventChainError: None,
        }},
        Tea_Cmd.none,
      )
    | Error(err) => ({...model, paneW: {...paneW, eventChainError: Some(err)}}, Tea_Cmd.none)
    }

  // --- File import commands (issue Tauri commands, await result) ---
  | ImportEventChainFile => (
      model,
      TauriCmd.openEventChainFile(result => PaneW(EventChainFileLoaded(result))),
    )
  | ImportPanicAttackerReportFile => (
      model,
      TauriCmd.openPanicAttackerReportFile(result =>
        PaneW(PanicAttackerReportPathLoaded(result))
      ),
    )
  | ImportLatestPanicAttacker => (
      model,
      TauriCmd.importLatestPanicAttackerReport(result =>
        PaneW(PanicAttackerImportLoaded(result))
      ),
    )
  | CheckPanicAttackerCapability => (
      model,
      TauriCmd.getPanicAttackerCapability(result =>
        PaneW(PanicAttackerCapabilityLoaded(result))
      ),
    )

  // --- File import results (parse response data) ---
  | EventChainFileLoaded(result) =>
    switch result {
    | Ok(contents) =>
      switch EventChain.parse(contents) {
      | Ok(payload) => (
          {...model, paneW: {
            ...paneW,
            eventChain: payload.events,
            eventChainSummary: payload.summary,
            eventChainTimeline: payload.timeline,
            eventChainError: None,
          }},
          Tea_Cmd.none,
        )
      | Error(err) => ({...model, paneW: {...paneW, eventChainError: Some(err)}}, Tea_Cmd.none)
      }
    | Error(err) => ({...model, paneW: {...paneW, eventChainError: Some(err)}}, Tea_Cmd.none)
    }
  | PanicAttackerReportPathLoaded(result) =>
    // Two-phase import: first get the file path, then ask backend to convert.
    switch result {
    | Ok(path) => (
        model,
        TauriCmd.importPanicAttackerReport(path, result =>
          PaneW(PanicAttackerImportLoaded(result))
        ),
      )
    | Error(err) => ({...model, paneW: {...paneW, eventChainError: Some(err)}}, Tea_Cmd.none)
    }
  | PanicAttackerImportLoaded(result) =>
    switch result {
    | Ok(json) =>
      switch EventChain.parse(json) {
      | Ok(payload) => (
          {...model, paneW: {
            ...paneW,
            eventChain: payload.events,
            eventChainSummary: payload.summary,
            eventChainTimeline: payload.timeline,
            eventChainError: None,
          }},
          Tea_Cmd.none,
        )
      | Error(err) => ({...model, paneW: {...paneW, eventChainError: Some(err)}}, Tea_Cmd.none)
      }
    | Error(err) => ({...model, paneW: {...paneW, eventChainError: Some(err)}}, Tea_Cmd.none)
    }
  | PanicAttackerCapabilityLoaded(result) =>
    switch result {
    | Ok(json) => {
        let (mode, binary, detail) = parsePanicAttackerCapability(json)
        (
          {...model, paneW: {
            ...paneW,
            panicAttackerMode: mode,
            panicAttackerBinary: binary,
            panicAttackerStatusDetail: detail,
          }},
          Tea_Cmd.none,
        )
      }
    | Error(err) => (
        {...model, paneW: {
          ...paneW,
          panicAttackerMode: "unavailable",
          panicAttackerStatusDetail: Some(err),
        }},
        Tea_Cmd.none,
      )
    }

  // --- Security menu interactions (pure state) ---
  | ToggleSecurityTools =>
    ({...model, paneW: {...paneW, securityMenuExpanded: !paneW.securityMenuExpanded}}, Tea_Cmd.none)
  | OpenSecurityDialog(tool) =>
    ({...model, paneW: {...paneW, securityDialogOpen: true, securityDialogTool: Some(tool)}}, Tea_Cmd.none)
  | CloseSecurityDialog =>
    ({...model, paneW: {...paneW, securityDialogOpen: false, securityDialogTool: None}}, Tea_Cmd.none)
  | ToggleSecurityStudyView =>
    ({...model, paneW: {...paneW, securityViewActive: !paneW.securityViewActive}}, Tea_Cmd.none)
  | SetSecurityTarget(t) =>
    ({...model, paneW: {...paneW, securityTarget: t}}, Tea_Cmd.none)
  | SetSecurityTimeline(t) =>
    ({...model, paneW: {...paneW, securityTimeline: t}}, Tea_Cmd.none)
  | SetSecurityAxes(a) =>
    ({...model, paneW: {...paneW, securityAxes: a}}, Tea_Cmd.none)
  | SetSecurityIntensity(i) =>
    ({...model, paneW: {...paneW, securityIntensity: i}}, Tea_Cmd.none)
  | SetSecurityDuration(d) =>
    ({...model, paneW: {...paneW, securityDuration: d}}, Tea_Cmd.none)

  // --- Security command lifecycle ---
  | LoadSecurityTimelineFile => (
      model,
      TauriCmd.openSecurityTimelineFile(result =>
        PaneW(SecurityTimelineFileLoaded(result))
      ),
    )
  | SecurityTimelineFileLoaded(result) =>
    switch result {
    | Ok(path) => ({...model, paneW: {...paneW, securityTimeline: path}}, Tea_Cmd.none)
    | Error(err) => ({...model, paneW: {...paneW, securityError: Some(err)}}, Tea_Cmd.none)
    }
  | LaunchSecurityAmbush => {
      // Gather options from current Pane-W state for the ambush command.
      let timeline = if paneW.securityTimeline !== "" {
        Some(paneW.securityTimeline)
      } else {
        None
      }
      let axes = if paneW.securityAxes !== "" {
        Some(paneW.securityAxes)
      } else {
        None
      }
      let durationSecs = switch Int.fromString(paneW.securityDuration) {
      | Some(d) => d
      | None => 30
      }
      (
        {...model, paneW: {...paneW, securityStatus: Some("Running..."), securityError: None}},
        TauriCmd.runPanicAttackAmbush(
          paneW.securityTarget,
          timeline,
          axes,
          paneW.securityIntensity,
          durationSecs,
          result => PaneW(SecurityAmbushResult(result)),
        ),
      )
    }
  | SecurityAmbushResult(result) =>
    switch result {
    | Ok(json) =>
      switch EventChain.parse(json) {
      | Ok(payload) => (
          {...model, paneW: {
            ...paneW,
            eventChain: payload.events,
            eventChainSummary: payload.summary,
            eventChainTimeline: payload.timeline,
            eventChainError: None,
            securityStatus: Some("Complete"),
            securityError: None,
          }},
          Tea_Cmd.none,
        )
      | Error(err) => (
          {...model, paneW: {...paneW, securityStatus: Some("Failed"), securityError: Some(err)}},
          Tea_Cmd.none,
        )
      }
    | Error(err) => (
        {...model, paneW: {...paneW, securityStatus: Some("Failed"), securityError: Some(err)}},
        Tea_Cmd.none,
      )
    }
  }
}

// ===========================================================================
// VeriSimDB Parsers
// ===========================================================================

/// Parse proof obligations from a VQL-DT JSON response.
/// VQL-DT queries return a `proof_certificate` object with an array of proofs.
/// Each proof has type, contract, verified status, and hash fields.
let parseProofObligations = (json: string): array<proofObligation> => {
  try {
    let parsed = JSON.parseExn(json)
    // Look for proof_certificate.proofs in the response
    switch JSON.Classify.classify(parsed) {
    | Object(obj) =>
      switch Dict.get(obj, "proof_certificate") {
      | Some(cert) =>
        switch JSON.Classify.classify(cert) {
        | Object(certObj) =>
          switch Dict.get(certObj, "proofs") {
          | Some(proofsVal) =>
            switch JSON.Classify.classify(proofsVal) {
            | Array(proofArr) =>
              proofArr->Array.filterMap(p =>
                switch JSON.Classify.classify(p) {
                | Object(proofObj) => {
                    let getStr = (key: string): string =>
                      switch Dict.get(proofObj, key) {
                      | Some(v) =>
                        switch JSON.Classify.classify(v) {
                        | String(s) => s
                        | _ => ""
                        }
                      | None => ""
                      }
                    let proofType = getStr("type")
                    let status = if getStr("verified") == "true" { "verified" } else { "pending" }
                    Some({
                      proofType,
                      contractName: getStr("contract"),
                      status,
                      proofHash: getStr("hash"),
                    })
                  }
                | _ => None
                }
              )
            | _ => []
            }
          | None => []
          }
        | _ => []
        }
      | None => []
      }
    | _ => []
    }
  } catch {
  | _ => []
  }
}

/// Parse drift scores from a drift status JSON response.
/// Returns structured drift scores for all 8 octad modalities.
let parseDriftScores = (json: string): option<driftScores> => {
  try {
    let parsed = JSON.parseExn(json)
    switch JSON.Classify.classify(parsed) {
    | Object(obj) => {
        let getFloat = (key: string): float =>
          switch Dict.get(obj, key) {
          | Some(v) =>
            switch JSON.Classify.classify(v) {
            | Number(n) => n
            | _ => 0.0
            }
          | None => 0.0
          }
        Some({
          graph: getFloat("graph"),
          vector: getFloat("vector"),
          tensor: getFloat("tensor"),
          semantic: getFloat("semantic"),
          document: getFloat("document"),
          temporal: getFloat("temporal"),
          provenance: getFloat("provenance"),
          spatial: getFloat("spatial"),
        })
      }
    | _ => None
    }
  } catch {
  | _ => None
  }
}

/// Parse a telemetry snapshot from the VeriSimDB reporter JSON response.
/// Extracts aggregate-only product development metrics — no PII or query content.
let parseTelemetrySnapshot = (json: string): option<telemetrySnapshot> => {
  try {
    let parsed = JSON.parseExn(json)
    switch JSON.Classify.classify(parsed) {
    | Object(obj) => {
        // Helper to safely extract nested fields.
        let getObj = (key: string): option<Dict.t<JSON.t>> =>
          switch Dict.get(obj, key) {
          | Some(v) =>
            switch JSON.Classify.classify(v) {
            | Object(o) => Some(o)
            | _ => None
            }
          | None => None
          }

        let getFloat = (o: Dict.t<JSON.t>, key: string): float =>
          switch Dict.get(o, key) {
          | Some(v) =>
            switch JSON.Classify.classify(v) {
            | Number(n) => n
            | _ => 0.0
            }
          | None => 0.0
          }

        let getInt = (o: Dict.t<JSON.t>, key: string): int =>
          switch Dict.get(o, key) {
          | Some(v) =>
            switch JSON.Classify.classify(v) {
            | Number(n) => Float.toInt(n)
            | _ => 0
            }
          | None => 0
          }

        let getString = (o: Dict.t<JSON.t>, key: string): string =>
          switch Dict.get(o, key) {
          | Some(v) =>
            switch JSON.Classify.classify(v) {
            | String(s) => s
            | _ => ""
            }
          | None => ""
          }

        // Parse modality heatmap (percentages)
        let modalityHeatmap = switch getObj("modality_heatmap") {
        | Some(heatmap) =>
          switch Dict.get(heatmap, "percentages") {
          | Some(v) =>
            switch JSON.Classify.classify(v) {
            | Object(pcts) =>
              Dict.keysToArray(pcts)
              ->Array.map(key => (key, getFloat(pcts, key)))
            | _ => []
            }
          | None => []
          }
        | None => []
        }

        // Parse query patterns
        let queryPatterns = switch getObj("query_patterns") {
        | Some(patterns) =>
          switch Dict.get(patterns, "by_type") {
          | Some(v) =>
            switch JSON.Classify.classify(v) {
            | Object(types) =>
              Dict.keysToArray(types)
              ->Array.map(key => (key, getInt(types, key)))
            | _ => []
            }
          | None => []
          }
        | None => []
        }

        // Parse proof type usage
        let proofTypeUsage = switch getObj("proof_types") {
        | Some(proofs) =>
          switch Dict.get(proofs, "by_type") {
          | Some(v) =>
            switch JSON.Classify.classify(v) {
            | Object(types) =>
              Dict.keysToArray(types)
              ->Array.map(key => (key, getInt(types, key)))
            | _ => []
            }
          | None => []
          }
        | None => []
        }

        // Extract scalar metrics
        let avgDuration = switch getObj("performance") {
        | Some(perf) => getFloat(perf, "avg_duration_ms")
        | None => 0.0
        }

        let driftCount = switch getObj("drift") {
        | Some(drift) => getInt(drift, "drift_detected_count")
        | None => 0
        }

        let successRate = switch getObj("drift") {
        | Some(drift) => getFloat(drift, "normalise_success_rate")
        | None => 0.0
        }

        let entityCount = switch getObj("entities") {
        | Some(entities) => getInt(entities, "created")
        | None => 0
        }

        let generatedAt = switch getObj("meta") {
        | Some(meta) => getString(meta, "generated_at")
        | None => ""
        }

        let privacyNotice = switch getObj("meta") {
        | Some(meta) => getString(meta, "privacy_notice")
        | None => "Aggregate metrics only. No query content or PII."
        }

        Some({
          generatedAt,
          modalityHeatmap,
          queryPatterns,
          avgQueryDurationMs: avgDuration,
          driftDetectedCount: driftCount,
          normaliseSuccessRate: successRate,
          proofTypeUsage,
          entityCount,
          privacyNotice,
        })
      }
    | _ => None
    }
  } catch {
  | _ => None
  }
}

// ===========================================================================
// VeriSimDB Sub-Updater
// ===========================================================================

/// STATE TRANSITION: VeriSimDB (Database Backend)
/// Manages the VeriSimDB connection state, VQL query lifecycle, entity browsing,
/// drift detection status, normalisation, and entity detail. Each message either
/// triggers a Tauri command (side effect) or updates model state from a command
/// result.
let updateVeriSimDB = (model: model, msg: verisimdbMsg): (model, Tea_Cmd.t<msg>) => {
  let db = model.verisimdb
  switch msg {
  | CheckHealth => (
      model,
      TauriCmd.checkVeriSimDBHealth(result => VeriSimDB(HealthResult(result))),
    )
  | HealthResult(result) =>
    switch result {
    | Ok(_json) => ({...model, verisimdb: {...db, connected: true, queryError: None}}, Tea_Cmd.none)
    | Error(err) => ({...model, verisimdb: {...db, connected: false, queryError: Some(err)}}, Tea_Cmd.none)
    }
  | SubmitQuery(query) => (
      {...model, verisimdb: {...db, lastQuery: query, queryResult: None, queryError: None, proofObligations: []}},
      TauriCmd.queryVeriSimDB(query, result => VeriSimDB(QueryResult(result))),
    )
  | UpdateQueryInput(text) => (
      {...model, verisimdb: {...db, lastQuery: text}},
      Tea_Cmd.none,
    )
  | QueryResult(result) =>
    switch result {
    | Ok(json) =>
      // Parse proof obligations from VQL-DT responses
      let proofs = parseProofObligations(json)
      (
        {...model, verisimdb: {...db, queryResult: Some(json), queryError: None, proofObligations: proofs}},
        Tea_Cmd.none,
      )
    | Error(err) => ({...model, verisimdb: {...db, queryResult: None, queryError: Some(err)}}, Tea_Cmd.none)
    }
  | ListEntities => (
      model,
      TauriCmd.listHexads(50, 0, result => VeriSimDB(EntitiesLoaded(result))),
    )
  | EntitiesLoaded(result) =>
    switch result {
    | Ok(_json) => ({...model, verisimdb: {...db, queryError: None}}, Tea_Cmd.none)
    | Error(err) => ({...model, verisimdb: {...db, queryError: Some(err)}}, Tea_Cmd.none)
    }
  | SelectEntity(entityId) => (
      {...model, verisimdb: {...db, selectedEntity: Some(entityId), entityDetail: None}},
      TauriCmd.batch(list{
        TauriCmd.getDrift(entityId, result => VeriSimDB(DriftLoaded(result))),
        TauriCmd.getEntityDetail(entityId, result => VeriSimDB(EntityDetailLoaded(result))),
      }),
    )
  | DriftLoaded(result) =>
    switch result {
    | Ok(json) =>
      let scores = parseDriftScores(json)
      (
        {...model, verisimdb: {...db, driftStatus: Some(json), driftScores: scores, queryError: None}},
        Tea_Cmd.none,
      )
    | Error(err) => (
        {...model, verisimdb: {...db, driftStatus: None, driftScores: None, queryError: Some(err)}},
        Tea_Cmd.none,
      )
    }
  | ToggleDbMenu => (
      {...model, verisimdb: {...db, dbMenuExpanded: !db.dbMenuExpanded}},
      Tea_Cmd.none,
    )
  | ClearQueryResult => (
      {...model, verisimdb: {...db, queryResult: None, queryError: None, proofObligations: []}},
      Tea_Cmd.none,
    )
  | TriggerNormalise(entityId) => (
      {...model, verisimdb: {...db, normalisingEntity: Some(entityId)}},
      TauriCmd.triggerNormalise(entityId, result => VeriSimDB(NormaliseResult(result))),
    )
  | NormaliseResult(result) =>
    switch result {
    | Ok(_json) => (
        {...model, verisimdb: {...db, normalisingEntity: None, queryError: None}},
        // Refresh drift status after normalisation
        switch db.selectedEntity {
        | Some(entityId) =>
          TauriCmd.getDrift(entityId, result => VeriSimDB(DriftLoaded(result)))
        | None => Tea_Cmd.none
        },
      )
    | Error(err) => (
        {...model, verisimdb: {...db, normalisingEntity: None, queryError: Some(err)}},
        Tea_Cmd.none,
      )
    }
  | LoadEntityDetail(entityId) => (
      model,
      TauriCmd.getEntityDetail(entityId, result => VeriSimDB(EntityDetailLoaded(result))),
    )
  | EntityDetailLoaded(result) =>
    switch result {
    | Ok(json) => ({...model, verisimdb: {...db, entityDetail: Some(json), queryError: None}}, Tea_Cmd.none)
    | Error(err) => ({...model, verisimdb: {...db, entityDetail: None, queryError: Some(err)}}, Tea_Cmd.none)
    }
  | FetchTelemetry => (
      model,
      TauriCmd.getTelemetry(result => VeriSimDB(TelemetryLoaded(result))),
    )
  | TelemetryLoaded(result) =>
    switch result {
    | Ok(json) =>
      let snapshot = parseTelemetrySnapshot(json)
      ({...model, verisimdb: {...db, telemetry: snapshot, queryError: None}}, Tea_Cmd.none)
    | Error(err) => ({...model, verisimdb: {...db, telemetry: None, queryError: Some(err)}}, Tea_Cmd.none)
    }
  | ToggleTelemetryPanel => (
      {...model, verisimdb: {...db, telemetryVisible: !db.telemetryVisible}},
      Tea_Cmd.none,
    )
  }
}

// ===========================================================================
// Cognitive Governance Sub-Updaters
// ===========================================================================

/// STATE TRANSITION: Vexometer
/// Tracks operator vexation signals (cancellations, corrections) and manages
/// the anti-inflammatory feedback system. Backend events are recorded via
/// Tauri commands so the Rust VexationTracker can compute the composite index.
let updateVexometer = (model: model, msg: vexometerMsg): (model, Tea_Cmd.t<msg>) => {
  let vex = model.vexometer
  switch msg {
  | RecordCancellation => (
      {...model, vexometer: {...vex, recentCancellations: vex.recentCancellations + 1}},
      TauriCmd.recordVexationEvent("cancellation", _result => NoOp),
    )
  | RecordCorrection => (
      {...model, vexometer: {...vex, recentCorrections: vex.recentCorrections + 1}},
      TauriCmd.recordVexationEvent("correction", _result => NoOp),
    )
  | RequestVexationIndex => (
      model,
      TauriCmd.getVexationIndex(index => Vexometer(UpdateVexationIndex(index))),
    )
  | UpdateVexationIndex(index) => (
      {...model, vexometer: {...vex, index}},
      Tea_Cmd.none,
    )
  | ToggleAntiInflammatory(active) => (
      {...model, vexometer: {...vex, antiInflammatoryActive: active}},
      Tea_Cmd.none,
    )
  | SetInertiaDetected(detected) => (
      {...model, vexometer: {...vex, inertiaDetected: detected}},
      Tea_Cmd.none,
    )
  | ResetVexometer => (
      {...model, vexometer: {
        index: 0.0,
        recentCancellations: 0,
        recentCorrections: 0,
        antiInflammatoryActive: false,
        inertiaDetected: false,
      }},
      TauriCmd.recordVexationEvent("reset", _result => NoOp),
    )
  }
}

/// STATE TRANSITION: Orbital Stability
/// Manages the Binary Star co-orbit stability metrics and drift aura.
/// The aura colour reflects orbit health: "indigo" (stable) or "amber" (decaying).
let updateOrbital = (model: model, msg: orbitalMsg): (model, Tea_Cmd.t<msg>) => {
  let orbital = model.orbital
  switch msg {
  | UpdateStability(value) => {
      // Recalculate drift aura colour when stability changes.
      let colour = if value >= 0.7 { "indigo" } else { "amber" }
      ({...model, orbital: {...orbital, stability: value, driftAuraColour: colour}}, Tea_Cmd.none)
    }
  | UpdateDivergence(value) => (
      {...model, orbital: {...orbital, divergenceLevel: value}},
      Tea_Cmd.none,
    )
  | SetDriftAura(colour) => (
      {...model, orbital: {...orbital, driftAuraColour: colour}},
      Tea_Cmd.none,
    )
  }
}

// ===========================================================================
// View & Feedback Sub-Updaters
// ===========================================================================

/// STATE TRANSITION: View Controls
/// Manages pane visibility, view mode, and information humidity level.
/// ParallaxAlign is a compound action that resets to the canonical three-pane layout.
let updateView = (model: model, msg: viewMsg): (model, Tea_Cmd.t<msg>) => {
  switch msg {
  | TogglePaneL => ({...model, paneLVisible: !model.paneLVisible}, Tea_Cmd.none)
  | TogglePaneN => ({...model, paneNVisible: !model.paneNVisible}, Tea_Cmd.none)
  | TogglePaneW => ({...model, paneWVisible: !model.paneWVisible}, Tea_Cmd.none)
  | ToggleProtocolAnalysis => (
      {...model, protocolAnalysisVisible: !model.protocolAnalysisVisible},
      Tea_Cmd.none,
    )
  | SetViewMode(mode) => ({...model, viewMode: mode}, Tea_Cmd.none)
  | SetHumidity(level) => ({...model, humidity: level}, Tea_Cmd.none)
  | ParallaxAlign => (
      // Synchronous horizontal tiling: show all panes in Standard mode.
      {...model, paneLVisible: true, paneNVisible: true, paneWVisible: true, viewMode: Standard},
      Tea_Cmd.none,
    )
  }
}

/// STATE TRANSITION: Feedback-O-Tron
/// Manages the feedback lifecycle: open dialog, submit to backend, cancel,
/// and handle the asynchronous submission result.
let updateFeedback = (model: model, msg: feedbackMsg): (model, Tea_Cmd.t<msg>) => {
  switch msg {
  | OpenFeedback => ({...model, feedbackPending: Some("")}, Tea_Cmd.none)
  | SubmitFeedback(text) => {
      let reportType = switch model.feedbackReportType {
      | Some(t) => t
      | None => "General"
      }
      (
        model,
        TauriCmd.submitFeedback(
          text,
          model.paneN.monologue,
          model.paneW.content,
          reportType,
          result => Feedback(FeedbackSubmissionResult(result)),
        ),
      )
    }
  | CancelFeedback => ({...model, feedbackPending: None}, Tea_Cmd.none)
  | SetReportType(t) => ({...model, feedbackReportType: Some(t)}, Tea_Cmd.none)
  | FeedbackSubmitted => ({...model, feedbackPending: None, feedbackError: None}, Tea_Cmd.none)
  | FeedbackSubmissionResult(result) =>
    switch result {
    | Ok(_) => ({...model, feedbackPending: None, feedbackError: None}, Tea_Cmd.none)
    | Error(err) => ({...model, feedbackError: Some(err)}, Tea_Cmd.none)
    }
  }
}

// ===========================================================================
// Anti-Crash Sub-Updater
// ===========================================================================

/// STATE TRANSITION: Anti-Crash Validation
/// Routes neural tokens through the symbolic validation pipeline (the Circuit
/// Breaker) before they can reach the Task Barycentre. Halts inference when
/// a strict violation is detected, requiring operator intervention to resume.
let updateAntiCrash = (model: model, msg: antiCrashMsg): (model, Tea_Cmd.t<msg>) => {
  switch msg {
  | ValidateToken(token) => {
      // Run the token through the full Anti-Crash pipeline.
      let (newAntiCrash, validatedToken) = AntiCrash.processToken(
        token,
        model.paneL.constraints,
        model.antiCrash,
      )
      // If the token passed validation, add it to the neural stream.
      let newPaneN = switch validatedToken {
      | Some(vt) => {...model.paneN, tokens: Array.concat(model.paneN.tokens, [vt])}
      | None => model.paneN
      }
      ({...model, antiCrash: newAntiCrash, paneN: newPaneN}, Tea_Cmd.none)
    }
  | ValidationPassed(token) => {
      // Token has already been validated externally — add directly.
      let newPaneN = {...model.paneN, tokens: Array.concat(model.paneN.tokens, [token])}
      ({...model, paneN: newPaneN}, Tea_Cmd.none)
    }
  | ValidationFailed(_token, reason) => {
      // Record the violation and potentially halt inference.
      let violation = LogicContradiction(reason)
      let newAntiCrash = {
        ...model.antiCrash,
        violations: Array.concat(model.antiCrash.violations, [violation]),
        halted: model.antiCrash.strictMode,
      }
      ({...model, antiCrash: newAntiCrash}, Tea_Cmd.none)
    }
  | RequestOperatorIntervention(_reason) => {
      // Halt the system and wait for operator to review.
      let newAntiCrash = {
        ...model.antiCrash,
        halted: true,
      }
      ({...model, antiCrash: newAntiCrash}, Tea_Cmd.none)
    }
  }
}

// ===========================================================================
// Contractiles Post-Processing (Cognitive Governance)
// ===========================================================================

/// Evaluate all contractiles against the current model state and update their
/// statuses. If any Strict contractile is Violated, halt neural inference as
/// a safety measure. This is called after every state-modifying update in the
/// main orchestrator.
let applyContractiles = (model: model, cmd: Tea_Cmd.t<msg>): (model, Tea_Cmd.t<msg>) => {
  let results = Contractiles.evaluateAll(model, model.contractiles)

  // Update each contractile's status based on evaluation results.
  let updatedContractiles = Array.map(model.contractiles, c => {
    let result = Array.find(results, r => r.contractId === c.id)
    switch result {
    | Some(r) => {...c, status: r.status}
    | None => c
    }
  })

  // Check for any Strict contractile violation — these require halting.
  let hasStrictViolation = Array.some(results, r => {
    let contractile = Array.find(model.contractiles, c => c.id === r.contractId)
    switch contractile {
    | Some(c) =>
      switch (c.enforcement, r.status) {
      | (Strict, Violated(_)) => true
      | _ => false
      }
    | None => false
    }
  })

  let newModel = {...model, contractiles: updatedContractiles}

  // If a Strict contractile is violated, halt neural inference.
  if hasStrictViolation {
    ({...newModel, paneN: {...newModel.paneN, inferenceActive: false}}, cmd)
  } else {
    (newModel, cmd)
  }
}

// ===========================================================================
// Main Orchestrator
// ===========================================================================

/// ORCHESTRATOR: The main entry point for state updates.
/// Routes each message to its domain-specific sub-updater, then applies
/// contractile evaluation as a post-processing cognitive governance step.
///
/// The contractile check runs after every state-modifying update (not NoOp)
/// to enforce the Binary Star system's behavioural contracts:
///   - Orbital Stability Bound (Strict)
///   - Vexation Ceiling (Adaptive)
///   - Divergence Limit (Warn)
///   - Autonomy Bound (Strict)
let update = (model: model, msg: msg): (model, Tea_Cmd.t<msg>) => {
  let (newModel, cmd) = switch msg {
  | PaneL(subMsg) => (updatePaneL(model, subMsg), Tea_Cmd.none)
  | PaneN(subMsg) => (updatePaneN(model, subMsg), Tea_Cmd.none)
  | PaneW(subMsg) => updatePaneW(model, subMsg)
  | VeriSimDB(subMsg) => updateVeriSimDB(model, subMsg)
  | Vexometer(subMsg) => updateVexometer(model, subMsg)
  | Orbital(subMsg) => updateOrbital(model, subMsg)
  | View(subMsg) => updateView(model, subMsg)
  | Feedback(subMsg) => updateFeedback(model, subMsg)
  | AntiCrash(subMsg) => updateAntiCrash(model, subMsg)
  | SaveState => {
      // Imperative: persist current state to localStorage.
      Storage.save(model)
      (model, Tea_Cmd.none)
    }
  | NoOp => (model, Tea_Cmd.none)
  }

  // Post-processing: evaluate contractiles after every state-modifying update.
  // Skip for NoOp to avoid unnecessary computation.
  switch msg {
  | NoOp => (newModel, cmd)
  | _ => applyContractiles(newModel, cmd)
  }
}
