// SPDX-License-Identifier: PMPL-1.0-or-later

/// PanLL Update Engine — The state transition kernel.
///
/// This module implements the "Update" function of The Elm Architecture (TEA).
/// It is responsible for taking the current `model` and an incoming `msg`,
/// and producing a new version of the model along with any required
/// side-effect commands (`Tea_Cmd`).
///
/// Architecture:
///   1. Domain sub-updaters handle each message category (PaneL, PaneN, PaneW, etc.)
///   2. The main `update()` orchestrator routes messages to sub-updaters
///   3. Contractiles post-processing evaluates cognitive governance contracts
///      after every state-modifying update
///
/// DESIGN: Sub-updaters are pure — commands represent deferred side effects.
/// The only imperative call is `Storage.save()` in the SaveState handler.

open Model
open Msg

// ===========================================================================
// Pane Sub-Updaters
// ===========================================================================

/// STATE TRANSITION: Pane-L (Logical Constraints)
/// Manages the set of formal constraints applied to the current inference session.
/// Handles all 6 paneLMsg variants: add, remove, toggle, pin, edit, set active.
let updatePaneL = (model: model, msg: paneLMsg): model => {
  let paneL = model.paneL
  let newPaneL = switch msg {
  | AddConstraint(c) => {...paneL, constraints: Array.concat(paneL.constraints, [c])}
  | RemoveConstraint(id) => {
      ...paneL,
      constraints: Array.filter(paneL.constraints, c => c.id !== id),
    }
  | ToggleConstraint(id) => {
      // Functional update: flip the 'active' status of the targeted constraint.
      ...paneL,
      constraints: Array.map(paneL.constraints, c =>
        c.id === id ? {...c, active: !c.active} : c
      ),
    }
  | PinConstraint(id) => {
      // Toggle the 'pinned' flag — pinned constraints survive session resets.
      ...paneL,
      constraints: Array.map(paneL.constraints, c =>
        c.id === id ? {...c, pinned: !c.pinned} : c
      ),
    }
  | UpdateEditorContent(content) => {...paneL, editorContent: content}
  | SetActiveConstraint(id) => {...paneL, activeConstraintId: id}
  }
  {...model, paneL: newPaneL}
}

/// STATE TRANSITION: Pane-N (Neural/Inference Tokens)
/// Handles the real-time stream of tokens generated by the LLM.
/// All 5 paneNMsg variants: receive, clear, toggle active, monologue, agency.
let updatePaneN = (model: model, msg: paneNMsg): model => {
  let paneN = model.paneN
  let newPaneN = switch msg {
  | ReceiveToken(token) => {...paneN, tokens: Array.concat(paneN.tokens, [token])}
  | ClearTokens => {...paneN, tokens: []}
  | SetInferenceActive(active) => {...paneN, inferenceActive: active}
  | UpdateMonologue(text) => {...paneN, monologue: text}
  | UpdateAgency(agency) => {...paneN, agency}
  }
  {...model, paneN: newPaneN}
}

// ===========================================================================
// Pane-W Helpers
// ===========================================================================

/// Parse panic-attacker capability JSON response.
/// Extracts mode, binary path, and status detail from the backend probe result.
/// Expected JSON shape: { "mode": "full"|"fallback"|"unavailable",
///   "binary_path": "/path/to/binary", "status_detail": "..." }
let parsePanicAttackerCapability = (json: string): (string, option<string>, option<string>) => {
  try {
    let parsed = JSON.parseExn(json)
    switch JSON.Classify.classify(parsed) {
    | Object(obj) => {
        let getStr = (key: string): option<string> =>
          switch Dict.get(obj, key) {
          | Some(v) =>
            switch JSON.Classify.classify(v) {
            | String(s) => Some(s)
            | _ => None
            }
          | None => None
          }
        let mode = switch getStr("mode") {
        | Some(m) => m
        | None => "unknown"
        }
        (mode, getStr("binary_path"), getStr("status_detail"))
      }
    | _ => ("unknown", None, None)
    }
  } catch {
  | _ => ("unknown", None, None)
  }
}

// ===========================================================================
// Pane-W Sub-Updater
// ===========================================================================

/// STATE TRANSITION: Pane-W (World / Event Chains)
/// Orchestrates the visualization of complex temporal event chains,
/// security study reports, and panic-attacker integration.
///
/// Returns `(model, Tea_Cmd.t<msg>)` because several handlers issue Tauri
/// commands (file dialogs, backend imports, security ambush runs).
let updatePaneW = (model: model, msg: paneWMsg): (model, Tea_Cmd.t<msg>) => {
  let paneW = model.paneW
  switch msg {
  // --- Content & view toggles (pure state) ---
  | UpdateContent(text) =>
    ({...model, paneW: {...paneW, content: text}}, Tea_Cmd.none)
  | ToggleTopologyView =>
    ({...model, paneW: {...paneW, topologyView: !paneW.topologyView}}, Tea_Cmd.none)
  | SetValidatedOutput(text) =>
    ({...model, paneW: {...paneW, lastValidatedOutput: text}}, Tea_Cmd.none)
  | UpdateEventChainInput(text) =>
    ({...model, paneW: {...paneW, eventChainInput: text}}, Tea_Cmd.none)
  | ClearEventChain => (
      {...model, paneW: {
        ...paneW,
        eventChain: [],
        eventChainSummary: None,
        eventChainTimeline: None,
        eventChainInput: "",
        eventChainError: None,
      }},
      Tea_Cmd.none,
    )

  // --- Inline event chain parsing from text input ---
  | ImportEventChain =>
    // PARSING: Transforms raw JSON input into a structured event chain.
    switch EventChain.parse(paneW.eventChainInput) {
    | Ok(payload) => (
        {...model, paneW: {
          ...paneW,
          eventChain: payload.events,
          eventChainSummary: payload.summary,
          eventChainTimeline: payload.timeline,
          eventChainError: None,
        }},
        Tea_Cmd.none,
      )
    | Error(err) => ({...model, paneW: {...paneW, eventChainError: Some(err)}}, Tea_Cmd.none)
    }

  // --- File import commands (issue Tauri commands, await result) ---
  | ImportEventChainFile => (
      model,
      TauriCmd.openEventChainFile(result => PaneW(EventChainFileLoaded(result))),
    )
  | ImportPanicAttackerReportFile => (
      model,
      TauriCmd.openPanicAttackerReportFile(result =>
        PaneW(PanicAttackerReportPathLoaded(result))
      ),
    )
  | ImportLatestPanicAttacker => (
      model,
      TauriCmd.importLatestPanicAttackerReport(result =>
        PaneW(PanicAttackerImportLoaded(result))
      ),
    )
  | CheckPanicAttackerCapability => (
      model,
      TauriCmd.getPanicAttackerCapability(result =>
        PaneW(PanicAttackerCapabilityLoaded(result))
      ),
    )

  // --- File import results (parse response data) ---
  | EventChainFileLoaded(result) =>
    switch result {
    | Ok(contents) =>
      switch EventChain.parse(contents) {
      | Ok(payload) => (
          {...model, paneW: {
            ...paneW,
            eventChain: payload.events,
            eventChainSummary: payload.summary,
            eventChainTimeline: payload.timeline,
            eventChainError: None,
          }},
          Tea_Cmd.none,
        )
      | Error(err) => ({...model, paneW: {...paneW, eventChainError: Some(err)}}, Tea_Cmd.none)
      }
    | Error(err) => ({...model, paneW: {...paneW, eventChainError: Some(err)}}, Tea_Cmd.none)
    }
  | PanicAttackerReportPathLoaded(result) =>
    // Two-phase import: first get the file path, then ask backend to convert.
    switch result {
    | Ok(path) => (
        model,
        TauriCmd.importPanicAttackerReport(path, result =>
          PaneW(PanicAttackerImportLoaded(result))
        ),
      )
    | Error(err) => ({...model, paneW: {...paneW, eventChainError: Some(err)}}, Tea_Cmd.none)
    }
  | PanicAttackerImportLoaded(result) =>
    switch result {
    | Ok(json) =>
      switch EventChain.parse(json) {
      | Ok(payload) => (
          {...model, paneW: {
            ...paneW,
            eventChain: payload.events,
            eventChainSummary: payload.summary,
            eventChainTimeline: payload.timeline,
            eventChainError: None,
          }},
          Tea_Cmd.none,
        )
      | Error(err) => ({...model, paneW: {...paneW, eventChainError: Some(err)}}, Tea_Cmd.none)
      }
    | Error(err) => ({...model, paneW: {...paneW, eventChainError: Some(err)}}, Tea_Cmd.none)
    }
  | PanicAttackerCapabilityLoaded(result) =>
    switch result {
    | Ok(json) => {
        let (mode, binary, detail) = parsePanicAttackerCapability(json)
        (
          {...model, paneW: {
            ...paneW,
            panicAttackerMode: mode,
            panicAttackerBinary: binary,
            panicAttackerStatusDetail: detail,
          }},
          Tea_Cmd.none,
        )
      }
    | Error(err) => (
        {...model, paneW: {
          ...paneW,
          panicAttackerMode: "unavailable",
          panicAttackerStatusDetail: Some(err),
        }},
        Tea_Cmd.none,
      )
    }

  // --- Security menu interactions (pure state) ---
  | ToggleSecurityTools =>
    ({...model, paneW: {...paneW, securityMenuExpanded: !paneW.securityMenuExpanded}}, Tea_Cmd.none)
  | OpenSecurityDialog(tool) =>
    ({...model, paneW: {...paneW, securityDialogOpen: true, securityDialogTool: Some(tool)}}, Tea_Cmd.none)
  | CloseSecurityDialog =>
    ({...model, paneW: {...paneW, securityDialogOpen: false, securityDialogTool: None}}, Tea_Cmd.none)
  | ToggleSecurityStudyView =>
    ({...model, paneW: {...paneW, securityViewActive: !paneW.securityViewActive}}, Tea_Cmd.none)
  | SetSecurityTarget(t) =>
    ({...model, paneW: {...paneW, securityTarget: t}}, Tea_Cmd.none)
  | SetSecurityTimeline(t) =>
    ({...model, paneW: {...paneW, securityTimeline: t}}, Tea_Cmd.none)
  | SetSecurityAxes(a) =>
    ({...model, paneW: {...paneW, securityAxes: a}}, Tea_Cmd.none)
  | SetSecurityIntensity(i) =>
    ({...model, paneW: {...paneW, securityIntensity: i}}, Tea_Cmd.none)
  | SetSecurityDuration(d) =>
    ({...model, paneW: {...paneW, securityDuration: d}}, Tea_Cmd.none)

  // --- Security command lifecycle ---
  | LoadSecurityTimelineFile => (
      model,
      TauriCmd.openSecurityTimelineFile(result =>
        PaneW(SecurityTimelineFileLoaded(result))
      ),
    )
  | SecurityTimelineFileLoaded(result) =>
    switch result {
    | Ok(path) => ({...model, paneW: {...paneW, securityTimeline: path}}, Tea_Cmd.none)
    | Error(err) => ({...model, paneW: {...paneW, securityError: Some(err)}}, Tea_Cmd.none)
    }
  | LaunchSecurityAmbush => {
      // Gather options from current Pane-W state for the ambush command.
      let timeline = if paneW.securityTimeline !== "" {
        Some(paneW.securityTimeline)
      } else {
        None
      }
      let axes = if paneW.securityAxes !== "" {
        Some(paneW.securityAxes)
      } else {
        None
      }
      let durationSecs = switch Int.fromString(paneW.securityDuration) {
      | Some(d) => d
      | None => 30
      }
      (
        {...model, paneW: {...paneW, securityStatus: Some("Running..."), securityError: None}},
        TauriCmd.runPanicAttackAmbush(
          paneW.securityTarget,
          timeline,
          axes,
          paneW.securityIntensity,
          durationSecs,
          result => PaneW(SecurityAmbushResult(result)),
        ),
      )
    }
  | SecurityAmbushResult(result) =>
    switch result {
    | Ok(json) =>
      switch EventChain.parse(json) {
      | Ok(payload) => (
          {...model, paneW: {
            ...paneW,
            eventChain: payload.events,
            eventChainSummary: payload.summary,
            eventChainTimeline: payload.timeline,
            eventChainError: None,
            securityStatus: Some("Complete"),
            securityError: None,
          }},
          Tea_Cmd.none,
        )
      | Error(err) => (
          {...model, paneW: {...paneW, securityStatus: Some("Failed"), securityError: Some(err)}},
          Tea_Cmd.none,
        )
      }
    | Error(err) => (
        {...model, paneW: {...paneW, securityStatus: Some("Failed"), securityError: Some(err)}},
        Tea_Cmd.none,
      )
    }
  }
}

// ===========================================================================
// VeriSimDB Parsers
// ===========================================================================

/// Parse proof obligations from a VQL-DT JSON response.
/// VQL-DT queries return a `proof_certificate` object with an array of proofs.
/// Each proof has type, contract, verified status, and hash fields.
let parseProofObligations = (json: string): array<proofObligation> => {
  try {
    let parsed = JSON.parseExn(json)
    // Look for proof_certificate.proofs in the response
    switch JSON.Classify.classify(parsed) {
    | Object(obj) =>
      switch Dict.get(obj, "proof_certificate") {
      | Some(cert) =>
        switch JSON.Classify.classify(cert) {
        | Object(certObj) =>
          switch Dict.get(certObj, "proofs") {
          | Some(proofsVal) =>
            switch JSON.Classify.classify(proofsVal) {
            | Array(proofArr) =>
              proofArr->Array.filterMap(p =>
                switch JSON.Classify.classify(p) {
                | Object(proofObj) => {
                    let getStr = (key: string): string =>
                      switch Dict.get(proofObj, key) {
                      | Some(v) =>
                        switch JSON.Classify.classify(v) {
                        | String(s) => s
                        | _ => ""
                        }
                      | None => ""
                      }
                    let proofType = getStr("type")
                    let status = if getStr("verified") == "true" { "verified" } else { "pending" }
                    Some({
                      proofType,
                      contractName: getStr("contract"),
                      status,
                      proofHash: getStr("hash"),
                    })
                  }
                | _ => None
                }
              )
            | _ => []
            }
          | None => []
          }
        | _ => []
        }
      | None => []
      }
    | _ => []
    }
  } catch {
  | _ => []
  }
}

/// Parse drift scores from a drift status JSON response.
/// Returns structured drift scores for all 8 octad modalities.
let parseDriftScores = (json: string): option<driftScores> => {
  try {
    let parsed = JSON.parseExn(json)
    switch JSON.Classify.classify(parsed) {
    | Object(obj) => {
        let getFloat = (key: string): float =>
          switch Dict.get(obj, key) {
          | Some(v) =>
            switch JSON.Classify.classify(v) {
            | Number(n) => n
            | _ => 0.0
            }
          | None => 0.0
          }
        Some({
          graph: getFloat("graph"),
          vector: getFloat("vector"),
          tensor: getFloat("tensor"),
          semantic: getFloat("semantic"),
          document: getFloat("document"),
          temporal: getFloat("temporal"),
          provenance: getFloat("provenance"),
          spatial: getFloat("spatial"),
        })
      }
    | _ => None
    }
  } catch {
  | _ => None
  }
}

/// Parse a telemetry snapshot from the VeriSimDB reporter JSON response.
/// Extracts aggregate-only product development metrics — no PII or query content.
let parseTelemetrySnapshot = (json: string): option<telemetrySnapshot> => {
  try {
    let parsed = JSON.parseExn(json)
    switch JSON.Classify.classify(parsed) {
    | Object(obj) => {
        // Helper to safely extract nested fields.
        let getObj = (key: string): option<Dict.t<JSON.t>> =>
          switch Dict.get(obj, key) {
          | Some(v) =>
            switch JSON.Classify.classify(v) {
            | Object(o) => Some(o)
            | _ => None
            }
          | None => None
          }

        let getFloat = (o: Dict.t<JSON.t>, key: string): float =>
          switch Dict.get(o, key) {
          | Some(v) =>
            switch JSON.Classify.classify(v) {
            | Number(n) => n
            | _ => 0.0
            }
          | None => 0.0
          }

        let getInt = (o: Dict.t<JSON.t>, key: string): int =>
          switch Dict.get(o, key) {
          | Some(v) =>
            switch JSON.Classify.classify(v) {
            | Number(n) => Float.toInt(n)
            | _ => 0
            }
          | None => 0
          }

        let getString = (o: Dict.t<JSON.t>, key: string): string =>
          switch Dict.get(o, key) {
          | Some(v) =>
            switch JSON.Classify.classify(v) {
            | String(s) => s
            | _ => ""
            }
          | None => ""
          }

        // Parse modality heatmap (percentages)
        let modalityHeatmap = switch getObj("modality_heatmap") {
        | Some(heatmap) =>
          switch Dict.get(heatmap, "percentages") {
          | Some(v) =>
            switch JSON.Classify.classify(v) {
            | Object(pcts) =>
              Dict.keysToArray(pcts)
              ->Array.map(key => (key, getFloat(pcts, key)))
            | _ => []
            }
          | None => []
          }
        | None => []
        }

        // Parse query patterns
        let queryPatterns = switch getObj("query_patterns") {
        | Some(patterns) =>
          switch Dict.get(patterns, "by_type") {
          | Some(v) =>
            switch JSON.Classify.classify(v) {
            | Object(types) =>
              Dict.keysToArray(types)
              ->Array.map(key => (key, getInt(types, key)))
            | _ => []
            }
          | None => []
          }
        | None => []
        }

        // Parse proof type usage
        let proofTypeUsage = switch getObj("proof_types") {
        | Some(proofs) =>
          switch Dict.get(proofs, "by_type") {
          | Some(v) =>
            switch JSON.Classify.classify(v) {
            | Object(types) =>
              Dict.keysToArray(types)
              ->Array.map(key => (key, getInt(types, key)))
            | _ => []
            }
          | None => []
          }
        | None => []
        }

        // Extract scalar metrics
        let avgDuration = switch getObj("performance") {
        | Some(perf) => getFloat(perf, "avg_duration_ms")
        | None => 0.0
        }

        let driftCount = switch getObj("drift") {
        | Some(drift) => getInt(drift, "drift_detected_count")
        | None => 0
        }

        let successRate = switch getObj("drift") {
        | Some(drift) => getFloat(drift, "normalise_success_rate")
        | None => 0.0
        }

        let entityCount = switch getObj("entities") {
        | Some(entities) => getInt(entities, "created")
        | None => 0
        }

        let generatedAt = switch getObj("meta") {
        | Some(meta) => getString(meta, "generated_at")
        | None => ""
        }

        let privacyNotice = switch getObj("meta") {
        | Some(meta) => getString(meta, "privacy_notice")
        | None => "Aggregate metrics only. No query content or PII."
        }

        Some({
          generatedAt,
          modalityHeatmap,
          queryPatterns,
          avgQueryDurationMs: avgDuration,
          driftDetectedCount: driftCount,
          normaliseSuccessRate: successRate,
          proofTypeUsage,
          entityCount,
          privacyNotice,
        })
      }
    | _ => None
    }
  } catch {
  | _ => None
  }
}

// ===========================================================================
// VeriSimDB Sub-Updater
// ===========================================================================

/// STATE TRANSITION: VeriSimDB (Database Backend)
/// Manages the VeriSimDB connection state, VQL query lifecycle, entity browsing,
/// drift detection status, normalisation, and entity detail. Each message either
/// triggers a Tauri command (side effect) or updates model state from a command
/// result.
let updateVeriSimDB = (model: model, msg: verisimdbMsg): (model, Tea_Cmd.t<msg>) => {
  let db = model.verisimdb
  switch msg {
  | CheckHealth => (
      model,
      TauriCmd.checkVeriSimDBHealth(result => VeriSimDB(HealthResult(result))),
    )
  | HealthResult(result) =>
    switch result {
    | Ok(_json) => ({...model, verisimdb: {...db, connected: true, queryError: None}}, Tea_Cmd.none)
    | Error(err) => ({...model, verisimdb: {...db, connected: false, queryError: Some(err)}}, Tea_Cmd.none)
    }
  | SubmitQuery(query) => (
      {...model, verisimdb: {...db, lastQuery: query, queryResult: None, queryError: None, proofObligations: []}},
      TauriCmd.queryVeriSimDB(query, result => VeriSimDB(QueryResult(result))),
    )
  | UpdateQueryInput(text) => (
      {...model, verisimdb: {...db, lastQuery: text}},
      Tea_Cmd.none,
    )
  | QueryResult(result) =>
    switch result {
    | Ok(json) =>
      // Parse proof obligations from VQL-DT responses
      let proofs = parseProofObligations(json)
      (
        {...model, verisimdb: {...db, queryResult: Some(json), queryError: None, proofObligations: proofs}},
        Tea_Cmd.none,
      )
    | Error(err) => ({...model, verisimdb: {...db, queryResult: None, queryError: Some(err)}}, Tea_Cmd.none)
    }
  | ListEntities => (
      model,
      TauriCmd.listHexads(50, 0, result => VeriSimDB(EntitiesLoaded(result))),
    )
  | EntitiesLoaded(result) =>
    switch result {
    | Ok(_json) => ({...model, verisimdb: {...db, queryError: None}}, Tea_Cmd.none)
    | Error(err) => ({...model, verisimdb: {...db, queryError: Some(err)}}, Tea_Cmd.none)
    }
  | SelectEntity(entityId) => (
      {...model, verisimdb: {...db, selectedEntity: Some(entityId), entityDetail: None}},
      TauriCmd.batch(list{
        TauriCmd.getDrift(entityId, result => VeriSimDB(DriftLoaded(result))),
        TauriCmd.getEntityDetail(entityId, result => VeriSimDB(EntityDetailLoaded(result))),
      }),
    )
  | DriftLoaded(result) =>
    switch result {
    | Ok(json) =>
      let scores = parseDriftScores(json)
      (
        {...model, verisimdb: {...db, driftStatus: Some(json), driftScores: scores, queryError: None}},
        Tea_Cmd.none,
      )
    | Error(err) => (
        {...model, verisimdb: {...db, driftStatus: None, driftScores: None, queryError: Some(err)}},
        Tea_Cmd.none,
      )
    }
  | ToggleDbMenu => (
      {...model, verisimdb: {...db, dbMenuExpanded: !db.dbMenuExpanded}},
      Tea_Cmd.none,
    )
  | ClearQueryResult => (
      {...model, verisimdb: {...db, queryResult: None, queryError: None, proofObligations: []}},
      Tea_Cmd.none,
    )
  | TriggerNormalise(entityId) => (
      {...model, verisimdb: {...db, normalisingEntity: Some(entityId)}},
      TauriCmd.triggerNormalise(entityId, result => VeriSimDB(NormaliseResult(result))),
    )
  | NormaliseResult(result) =>
    switch result {
    | Ok(_json) => (
        {...model, verisimdb: {...db, normalisingEntity: None, queryError: None}},
        // Refresh drift status after normalisation
        switch db.selectedEntity {
        | Some(entityId) =>
          TauriCmd.getDrift(entityId, result => VeriSimDB(DriftLoaded(result)))
        | None => Tea_Cmd.none
        },
      )
    | Error(err) => (
        {...model, verisimdb: {...db, normalisingEntity: None, queryError: Some(err)}},
        Tea_Cmd.none,
      )
    }
  | LoadEntityDetail(entityId) => (
      model,
      TauriCmd.getEntityDetail(entityId, result => VeriSimDB(EntityDetailLoaded(result))),
    )
  | EntityDetailLoaded(result) =>
    switch result {
    | Ok(json) => ({...model, verisimdb: {...db, entityDetail: Some(json), queryError: None}}, Tea_Cmd.none)
    | Error(err) => ({...model, verisimdb: {...db, entityDetail: None, queryError: Some(err)}}, Tea_Cmd.none)
    }
  | FetchTelemetry => (
      model,
      TauriCmd.getTelemetry(result => VeriSimDB(TelemetryLoaded(result))),
    )
  | TelemetryLoaded(result) =>
    switch result {
    | Ok(json) =>
      let snapshot = parseTelemetrySnapshot(json)
      ({...model, verisimdb: {...db, telemetry: snapshot, queryError: None}}, Tea_Cmd.none)
    | Error(err) => ({...model, verisimdb: {...db, telemetry: None, queryError: Some(err)}}, Tea_Cmd.none)
    }
  | ToggleTelemetryPanel => (
      {...model, verisimdb: {...db, telemetryVisible: !db.telemetryVisible}},
      Tea_Cmd.none,
    )
  | FetchOrchStatus => (
      model,
      TauriCmd.getOrchStatus(result => VeriSimDB(OrchStatusLoaded(result))),
    )
  | OrchStatusLoaded(result) =>
    switch result {
    | Ok(json) => ({...model, verisimdb: {...db, orchStatus: Some(json), queryError: None}}, Tea_Cmd.none)
    | Error(err) => ({...model, verisimdb: {...db, orchStatus: None, queryError: Some(err)}}, Tea_Cmd.none)
    }
  }
}

// ===========================================================================
// ECHIDNA Parsers
// ===========================================================================

/// Parse the ECHIDNA version string from a health check JSON response.
/// Expected shape: `{ "status": "ok", "version": "0.4.2" }`.
let parseEchidnaVersion = (json: string): option<string> => {
  try {
    let parsed = JSON.parseExn(json)
    switch JSON.Classify.classify(parsed) {
    | Object(obj) =>
      switch Dict.get(obj, "version") {
      | Some(v) =>
        switch JSON.Classify.classify(v) {
        | String(s) => Some(s)
        | _ => None
        }
      | None => None
      }
    | _ => None
    }
  } catch {
  | _ => None
  }
}

/// Parse the ECHIDNA prover catalog from a list provers JSON response.
/// Expected shape: `[{ "name": "z3", "tier": "SMT", "complexity": "NP" }, ...]`
/// or `{ "provers": [...] }` wrapper.
let parseEchidnaProvers = (json: string): array<echidnaProver> => {
  try {
    let parsed = JSON.parseExn(json)
    // Helper to extract a prover record from a JSON object.
    let parseProver = (obj: Dict.t<JSON.t>): option<echidnaProver> => {
      let getStr = (key: string): string =>
        switch Dict.get(obj, key) {
        | Some(v) =>
          switch JSON.Classify.classify(v) {
          | String(s) => s
          | _ => ""
          }
        | None => ""
        }
      let name = getStr("name")
      if name === "" {
        None
      } else {
        Some({name, tier: getStr("tier"), complexity: getStr("complexity")})
      }
    }
    // Try direct array first, then check for { "provers": [...] } wrapper.
    switch JSON.Classify.classify(parsed) {
    | Array(arr) =>
      arr->Array.filterMap(item =>
        switch JSON.Classify.classify(item) {
        | Object(obj) => parseProver(obj)
        | _ => None
        }
      )
    | Object(obj) =>
      switch Dict.get(obj, "provers") {
      | Some(v) =>
        switch JSON.Classify.classify(v) {
        | Array(arr) =>
          arr->Array.filterMap(item =>
            switch JSON.Classify.classify(item) {
            | Object(o) => parseProver(o)
            | _ => None
            }
          )
        | _ => []
        }
      | None => []
      }
    | _ => []
    }
  } catch {
  | _ => []
  }
}

/// Parse an ECHIDNA dispatch result from a proof/verify JSON response.
/// Maps trust_level integers (1-5) to the echidnaTrustLevel variant,
/// parses the axiom report, and extracts prover telemetry.
let parseEchidnaDispatchResult = (json: string): option<echidnaDispatchResult> => {
  try {
    let parsed = JSON.parseExn(json)
    switch JSON.Classify.classify(parsed) {
    | Object(obj) => {
        let getStr = (key: string): string =>
          switch Dict.get(obj, key) {
          | Some(v) =>
            switch JSON.Classify.classify(v) {
            | String(s) => s
            | _ => ""
            }
          | None => ""
          }
        let getBool = (key: string): bool =>
          switch Dict.get(obj, key) {
          | Some(v) =>
            switch JSON.Classify.classify(v) {
            | Bool(b) => b
            | _ => false
            }
          | None => false
          }
        let getFloat = (key: string): float =>
          switch Dict.get(obj, key) {
          | Some(v) =>
            switch JSON.Classify.classify(v) {
            | Number(n) => n
            | _ => 0.0
            }
          | None => 0.0
          }
        let getInt = (key: string): int =>
          switch Dict.get(obj, key) {
          | Some(v) =>
            switch JSON.Classify.classify(v) {
            | Number(n) => Float.toInt(n)
            | _ => 0
            }
          | None => 0
          }

        // Parse trust_level integer to variant
        let trustLevel = switch getInt("trust_level") {
        | 1 => TrustLevel1
        | 2 => TrustLevel2
        | 3 => TrustLevel3
        | 4 => TrustLevel4
        | 5 => TrustLevel5
        | _ => TrustLevel1
        }

        // Parse provers_used string array
        let proversUsed = switch Dict.get(obj, "provers_used") {
        | Some(v) =>
          switch JSON.Classify.classify(v) {
          | Array(arr) =>
            arr->Array.filterMap(item =>
              switch JSON.Classify.classify(item) {
              | String(s) => Some(s)
              | _ => None
              }
            )
          | _ => []
          }
        | None => []
        }

        // Parse axiom_report array
        let axiomReport = switch Dict.get(obj, "axiom_report") {
        | Some(v) =>
          switch JSON.Classify.classify(v) {
          | Array(arr) =>
            arr->Array.filterMap(item =>
              switch JSON.Classify.classify(item) {
              | Object(axiomObj) => {
                  let aGetStr = (key: string): string =>
                    switch Dict.get(axiomObj, key) {
                    | Some(av) =>
                      switch JSON.Classify.classify(av) {
                      | String(s) => s
                      | _ => ""
                      }
                    | None => ""
                    }
                  let dangerLevel = switch aGetStr("danger_level") {
                  | "safe" => Safe
                  | "noted" => Noted
                  | "warning" => Warning
                  | "reject" => Reject
                  | _ => Noted
                  }
                  Some({
                    axiomName: aGetStr("axiom_name"),
                    dangerLevel,
                    description: aGetStr("description"),
                  })
                }
              | _ => None
              }
            )
          | _ => []
          }
        | None => []
        }

        // Parse cross_checked string to variant
        let crossChecked = switch getStr("cross_checked") {
        | "cross_checked" => CrossChecked
        | "single_solver" => SingleSolver
        | "inconclusive" => Inconclusive
        | "all_timed_out" => AllTimedOut
        | _ => SingleSolver
        }

        // Parse optional certificate hash
        let certificateHash = switch Dict.get(obj, "certificate_hash") {
        | Some(v) =>
          switch JSON.Classify.classify(v) {
          | String(s) => Some(s)
          | _ => None
          }
        | None => None
        }

        Some({
          verified: getBool("verified"),
          trustLevel,
          proversUsed,
          proofTimeMs: getFloat("proof_time_ms"),
          goalsRemaining: getInt("goals_remaining"),
          axiomReport,
          certificateHash,
          message: getStr("message"),
          crossChecked,
        })
      }
    | _ => None
    }
  } catch {
  | _ => None
  }
}

// ===========================================================================
// ECHIDNA Session & Tactic Parsers
// ===========================================================================

/// Parse a proof status string from ECHIDNA's ProofResponse into the variant type.
let parseProofStatus = (s: string): echidnaProofStatus => {
  switch s {
  | "pending" => Pending
  | "in_progress" => InProgress
  | "success" => ProofSuccess
  | "failed" => ProofFailed
  | "timeout" => ProofTimeout
  | "error" => ProofError
  | _ => Pending
  }
}

/// Parse an ECHIDNA ProofResponse JSON into echidnaSessionState.
/// Expected shape: `{ "id": "...", "prover": "...", "goal": "...",
///   "status": "in_progress", "goals": [...], "proof_script": [...],
///   "complete": false, "tactics_applied": [...],
///   "time_elapsed": 1.23, "error_message": null }`
let parseEchidnaSession = (json: string): option<echidnaSessionState> => {
  try {
    let parsed = JSON.parseExn(json)
    switch JSON.Classify.classify(parsed) {
    | Object(obj) => {
        let getStr = (key: string): string =>
          switch Dict.get(obj, key) {
          | Some(v) =>
            switch JSON.Classify.classify(v) {
            | String(s) => s
            | _ => ""
            }
          | None => ""
          }
        let getBool = (key: string): bool =>
          switch Dict.get(obj, key) {
          | Some(v) =>
            switch JSON.Classify.classify(v) {
            | Bool(b) => b
            | _ => false
            }
          | None => false
          }
        let getStrArray = (key: string): array<string> =>
          switch Dict.get(obj, key) {
          | Some(v) =>
            switch JSON.Classify.classify(v) {
            | Array(arr) =>
              arr->Array.filterMap(item =>
                switch JSON.Classify.classify(item) {
                | String(s) => Some(s)
                | _ => None
                }
              )
            | _ => []
            }
          | None => []
          }
        let getOptFloat = (key: string): option<float> =>
          switch Dict.get(obj, key) {
          | Some(v) =>
            switch JSON.Classify.classify(v) {
            | Number(n) => Some(n)
            | _ => None
            }
          | None => None
          }
        let getOptStr = (key: string): option<string> =>
          switch Dict.get(obj, key) {
          | Some(v) =>
            switch JSON.Classify.classify(v) {
            | String(s) => Some(s)
            | _ => None
            }
          | None => None
          }

        let sessionId = getStr("id")
        if sessionId === "" {
          None
        } else {
          Some({
            sessionId,
            prover: getStr("prover"),
            goal: getStr("goal"),
            status: parseProofStatus(getStr("status")),
            goals: getStrArray("goals"),
            proofScript: getStrArray("proof_script"),
            complete: getBool("complete"),
            tacticsApplied: getStrArray("tactics_applied"),
            timeElapsed: getOptFloat("time_elapsed"),
            errorMessage: getOptStr("error_message"),
          })
        }
      }
    | _ => None
    }
  } catch {
  | _ => None
  }
}

/// Parse a TacticResponse JSON into (success, updated session state).
/// Expected shape: `{ "success": true, "proof_state": { ...ProofResponse... } }`
let parseTacticResponse = (json: string): option<(bool, echidnaSessionState)> => {
  try {
    let parsed = JSON.parseExn(json)
    switch JSON.Classify.classify(parsed) {
    | Object(obj) => {
        let success = switch Dict.get(obj, "success") {
        | Some(v) =>
          switch JSON.Classify.classify(v) {
          | Bool(b) => b
          | _ => false
          }
        | None => false
        }
        // The proof_state is embedded as a nested object — re-stringify it
        // so we can reuse parseEchidnaSession.
        switch Dict.get(obj, "proof_state") {
        | Some(proofState) =>
          let stateJson = JSON.stringify(proofState)
          switch parseEchidnaSession(stateJson) {
          | Some(session) => Some((success, session))
          | None => None
          }
        | None => None
        }
      }
    | _ => None
    }
  } catch {
  | _ => None
  }
}

/// Parse tactic suggestions JSON into an array of echidnaTacticSuggestion.
/// Expected shape: `[{ "name": "intro", "args": ["x"], "description": "...",
///   "confidence": 0.85 }, ...]`
let parseTacticSuggestions = (json: string): array<echidnaTacticSuggestion> => {
  try {
    let parsed = JSON.parseExn(json)
    switch JSON.Classify.classify(parsed) {
    | Array(arr) =>
      arr->Array.filterMap(item =>
        switch JSON.Classify.classify(item) {
        | Object(obj) => {
            let getStr = (key: string): string =>
              switch Dict.get(obj, key) {
              | Some(v) =>
                switch JSON.Classify.classify(v) {
                | String(s) => s
                | _ => ""
                }
              | None => ""
              }
            let getFloat = (key: string): float =>
              switch Dict.get(obj, key) {
              | Some(v) =>
                switch JSON.Classify.classify(v) {
                | Number(n) => n
                | _ => 0.0
                }
              | None => 0.0
              }
            let getStrArray = (key: string): array<string> =>
              switch Dict.get(obj, key) {
              | Some(v) =>
                switch JSON.Classify.classify(v) {
                | Array(a) =>
                  a->Array.filterMap(i =>
                    switch JSON.Classify.classify(i) {
                    | String(s) => Some(s)
                    | _ => None
                    }
                  )
                | _ => []
                }
              | None => []
              }
            let name = getStr("name")
            if name === "" {
              None
            } else {
              Some({
                tactic: name,
                args: getStrArray("args"),
                confidence: getFloat("confidence"),
                aspectTags: getStrArray("aspect_tags"),
                description: getStr("description"),
              })
            }
          }
        | _ => None
        }
      )
    | _ => []
    }
  } catch {
  | _ => []
  }
}

// ===========================================================================
// ECHIDNA Sub-Updater
// ===========================================================================

/// STATE TRANSITION: ECHIDNA (Theorem Prover Backend)
/// Manages the ECHIDNA connection state, prover catalog, proof submission lifecycle,
/// theorem search, interactive proof sessions, tactic suggestions, and UI toggles.
let updateEchidna = (model: model, msg: echidnaMsg): (model, Tea_Cmd.t<msg>) => {
  let ec = model.echidna
  switch msg {
  // --- Connection lifecycle ---
  | CheckHealth => (
      model,
      TauriCmd.checkEchidnaHealth(result =>
        switch result {
        | Ok(json) => Echidna(HealthOk(json))
        | Error(err) => Echidna(HealthError(err))
        }
      ),
    )
  | HealthOk(json) =>
    let version = parseEchidnaVersion(json)
    ({...model, echidna: {...ec, connected: true, version, proofError: None}}, Tea_Cmd.none)
  | HealthError(err) => (
      {...model, echidna: {...ec, connected: false, version: None, proofError: Some(err)}},
      Tea_Cmd.none,
    )

  // --- Prover catalog ---
  | ListProvers => (
      model,
      TauriCmd.listEchidnaProvers(result => Echidna(ProversLoaded(result))),
    )
  | ProversLoaded(result) =>
    switch result {
    | Ok(json) =>
      let provers = parseEchidnaProvers(json)
      ({...model, echidna: {...ec, provers, proofError: None}}, Tea_Cmd.none)
    | Error(err) => ({...model, echidna: {...ec, proofError: Some(err)}}, Tea_Cmd.none)
    }

  // --- Proof submission ---
  | SubmitProof => (
      {...model, echidna: {...ec, proofLoading: true, proofError: None, lastProofResult: None}},
      TauriCmd.echidnaProve(ec.proofInput, ec.selectedProver, result =>
        Echidna(ProofResult(result))
      ),
    )
  | ProofResult(result) =>
    switch result {
    | Ok(json) =>
      let parsed = parseEchidnaDispatchResult(json)
      (
        {...model, echidna: {...ec, lastProofResult: parsed, proofLoading: false, proofError: None}},
        Tea_Cmd.none,
      )
    | Error(err) => (
        {...model, echidna: {...ec, proofLoading: false, proofError: Some(err), lastProofResult: None}},
        Tea_Cmd.none,
      )
    }

  // --- Verification ---
  | SubmitVerify => (
      {...model, echidna: {...ec, proofLoading: true, proofError: None, lastProofResult: None}},
      TauriCmd.echidnaVerify(ec.proofInput, result => Echidna(VerifyResult(result))),
    )
  | VerifyResult(result) =>
    switch result {
    | Ok(json) =>
      let parsed = parseEchidnaDispatchResult(json)
      (
        {...model, echidna: {...ec, lastProofResult: parsed, proofLoading: false, proofError: None}},
        Tea_Cmd.none,
      )
    | Error(err) => (
        {...model, echidna: {...ec, proofLoading: false, proofError: Some(err), lastProofResult: None}},
        Tea_Cmd.none,
      )
    }

  // --- Theorem search ---
  | SearchTheorems(query) => (
      model,
      TauriCmd.echidnaSearchTheorems(query, result => Echidna(SearchResult(result))),
    )
  | SearchResult(_result) =>
    // Search results display is Phase 2 — for now just clear errors.
    ({...model, echidna: {...ec, proofError: None}}, Tea_Cmd.none)

  // --- Interactive sessions ---
  | CreateSession => {
      let prover = switch ec.selectedProver {
      | Some(p) => p
      | None => "auto"
      }
      (
        {...model, echidna: {...ec, sessionLoading: true, proofError: None}},
        TauriCmd.createEchidnaSession(ec.proofInput, prover, result =>
          Echidna(SessionCreated(result))
        ),
      )
    }
  | SessionCreated(result) =>
    switch result {
    | Ok(json) =>
      let session = parseEchidnaSession(json)
      switch session {
      | Some(s) => (
          {...model, echidna: {...ec, session: Some(s), sessionLoading: false, proofError: None}},
          // Auto-request tactic suggestions after session creation
          TauriCmd.suggestEchidnaTactics(s.sessionId, 5, result =>
            Echidna(TacticSuggestionsLoaded(result))
          ),
        )
      | None => (
          {...model, echidna: {...ec, sessionLoading: false, proofError: Some("Failed to parse session response")}},
          Tea_Cmd.none,
        )
      }
    | Error(err) => (
        {...model, echidna: {...ec, sessionLoading: false, proofError: Some(err)}},
        Tea_Cmd.none,
      )
    }
  | ApplyTactic(name, args) =>
    switch ec.session {
    | Some(s) => (
        model,
        TauriCmd.applyEchidnaTactic(s.sessionId, name, args, result =>
          Echidna(TacticApplied(result))
        ),
      )
    | None => (model, Tea_Cmd.none)
    }
  | TacticApplied(result) =>
    switch result {
    | Ok(json) =>
      switch parseTacticResponse(json) {
      | Some((_success, updatedSession)) => (
          {...model, echidna: {...ec, session: Some(updatedSession), proofError: None}},
          // Auto-request fresh suggestions after tactic application
          TauriCmd.suggestEchidnaTactics(updatedSession.sessionId, 5, result =>
            Echidna(TacticSuggestionsLoaded(result))
          ),
        )
      | None => (
          {...model, echidna: {...ec, proofError: Some("Failed to parse tactic response")}},
          Tea_Cmd.none,
        )
      }
    | Error(err) => (
        {...model, echidna: {...ec, proofError: Some(err)}},
        Tea_Cmd.none,
      )
    }
  | GetSessionState =>
    switch ec.session {
    | Some(s) => (
        model,
        TauriCmd.getEchidnaSession(s.sessionId, result =>
          Echidna(SessionStateLoaded(result))
        ),
      )
    | None => (model, Tea_Cmd.none)
    }
  | SessionStateLoaded(result) =>
    switch result {
    | Ok(json) =>
      let session = parseEchidnaSession(json)
      switch session {
      | Some(s) => ({...model, echidna: {...ec, session: Some(s), proofError: None}}, Tea_Cmd.none)
      | None => ({...model, echidna: {...ec, proofError: Some("Failed to parse session state")}}, Tea_Cmd.none)
      }
    | Error(err) => ({...model, echidna: {...ec, proofError: Some(err)}}, Tea_Cmd.none)
    }
  | CancelSession => (
      {...model, echidna: {...ec, session: None, tacticSuggestions: [], sessionLoading: false, tacticInput: "", proofError: None}},
      Tea_Cmd.none,
    )
  | UpdateTacticInput(text) => (
      {...model, echidna: {...ec, tacticInput: text}},
      Tea_Cmd.none,
    )

  // --- Tactic suggestions ---
  | RequestTacticSuggestions =>
    switch ec.session {
    | Some(s) => (
        model,
        TauriCmd.suggestEchidnaTactics(s.sessionId, 5, result =>
          Echidna(TacticSuggestionsLoaded(result))
        ),
      )
    | None => (model, Tea_Cmd.none)
    }
  | TacticSuggestionsLoaded(result) =>
    switch result {
    | Ok(json) =>
      let suggestions = parseTacticSuggestions(json)
      ({...model, echidna: {...ec, tacticSuggestions: suggestions}}, Tea_Cmd.none)
    | Error(_err) => (
        {...model, echidna: {...ec, tacticSuggestions: []}},
        Tea_Cmd.none,
      )
    }

  // --- UI state ---
  | ToggleMenu => (
      {...model, echidna: {...ec, menuExpanded: !ec.menuExpanded}},
      Tea_Cmd.none,
    )
  | UpdateProofInput(text) => (
      {...model, echidna: {...ec, proofInput: text}},
      Tea_Cmd.none,
    )
  | SelectProver(prover) => (
      {...model, echidna: {...ec, selectedProver: prover}},
      Tea_Cmd.none,
    )
  | ClearProofResult => (
      {...model, echidna: {...ec, lastProofResult: None, proofError: None}},
      Tea_Cmd.none,
    )
  }
}

// ===========================================================================
// Cognitive Governance Sub-Updaters
// ===========================================================================

/// STATE TRANSITION: Vexometer
/// Tracks operator vexation signals (cancellations, corrections) and manages
/// the anti-inflammatory feedback system. Backend events are recorded via
/// Tauri commands so the Rust VexationTracker can compute the composite index.
let updateVexometer = (model: model, msg: vexometerMsg): (model, Tea_Cmd.t<msg>) => {
  let vex = model.vexometer
  switch msg {
  | RecordCancellation => (
      {...model, vexometer: {...vex, recentCancellations: vex.recentCancellations + 1}},
      TauriCmd.recordVexationEvent("cancellation", _result => NoOp),
    )
  | RecordCorrection => (
      {...model, vexometer: {...vex, recentCorrections: vex.recentCorrections + 1}},
      TauriCmd.recordVexationEvent("correction", _result => NoOp),
    )
  | RequestVexationIndex => (
      model,
      TauriCmd.getVexationIndex(index => Vexometer(UpdateVexationIndex(index))),
    )
  | UpdateVexationIndex(index) => (
      {...model, vexometer: {...vex, index}},
      Tea_Cmd.none,
    )
  | ToggleAntiInflammatory(active) => (
      {...model, vexometer: {...vex, antiInflammatoryActive: active}},
      Tea_Cmd.none,
    )
  | SetInertiaDetected(detected) => (
      {...model, vexometer: {...vex, inertiaDetected: detected}},
      Tea_Cmd.none,
    )
  | ResetVexometer => (
      {...model, vexometer: {
        index: 0.0,
        recentCancellations: 0,
        recentCorrections: 0,
        antiInflammatoryActive: false,
        inertiaDetected: false,
      }},
      TauriCmd.recordVexationEvent("reset", _result => NoOp),
    )
  }
}

/// STATE TRANSITION: Orbital Stability
/// Manages the Binary Star co-orbit stability metrics and drift aura.
/// The aura colour reflects orbit health: "indigo" (stable) or "amber" (decaying).
let updateOrbital = (model: model, msg: orbitalMsg): (model, Tea_Cmd.t<msg>) => {
  let orbital = model.orbital
  switch msg {
  | UpdateStability(value) => {
      // Recalculate drift aura colour when stability changes.
      let colour = if value >= 0.7 { "indigo" } else { "amber" }
      ({...model, orbital: {...orbital, stability: value, driftAuraColour: colour}}, Tea_Cmd.none)
    }
  | UpdateDivergence(value) => (
      {...model, orbital: {...orbital, divergenceLevel: value}},
      Tea_Cmd.none,
    )
  | SetDriftAura(colour) => (
      {...model, orbital: {...orbital, driftAuraColour: colour}},
      Tea_Cmd.none,
    )
  }
}

// ===========================================================================
// View & Feedback Sub-Updaters
// ===========================================================================

/// STATE TRANSITION: View Controls
/// Manages pane visibility, view mode, and information humidity level.
/// ParallaxAlign is a compound action that resets to the canonical three-pane layout.
let updateView = (model: model, msg: viewMsg): (model, Tea_Cmd.t<msg>) => {
  switch msg {
  | TogglePaneL => ({...model, paneLVisible: !model.paneLVisible}, Tea_Cmd.none)
  | TogglePaneN => ({...model, paneNVisible: !model.paneNVisible}, Tea_Cmd.none)
  | TogglePaneW => ({...model, paneWVisible: !model.paneWVisible}, Tea_Cmd.none)
  | ToggleProtocolAnalysis => (
      {...model, protocolAnalysisVisible: !model.protocolAnalysisVisible},
      Tea_Cmd.none,
    )
  | SetViewMode(mode) => ({...model, viewMode: mode}, Tea_Cmd.none)
  | SetHumidity(level) => ({...model, humidity: level}, Tea_Cmd.none)
  | ParallaxAlign => (
      // Synchronous horizontal tiling: show all panes in Standard mode.
      {...model, paneLVisible: true, paneNVisible: true, paneWVisible: true, viewMode: Standard},
      Tea_Cmd.none,
    )
  }
}

/// STATE TRANSITION: Feedback-O-Tron
/// Manages the feedback lifecycle: open dialog, submit to backend, cancel,
/// and handle the asynchronous submission result.
let updateFeedback = (model: model, msg: feedbackMsg): (model, Tea_Cmd.t<msg>) => {
  switch msg {
  | OpenFeedback => ({...model, feedbackPending: Some("")}, Tea_Cmd.none)
  | SubmitFeedback(text) => {
      let reportType = switch model.feedbackReportType {
      | Some(t) => t
      | None => "General"
      }
      (
        model,
        TauriCmd.submitFeedback(
          text,
          model.paneN.monologue,
          model.paneW.content,
          reportType,
          result => Feedback(FeedbackSubmissionResult(result)),
        ),
      )
    }
  | CancelFeedback => ({...model, feedbackPending: None}, Tea_Cmd.none)
  | SetReportType(t) => ({...model, feedbackReportType: Some(t)}, Tea_Cmd.none)
  | FeedbackSubmitted => ({...model, feedbackPending: None, feedbackError: None}, Tea_Cmd.none)
  | FeedbackSubmissionResult(result) =>
    switch result {
    | Ok(_) => ({...model, feedbackPending: None, feedbackError: None}, Tea_Cmd.none)
    | Error(err) => ({...model, feedbackError: Some(err)}, Tea_Cmd.none)
    }
  }
}

// ===========================================================================
// Anti-Crash Sub-Updater
// ===========================================================================

/// STATE TRANSITION: Anti-Crash Validation
/// Routes neural tokens through the symbolic validation pipeline (the Circuit
/// Breaker) before they can reach the Task Barycentre. Halts inference when
/// a strict violation is detected, requiring operator intervention to resume.
let updateAntiCrash = (model: model, msg: antiCrashMsg): (model, Tea_Cmd.t<msg>) => {
  switch msg {
  | ValidateToken(token) => {
      // Run the token through the full Anti-Crash pipeline.
      let (newAntiCrash, validatedToken) = AntiCrash.processToken(
        token,
        model.paneL.constraints,
        model.antiCrash,
      )
      // If the token passed validation, add it to the neural stream.
      let newPaneN = switch validatedToken {
      | Some(vt) => {...model.paneN, tokens: Array.concat(model.paneN.tokens, [vt])}
      | None => model.paneN
      }
      ({...model, antiCrash: newAntiCrash, paneN: newPaneN}, Tea_Cmd.none)
    }
  | ValidationPassed(token) => {
      // Token has already been validated externally — mark as validated and add.
      let validatedToken = {...token, validated: true}
      let newPaneN = {...model.paneN, tokens: Array.concat(model.paneN.tokens, [validatedToken])}
      ({...model, paneN: newPaneN}, Tea_Cmd.none)
    }
  | ValidationFailed(_token, reason) => {
      // Record the violation and potentially halt inference.
      let violation = LogicContradiction(reason)
      let newAntiCrash = {
        ...model.antiCrash,
        violations: Array.concat(model.antiCrash.violations, [violation]),
        halted: model.antiCrash.strictMode,
      }
      ({...model, antiCrash: newAntiCrash}, Tea_Cmd.none)
    }
  | RequestOperatorIntervention(_reason) => {
      // Halt the system and wait for operator to review.
      let newAntiCrash = {
        ...model.antiCrash,
        halted: true,
      }
      ({...model, antiCrash: newAntiCrash}, Tea_Cmd.none)
    }
  }
}

// ===========================================================================
// Contractiles Post-Processing (Cognitive Governance)
// ===========================================================================

/// Evaluate all contractiles against the current model state and update their
/// statuses. If any Strict contractile is Violated, halt neural inference as
/// a safety measure. This is called after every state-modifying update in the
/// main orchestrator.
let applyContractiles = (model: model, cmd: Tea_Cmd.t<msg>): (model, Tea_Cmd.t<msg>) => {
  let results = Contractiles.evaluateAll(model, model.contractiles)

  // Update each contractile's status based on evaluation results.
  let updatedContractiles = Array.map(model.contractiles, c => {
    let result = Array.find(results, r => r.contractId === c.id)
    switch result {
    | Some(r) => {...c, status: r.status}
    | None => c
    }
  })

  // Check for any Strict contractile violation — these require halting.
  let hasStrictViolation = Array.some(results, r => {
    let contractile = Array.find(model.contractiles, c => c.id === r.contractId)
    switch contractile {
    | Some(c) =>
      switch (c.enforcement, r.status) {
      | (Strict, Violated(_)) => true
      | _ => false
      }
    | None => false
    }
  })

  let newModel = {...model, contractiles: updatedContractiles}

  // Auto-activate anti-inflammatory when vexation index exceeds threshold (0.7).
  let antiInflammatoryActive = newModel.vexometer.index > 0.7
  let newModel = {
    ...newModel,
    vexometer: {...newModel.vexometer, antiInflammatoryActive},
  }

  // If a Strict contractile is violated, halt neural inference.
  if hasStrictViolation {
    ({...newModel, paneN: {...newModel.paneN, inferenceActive: false}}, cmd)
  } else {
    (newModel, cmd)
  }
}

// ===========================================================================
// VAB Sub-Updater
// ===========================================================================

/// Helper: recompute VAB warnings and capabilities after an assembly change.
/// Called after every add/remove/clear operation to keep the status bar current.
let recomputeVabStatus = (vab: vabState): vabState => {
  let warnings = VabEngine.checkDependencies(vab.server.components, vab.catalog)
  let capabilities = VabEngine.computeCapabilities(vab.server.components, vab.catalog, warnings)
  {...vab, warnings, capabilities}
}

/// STATE TRANSITION: VAB (Verified Assembly Building)
/// Handles server composition: category browsing, component add/remove,
/// server naming, filter/sort, and assembly management. After every
/// assembly-modifying action, recomputes dependency warnings and capabilities.
let updateVab = (model: model, msg: vabMsg): model => {
  let vab = model.vab
  let newVab = switch msg {
  | ToggleVab => {...vab, visible: !vab.visible}
  | SelectCategory(cat) => {...vab, selectedCategory: cat}
  | AddComponent(id) => {
      // Only add if not already present
      let alreadyPresent = Array.some(vab.server.components, c => c === id)
      if alreadyPresent {
        vab
      } else {
        let server = {
          ...vab.server,
          components: Array.concat(vab.server.components, [id]),
        }
        recomputeVabStatus({...vab, server})
      }
    }
  | RemoveComponent(id) => {
      let server = {
        ...vab.server,
        components: Array.filter(vab.server.components, c => c !== id),
      }
      recomputeVabStatus({...vab, server})
    }
  | RenameServer(name) => {...vab, server: {...vab.server, name}}
  | ClearAssembly => {
      let server = {...vab.server, components: []}
      recomputeVabStatus({...vab, server})
    }
  | SetFilterText(text) => {...vab, filterText: text}
  | SetSortBy(sort) => {...vab, sortBy: sort}
  | HoverComponent(id) => {...vab, hoveredComponent: id}
  }
  {...model, vab: newVab}
}

// ===========================================================================
// ===========================================================================
// CloudGuard Sub-Updater
// ===========================================================================

/// Handles all CloudGuard (Cloudflare domain security management) messages.
/// Connection lifecycle, zone listing, settings read/write, DNS records,
/// DNSSEC, hardening operations, audit, and UI state toggling.
let updateCloudGuard = (model: model, msg: cloudguardMsg): (model, Tea_Cmd.t<msg>) => {
  let cg = model.cloudguard
  switch msg {
  // -- Connection lifecycle --
  | VerifyToken => (
      {...model, cloudguard: {...cg, connection: Connecting, loading: true}},
      CloudGuardCmd.verifyToken(result => CloudGuard(TokenVerified(result))),
    )
  | TokenVerified(result) =>
    switch result {
    | Ok(json) => (
        {...model, cloudguard: {...cg, connection: Connected(json), loading: false, error: None}},
        // Auto-fetch zones after successful connection
        CloudGuardCmd.listZones(result => CloudGuard(ZonesLoaded(result))),
      )
    | Error(err) => (
        {...model, cloudguard: {...cg, connection: ConnectionError(err), loading: false, error: Some(err)}},
        Tea_Cmd.none,
      )
    }

  // -- Zone listing --
  | FetchZones => (
      {...model, cloudguard: {...cg, loading: true}},
      CloudGuardCmd.listZones(result => CloudGuard(ZonesLoaded(result))),
    )
  | ZonesLoaded(result) =>
    switch result {
    | Ok(_json) =>
      // TODO: Parse zone JSON array into cfZone records (Phase 2 — proper JSON parsing)
      ({...model, cloudguard: {...cg, loading: false, error: None}}, Tea_Cmd.none)
    | Error(err) => (
        {...model, cloudguard: {...cg, loading: false, error: Some(err)}},
        Tea_Cmd.none,
      )
    }

  // -- Zone selection (multi-select domain ribbon) --
  | ToggleZoneSelection(zoneId) => {
      let newSelected = if Array.includes(cg.selectedZoneIds, zoneId) {
        cg.selectedZoneIds->Array.filter(id => id !== zoneId)
      } else {
        Array.concat(cg.selectedZoneIds, [zoneId])
      }
      ({...model, cloudguard: {...cg, selectedZoneIds: newSelected}}, Tea_Cmd.none)
    }
  | SelectAllZones => {
      let allIds = cg.zones->Array.map(z => z.id)
      ({...model, cloudguard: {...cg, selectedZoneIds: allIds}}, Tea_Cmd.none)
    }
  | DeselectAllZones => (
      {...model, cloudguard: {...cg, selectedZoneIds: []}},
      Tea_Cmd.none,
    )

  // -- Settings read/write --
  | FetchSettings(zoneId) => (
      {...model, cloudguard: {...cg, loading: true}},
      CloudGuardCmd.getSettings(zoneId, result => CloudGuard(SettingsLoaded(result))),
    )
  | SettingsLoaded(result) =>
    switch result {
    | Ok(_json) =>
      // TODO: Parse settings JSON into cfSetting records (Phase 2)
      ({...model, cloudguard: {...cg, loading: false}}, Tea_Cmd.none)
    | Error(err) => (
        {...model, cloudguard: {...cg, loading: false, error: Some(err)}},
        Tea_Cmd.none,
      )
    }
  | ToggleSetting(settingId) => {
      let newSettings = cg.settings->Array.map(s => {
        if s.id === settingId {
          let newValue = switch s.value {
          | StringValue("on") => StringValue("off")
          | StringValue("off") => StringValue("on")
          | BoolValue(b) => BoolValue(!b)
          | other => other
          }
          {...s, value: newValue, modified: true}
        } else {
          s
        }
      })
      ({...model, cloudguard: {...cg, settings: newSettings}}, Tea_Cmd.none)
    }
  | UpdateSettingValue(settingId, value) => {
      let newSettings = cg.settings->Array.map(s => {
        if s.id === settingId {
          {...s, value: StringValue(value), modified: true}
        } else {
          s
        }
      })
      ({...model, cloudguard: {...cg, settings: newSettings}}, Tea_Cmd.none)
    }
  | PushChanges => {
      // Collect modified settings and push them
      let _modified = cg.settings->Array.filter(s => s.modified)
      // TODO: Build JSON payload and call updateSettingsBatch (Phase 2)
      ({...model, cloudguard: {...cg, loading: true}}, Tea_Cmd.none)
    }
  | ChangesPushed(result) =>
    switch result {
    | Ok(_json) => ({...model, cloudguard: {...cg, loading: false}}, Tea_Cmd.none)
    | Error(err) => (
        {...model, cloudguard: {...cg, loading: false, error: Some(err)}},
        Tea_Cmd.none,
      )
    }

  // -- DNS records --
  | FetchDnsRecords(zoneId) => (
      {...model, cloudguard: {...cg, loading: true}},
      CloudGuardCmd.listDnsRecords(zoneId, result => CloudGuard(DnsRecordsLoaded(result))),
    )
  | DnsRecordsLoaded(result) =>
    switch result {
    | Ok(_json) =>
      // TODO: Parse DNS records JSON (Phase 3)
      ({...model, cloudguard: {...cg, loading: false}}, Tea_Cmd.none)
    | Error(err) => (
        {...model, cloudguard: {...cg, loading: false, error: Some(err)}},
        Tea_Cmd.none,
      )
    }
  | DeleteDnsRecord(zoneId, recordId) => (
      {...model, cloudguard: {...cg, loading: true}},
      CloudGuardCmd.deleteDnsRecord(zoneId, recordId, result => CloudGuard(DnsRecordDeleted(result))),
    )
  | DnsRecordDeleted(result) =>
    switch result {
    | Ok(_json) => ({...model, cloudguard: {...cg, loading: false}}, Tea_Cmd.none)
    | Error(err) => (
        {...model, cloudguard: {...cg, loading: false, error: Some(err)}},
        Tea_Cmd.none,
      )
    }

  // -- DNSSEC --
  | FetchDnssec(zoneId) => (
      {...model, cloudguard: {...cg, loading: true}},
      CloudGuardCmd.getDnssec(zoneId, result => CloudGuard(DnssecLoaded(result))),
    )
  | DnssecLoaded(result) =>
    switch result {
    | Ok(_json) => ({...model, cloudguard: {...cg, loading: false}}, Tea_Cmd.none)
    | Error(err) => (
        {...model, cloudguard: {...cg, loading: false, error: Some(err)}},
        Tea_Cmd.none,
      )
    }
  | EnableDnssec(zoneId) => (
      {...model, cloudguard: {...cg, loading: true}},
      CloudGuardCmd.enableDnssec(zoneId, result => CloudGuard(DnssecEnabled(result))),
    )
  | DnssecEnabled(result) =>
    switch result {
    | Ok(_json) => ({...model, cloudguard: {...cg, loading: false}}, Tea_Cmd.none)
    | Error(err) => (
        {...model, cloudguard: {...cg, loading: false, error: Some(err)}},
        Tea_Cmd.none,
      )
    }

  // -- Hardening --
  | HardenSelected => {
      // Harden first selected zone; subsequent zones handled by ZoneHardened
      switch Array.get(cg.selectedZoneIds, 0) {
      | Some(firstZone) => (
          {...model, cloudguard: {
            ...cg,
            loading: true,
            bulkProgress: Some({
              total: Array.length(cg.selectedZoneIds),
              completed: 0,
              failed: 0,
              currentDomain: cg.zones->Array.find(z => z.id === firstZone)->Option.map(z => z.name),
              startedAt: "",
              errors: [],
            }),
          }},
          CloudGuardCmd.hardenZone(firstZone, result => CloudGuard(ZoneHardened(result))),
        )
      | None => (model, Tea_Cmd.none)
      }
    }
  | HardenZone(zoneId) => (
      {...model, cloudguard: {...cg, loading: true}},
      CloudGuardCmd.hardenZone(zoneId, result => CloudGuard(ZoneHardened(result))),
    )
  | ZoneHardened(result) => {
      let progress = switch cg.bulkProgress {
      | Some(p) =>
        switch result {
        | Ok(_) => Some({...p, completed: p.completed + 1})
        | Error(err) => Some({
            ...p,
            completed: p.completed + 1,
            failed: p.failed + 1,
            errors: Array.concat(p.errors, [("unknown", err)]),
          })
        }
      | None => None
      }
      // Check if there are more zones to harden
      let nextIndex = switch progress {
      | Some(p) => p.completed
      | None => 0
      }
      let cmd = if nextIndex < Array.length(cg.selectedZoneIds) {
        switch Array.get(cg.selectedZoneIds, nextIndex) {
        | Some(nextZone) =>
          CloudGuardCmd.hardenZone(nextZone, result => CloudGuard(ZoneHardened(result)))
        | None => Tea_Cmd.none
        }
      } else {
        Tea_Cmd.none // All done
      }
      let isDone = nextIndex >= Array.length(cg.selectedZoneIds)
      (
        {...model, cloudguard: {...cg, bulkProgress: progress, loading: !isDone}},
        cmd,
      )
    }

  // -- Audit --
  | RunAudit => (
      {...model, cloudguard: {...cg, loading: true, showAudit: true}},
      Tea_Cmd.none, // TODO: Backend audit command (Phase 4)
    )
  | AuditComplete(result) =>
    switch result {
    | Ok(_json) => ({...model, cloudguard: {...cg, loading: false}}, Tea_Cmd.none)
    | Error(err) => (
        {...model, cloudguard: {...cg, loading: false, error: Some(err)}},
        Tea_Cmd.none,
      )
    }

  // -- Offline config --
  | DownloadConfig => (
      {...model, cloudguard: {...cg, loading: true}},
      Tea_Cmd.none, // TODO: Config download command (Phase 5)
    )
  | ConfigDownloaded(result) =>
    switch result {
    | Ok(_json) => ({...model, cloudguard: {...cg, loading: false}}, Tea_Cmd.none)
    | Error(err) => (
        {...model, cloudguard: {...cg, loading: false, error: Some(err)}},
        Tea_Cmd.none,
      )
    }

  // -- UI state --
  | ToggleCloudGuard => {
      let newVisible = !cg.visible
      let cmd = if newVisible && cg.connection === Disconnected {
        // Auto-connect when opening the panel
        CloudGuardCmd.verifyToken(result => CloudGuard(TokenVerified(result)))
      } else {
        Tea_Cmd.none
      }
      ({...model, cloudguard: {...cg, visible: newVisible}}, cmd)
    }
  | SetCategory(cat) => (
      {...model, cloudguard: {...cg, activeCategory: cat}},
      Tea_Cmd.none,
    )
  | SetFilterText(text) => (
      {...model, cloudguard: {...cg, filterText: text}},
      Tea_Cmd.none,
    )
  | SetSettingFilter(text) => (
      {...model, cloudguard: {...cg, settingFilter: text}},
      Tea_Cmd.none,
    )
  | ToggleAuditPanel => (
      {...model, cloudguard: {...cg, showAudit: !cg.showAudit}},
      Tea_Cmd.none,
    )
  | ToggleDiffPanel => (
      {...model, cloudguard: {...cg, showDiff: !cg.showDiff}},
      Tea_Cmd.none,
    )
  }
}

// ===========================================================================
// Main Orchestrator
// ===========================================================================

/// Determines whether a message should trigger an auto-save.
/// Returns false for NoOp and SaveState (no state change), true for everything else.
let shouldAutoSave = (msg: msg): bool => {
  switch msg {
  | NoOp => false
  | SaveState => false
  | _ => true
  }
}

/// ORCHESTRATOR: The main entry point for state updates.
/// Routes each message to its domain-specific sub-updater, then applies
/// contractile evaluation as a post-processing cognitive governance step.
///
/// The contractile check runs after every state-modifying update (not NoOp)
/// to enforce the Binary Star system's behavioural contracts:
///   - Orbital Stability Bound (Strict)
///   - Vexation Ceiling (Adaptive)
///   - Divergence Limit (Warn)
///   - Autonomy Bound (Strict)
let update = (model: model, msg: msg): (model, Tea_Cmd.t<msg>) => {
  let (newModel, cmd) = switch msg {
  | PaneL(subMsg) => (updatePaneL(model, subMsg), Tea_Cmd.none)
  | PaneN(subMsg) => (updatePaneN(model, subMsg), Tea_Cmd.none)
  | PaneW(subMsg) => updatePaneW(model, subMsg)
  | VeriSimDB(subMsg) => updateVeriSimDB(model, subMsg)
  | Echidna(subMsg) => updateEchidna(model, subMsg)
  | Vexometer(subMsg) => updateVexometer(model, subMsg)
  | Orbital(subMsg) => updateOrbital(model, subMsg)
  | View(subMsg) => updateView(model, subMsg)
  | Feedback(subMsg) => updateFeedback(model, subMsg)
  | AntiCrash(subMsg) => updateAntiCrash(model, subMsg)
  | Vab(subMsg) => (updateVab(model, subMsg), Tea_Cmd.none)
  | CloudGuard(subMsg) => updateCloudGuard(model, subMsg)
  | SaveState => {
      // Imperative: persist current state to localStorage.
      Storage.save(model)
      (model, Tea_Cmd.none)
    }
  | NoOp => (model, Tea_Cmd.none)
  }

  // Post-processing: evaluate contractiles after every state-modifying update.
  // Skip for NoOp to avoid unnecessary computation.
  switch msg {
  | NoOp => (newModel, cmd)
  | _ => applyContractiles(newModel, cmd)
  }
}
